export default function AdeptPowersList() {
  const powers = {
    adeptSpell: {
      power: "Adept Spell",
      prerequisite: "-",
      activation: "Simple Action",
      cost: "1 PP",
      source: "SR5:HT",
    },
    adeptAccident: {
      power: "Adept Accident",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:HT",
    },
    adrenalineBoost: {
      power: "Adrenaline Boost",
      prerequisite: "-",
      activation: "Free Action",
      cost: "0.25 PP per level",
      source: "Core",
    },
    analytics: {
      power: "Analytics",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "SR5:SG",
    },
    animalEmpathy: {
      power: "Animal Empathy",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SG",
    },
    astralPerception: {
      power: "Astral Perception",
      prerequisite: "-",
      activation: "Simple Action",
      cost: "1 PP",
      source: "Core",
    },
    attributeBoost: {
      power: "Attribute Boost (Attribute)",
      prerequisite: "-",
      activation: "Simple Action",
      cost: "0.25 PP per level",
      source: "Core",
    },
    authoritativeTone: {
      power: "Authoritative Tone",
      prerequisite: "-",
      activation: "-",
      cost: "0.50 PP per level (Max 3)",
      source: "SR5:SG",
    },
    berserk: {
      power: "Berserk",
      prerequisite: "-",
      activation: "Simple Action",
      cost: "1 PP",
      source: "SR5:SG",
    },
    berserkersRage: {
      power: "Berserker's Rage",
      prerequisite: "Berserk",
      activation: "Complex Action",
      cost: "1 PP",
      source: "SR5:SG",
    },
    blindFighting: {
      power: "Blind Fighting",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    cloak: {
      power: "Cloak",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SG",
    },
    combatSense: {
      power: "Combat Sense",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    commandingVoiceSG: {
      power: "Commanding Voice (SR5:SG)",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 3)",
      source: "SR5:SG",
    },
    commandingVoiceSSo: {
      power: "Commanding Voice (SR5:SSo)",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SSo",
    },
    coolResolve: {
      power: "Cool Resolve",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP per level",
      source: "SR5:SG",
    },
    counterstrike: {
      power: "Counterstrike",
      prerequisite: "Interrupt (-5 Initiative)",
      activation: "-",
      cost: "1 PP per level",
      source: "SR5:SG",
    },
    criticalStrikeSkill: {
      power: "Critical Strike (Skill)",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "Core",
    },
    dangerSense: {
      power: "Danger Sense",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "Core",
    },
    demara: {
      power: "Demara",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SSp",
    },
    eideticSenseMemory: {
      power: "Eidetic Sense Memory",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SSp",
    },
    elementalBody: {
      power: "Elemental Body",
      prerequisite: "Elemental Strike",
      activation: "Complex Action",
      cost: "1 PP",
      source: "SR5:SG",
    },
    elementalStrike: {
      power: "Elemental Strike",
      prerequisite: "Killing Hands",
      activation: "Simple Action",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    elementalWeapon: {
      power: "Elemental Weapon",
      prerequisite: "Weapon Foci",
      activation: "Simple Action",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    empathicHealing: {
      power: "Empathic Healing",
      prerequisite: "-",
      activation: "2 turns per box",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    enhancedAccuracySkill: {
      power: "Enhanced Accuracy (Skill)",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP",
      source: "Core",
    },
    enhancedPerception: {
      power: "Enhanced Perception",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    enthrallingPerformance: {
      power: "Enthralling Performance",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SSp",
    },
    facialSculpt: {
      power: "Facial Sculpt",
      prerequisite: "-",
      activation: "Complex Action",
      cost: "0.25 PP per level",
      source: "SR5:SG",
    },
    feignDeath: {
      power: "Feign Death",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:BB",
    },
    feignIllness: {
      power: "Feign Illness",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:BB",
    },
    flexibility: {
      power: "Flexibility",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 3)",
      source: "SR5:SG",
    },
    focusedArchery: {
      power: "Focused Archery",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 3)",
      source: "SR5:HT",
    },
    freefall: {
      power: "Freefall",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SG",
    },
    hangTime: {
      power: "Hang Time",
      prerequisite: "-",
      activation: "Simple Action",
      cost: "0.25 PP per level",
      source: "SR5:SG",
    },
    heightenedConcern: {
      power: "Heightened Concern",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SSp",
    },
    improvedAbilitySkill: {
      power: "Improved Ability (Skill)",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    improvedPhysicalAttribute: {
      power: "Improved Physical Attribute",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP per level",
      source: "Core",
    },
    improvedPotentialLimit: {
      power: "Improved Potential (Limit)",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    improvedReflexes: {
      power: "Improved Reflexes",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP + level (Max 3)",
      source: "Core",
    },
    improvedSense: {
      power: "Improved Sense",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP each",
      source: "Core",
    },
    indomitableWill: {
      power: "Indomitable Will",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SSp",
    },
    inertiaStrike: {
      power: "Inertia Strike",
      prerequisite: "-",
      activation: "Free Action",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    ironGut: {
      power: "Iron Gut",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SSp",
    },
    ironLungs: {
      power: "Iron Lungs",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SSp",
    },
    ironWill: {
      power: "Iron Will",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "SR5:SSp",
    },
    keratinControl: {
      power: "Keratin Control",
      prerequisite: "-",
      activation: "Free Action",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    kiai: {
      power: "Kiai",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 6)",
      source: "SR5:HT",
    },
    killingHands: {
      power: "Killing Hands",
      prerequisite: "-",
      activation: "Free Action",
      cost: "0.5 PP",
      source: "Core",
    },
    kinesics: {
      power: "Kinesics",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "Core",
    },
    kinesicsMastery: {
      power: "Kinesics Mastery",
      prerequisite: "Kinesics",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    lightBody: {
      power: "Light Body",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "Core",
    },
    lightTouch: {
      power: "Light Touch",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SSo",
    },
    linguistics: {
      power: "Linguistics",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP",
      source: "SR5:SG",
    },
    livingFocus: {
      power: "Living Focus",
      prerequisite: "-",
      activation: "Free Action",
      cost: "1 PP",
      source: "SR5:SSp",
    },
    maintainWarmth: {
      power: "Maintain Warmth",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP",
      source: "SR5:SSp",
    },
    magicSense: {
      power: "Magic Sense",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    masterArcher: {
      power: "Master Archer",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:HT",
    },
    melaninControl: {
      power: "Melanin Control",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    memoryDisplacement: {
      power: "Memory Displacement",
      prerequisite: "-",
      activation: "Complex Action",
      cost: "0.25 PP",
      source: "SR5:SSp",
    },
    metabolicControl: {
      power: "Metabolic Control",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    mimic: {
      power: "Mimic",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 6)",
      source: "SR5:SSo",
    },
    missileMastery: {
      power: "Missile Mastery",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SG",
    },
    missileParry: {
      power: "Missile Parry",
      prerequisite: "-",
      activation: "Interrupt (-5 Initiative)",
      cost: "0.25 PP per level",
      source: "Core",
    },
    motionSense: {
      power: "Motion Sense",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    mysticArmor: {
      power: "Mystic Armor",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    naturalImmunity: {
      power: "Natural Immunity",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "Core",
    },
    nerveStrikeSG: {
      power: "Nerve Strike (SR5:SG)",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SG",
    },
    nerveStrikeSSo: {
      power: "Nerve Strike (SR5:SSo)",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SSo",
    },
    nimbleFingersSG: {
      power: "Nimble Fingers (SR5:SG)",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP",
      source: "SR5:SG",
    },
    nimbleFingersSSo: {
      power: "Nimble Fingers (SR5:SSo)",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP",
      source: "SR5:SSo",
    },
    painRelief: {
      power: "Pain Relief",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SG",
    },
    painResistance: {
      power: "Pain Resistance",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    penetratingStrike: {
      power: "Penetrating Strike",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 4)",
      source: "SR5:SG",
    },
    piercingSenses: {
      power: "Piercing Senses",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SSp",
    },
    plagueCloud: {
      power: "Plague Cloud",
      prerequisite: "Free Action",
      activation: "0.5 PP",
      source: "SR5:SG",
    },
    powerSwimming: {
      power: "Power Swimming",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SSp",
    },
    precisionThrowing: {
      power: "Precision Throwing",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 3)",
      source: "SR5:HT",
    },
    rapidDraw: {
      power: "Rapid Draw",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    rapidHealing: {
      power: "Rapid Healing",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    riposte: {
      power: "Riposte",
      prerequisite: "Interrupt (-5 Initiative)",
      activation: "-",
      cost: "0.5 PP per level",
      source: "SR5:SG",
    },
    rooting: {
      power: "Rooting",
      prerequisite: "Simple Action",
      activation: "0.25 PP per level",
      source: "SR5:SSp",
    },
    skate: {
      power: "Skate",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SG",
    },
    smashingBlow: {
      power: "Smashing Blow",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "SR5:SG",
    },
    spellResistance: {
      power: "Spell Resistance",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    spiritClaw: {
      power: "Spirit Claw",
      prerequisite: "Free Action",
      activation: "0.25 PP",
      source: "SR5:SG",
    },
    spiritRam: {
      power: "Spirit Ram",
      prerequisite: "Simple Action",
      activation: "0.5 PP",
      source: "SR5:SG",
    },
    stillness: {
      power: "Stillness",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level (Max 3)",
      source: "SR5:SG",
    },
    sustenance: {
      power: "Sustenance",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP",
      source: "SR5:SG",
    },
    temperatureTolerance: {
      power: "Temperature Tolerance",
      prerequisite: "-",
      activation: "-",
      cost: "0.25 PP per level",
      source: "SR5:SG",
    },
    threeDimensionalMemory: {
      power: "Three-Dimensional Memory",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    toxicStrike: {
      power: "Toxic Strike",
      prerequisite: "Killing Hands",
      activation: "Simple Action",
      cost: "0.5 PP",
      source: "SR5:SG",
    },
    tracelessWalk: {
      power: "Traceless Walk",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP",
      source: "Core",
    },
    transmitDamage: {
      power: "Transmit Damage",
      prerequisite: "-",
      activation: "-",
      cost: "1 PP per level",
      source: "SR5:BB",
    },
    voiceControl: {
      power: "Voice Control",
      prerequisite: "-",
      activation: "-",
      cost: "0.5 PP per level",
      source: "Core",
    },
    wallRunning: {
      power: "Wall Running",
      prerequisite: "Simple Action",
      activation: "0.5 PP",
      source: "Core",
    },
  };

  return powers;
}
