export default function returnMisc() {
  const misc = {
    explosives: {
      ammoniumNitrate: {
        type: "Explosives",
        name: "Ammonium nitrate",
        rating: 4,
        availability: 5,
        cost: "80¥ per KG",
        source: "SR5:R&G",
      },
      anfo: {
        type: "Explosives",
        name: "ANFO",
        rating: 6,
        availability: 7,
        cost: "100¥ per KG",
        source: "SR5:R&G",
      },
      binary: {
        type: "Explosives",
        name: "Binary",
        rating: "1-20",
        availability: "18F",
        cost: "Rating x 125¥ per KG",
        source: "SR5:R&G",
      },
      commercial: {
        type: "Explosives",
        name: "Commercial",
        rating: 5,
        availability: "8R",
        cost: "100¥ per KG",
        source: "Core",
      },
      detonatingCordLowYield: {
        type: "Explosives",
        name: "Detonating Cord, Low Yield",
        rating: 3,
        availability: "10R",
        cost: "100¥ per meter",
        source: "SR5:R&G",
      },
      detonatingCordHighYield: {
        type: "Explosives",
        name: "Detonating Cord, High Yield",
        rating: 6,
        availability: "14R",
        cost: "150¥ per meter",
        source: "SR5:R&G",
      },
      dynamite: {
        type: "Explosives",
        name: "Dynamite",
        rating: 3,
        availability: "8R",
        cost: "350¥ per KG",
        source: "SR5:R&G",
      },
      foam: {
        type: "Explosives",
        name: "Foam",
        rating: "6-25",
        availability: "12F",
        cost: "Rating x 100¥ per KG",
        source: "Core",
      },
      linearCharge: {
        type: "Explosives",
        name: "Linear Charge",
        rating: "1-25",
        availability: "16R",
        cost: "Rating x 250¥ per KG",
        source: "SR5:R&G",
      },
      liquid: {
        type: "Explosives",
        name: "Liquid",
        rating: "1-25",
        availability: "16F",
        cost: "Rating x 150¥ per KG",
        source: "SR5:R&G",
      },
      nitroglycerin: {
        type: "Explosives",
        name: "Nitroglycerin",
        rating: 6,
        availability: "11R",
        cost: "350¥ per KG",
        source: "SR5:R&G",
      },
      plastic: {
        type: "Explosives",
        name: "Plastic",
        rating: "6-25",
        availability: "16F",
        cost: "Rating x 100¥ per KG",
        source: "Core",
      },
      tnt: {
        type: "Explosives",
        name: "TNT",
        rating: 5,
        availability: "12R",
        cost: "200¥ per KG",
        source: "SR5:R&G",
      },
    },
    chemicals: {
      glueSolvent: {
        type: "CHEMICALS",
        name: "Glue solvent",
        availability: 2,
        cost: "90¥",
        source: "Core",
      },
      glueSprayer: {
        type: "CHEMICALS",
        name: "Glue sprayer",
        availability: 2,
        cost: "150¥",
        source: "Core",
      },
      thermiteBurningBar: {
        type: "CHEMICALS",
        name: "Thermite Burning Bar",
        availability: "16R",
        cost: "500¥",
        source: "Core",
      },
      ultraGlideIndustrialLubricant: {
        type: "CHEMICALS",
        name: "Ultra-Glide Industrial Lubricant",
        availability: 12,
        cost: "30¥ (per liter)",
        source: "SR5:R&G",
      },
      holdFastAdhesiveSpray: {
        type: "CHEMICALS",
        name: "Hold-Fast Adhesive Spray",
        availability: 12,
        cost: "50¥",
        source: "SR5:R&G",
      },
    },
    survivalGear: {
      chemsuit: {
        type: "GEAR",
        name: "Chemsuit (R 1-6)",
        availability: "Rating x 2",
        cost: "Rating x 150¥",
        source: "Core",
      },
      climbingGear: {
        type: "GEAR",
        name: "Climbing gear",
        availability: "-",
        cost: "200¥",
        source: "Core",
      },
      divingGear: {
        type: "GEAR",
        name: "Diving gear",
        availability: 6,
        cost: "2,000¥",
        source: "Core",
      },
      flashlight: {
        type: "GEAR",
        name: "Flashlight",
        availability: "-",
        cost: "25¥",
        source: "Core",
      },
      gasMask: {
        type: "GEAR",
        name: "Gas mask",
        availability: "-",
        cost: "200¥",
        source: "Core",
      },
      geckoTapeGloves: {
        type: "GEAR",
        name: "Gecko tape gloves",
        availability: 12,
        cost: "250¥",
        source: "Core",
      },
      hazmatSuit: {
        type: "GEAR",
        name: "Hazmat suit",
        availability: 8,
        cost: "3,000¥",
        source: "Core",
      },
      lightStick: {
        type: "GEAR",
        name: "Light stick",
        availability: "-",
        cost: "25¥",
        source: "Core",
      },
      magnesiumTorch: {
        type: "GEAR",
        name: "Magnesium torch",
        availability: "-",
        cost: "5¥",
        source: "Core",
      },
      microFlareLauncher: {
        type: "GEAR",
        name: "Micro flare launcher",
        availability: "-",
        cost: "175¥",
        source: "Core",
      },
      microFlares: {
        type: "GEAR",
        name: "Micro flares",
        availability: "-",
        cost: "25¥",
        source: "Core",
      },
      rappellingGloves: {
        type: "GEAR",
        name: "Rappelling gloves",
        availability: "-",
        cost: "50¥",
        source: "Core",
      },
      respirator: {
        type: "GEAR",
        name: "Respirator (R 1-6)",
        availability: "-",
        cost: "Rating x 50¥",
        source: "Core",
      },
      survivalKit: {
        type: "GEAR",
        name: "Survival Kit",
        availability: 4,
        cost: "200¥",
        source: "Core",
      },
      aresPed: {
        type: "GEAR",
        name: "Ares Ped (Personal Extrication Device) Mark III",
        availability: "10R",
        cost: "2,500¥",
        source: "SR5:R&G",
      },
    },
    nanoGear: {
      altskinPerApplication: {
        type: "DEVICE",
        name: "Altskin (Per Application)",
        subtype: "Hard",
        availability: 10,
        cost: "1,250¥",
        source: "SR5:CF",
      },
      altskinArmor: {
        type: "DEVICE",
        name: "Altskin (Armor)",
        subtype: "-",
        availability: "+3",
        cost: "+500¥",
        source: "SR5:CF",
      },
      altskinChameleon: {
        type: "DEVICE",
        name: "Altskin (Chameleon)",
        subtype: "-",
        availability: "+2",
        cost: "+250¥",
        source: "SR5:CF",
      },
      altskinNewprint: {
        type: "DEVICE",
        name: "Altskin (Newprint)",
        subtype: "-",
        availability: "+4F",
        cost: "+(Rating x 200¥)",
        source: "SR5:CF",
      },
      altskinSealer: {
        type: "DEVICE",
        name: "Altskin (Sealer)",
        subtype: "-",
        availability: "+1",
        cost: "+250¥",
        source: "SR5:CF",
      },
      altskinShifter: {
        type: "DEVICE",
        name: "Altskin (Shifter)",
        subtype: "-",
        availability: "+2",
        cost: "+250¥",
        source: "SR5:CF",
      },
      etchers: {
        type: "DEVICE",
        name: "Etchers",
        subtype: "Hard",
        availability: 8,
        cost: "500¥",
        source: "SR5:CF",
      },
      monowirePerMeter: {
        type: "DEVICE",
        name: "Monowire (Per Meter)",
        subtype: "Hard",
        availability: "14R",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      nanopasteDisguiseContainerSmall: {
        type: "DEVICE",
        name: "Nanopaste Disguise Container (Small)",
        subtype: "Hard",
        availability: "12F",
        cost: "350¥",
        source: "SR5:CF",
      },
      nanopasteDisguiseContainerLarge: {
        type: "DEVICE",
        name: "Nanopaste Disguise Container (Large)",
        subtype: "Hard",
        availability: "16F",
        cost: "700¥",
        source: "SR5:CF",
      },
      nanoscanner: {
        type: "DEVICE",
        name: "Nanoscanner",
        subtype: "-",
        availability: 8,
        cost: "As Sensor¥",
        source: "SR5:CF",
      },
      nanospyPerApplication: {
        type: "DEVICE",
        name: "NanoSpy (Per Application)",
        subtype: "Hard",
        availability: "14F",
        cost: "10,000¥",
        source: "SR5:CF",
      },
      saviorMedkit: {
        type: "DEVICE",
        name: "Savior Medkit",
        subtype: "-",
        availability: 6,
        cost: "2,000¥",
        source: "SR5:CF",
      },
      saviorMedkitSupplies: {
        type: "DEVICE",
        name: "Savior Medkit Supplies",
        subtype: "Hard",
        availability: 4,
        cost: "300¥",
        source: "SR5:CF",
      },
      smartCorrosivesPerApplication: {
        type: "DEVICE",
        name: "Smart Corrosives (Per Application)",
        subtype: "Soft",
        availability: "10R",
        cost: "4,000¥",
        source: "SR5:CF",
      },
      universalSealantPerApplication: {
        type: "DEVICE",
        name: "Universal Sealant (Per Application)",
        subtype: "Hard",
        availability: 10,
        cost: "250¥",
        source: "SR5:CF",
      },
    },
  };
  return misc;
}
