export default function returnArmor() {
  const armors = {
    clothingAndArmor: {
      clothing: {
        article: "Clothing",
        armorRating: 0,
        capacity: 0,
        availability: "-",
        cost: "20¥ - 100,000¥",
        source: "Core",
      },
      electrochromicModification: {
        article: "Electrochromic Modification",
        armorRating: "-",
        capacity: "-",
        availability: "+2",
        cost: "+500¥",
        source: "Core",
      },
      feedbackClothing: {
        article: "Feedback Clothing",
        armorRating: "-",
        capacity: "-",
        availability: 8,
        cost: "+500¥",
        source: "Core",
      },
      synthLeather: {
        article: "(Synth)Leather",
        armorRating: 4,
        capacity: 4,
        availability: "-",
        cost: "+200¥",
        source: "Core",
      },
      armanteSuit: {
        article: "Armante Suit",
        armorRating: 8,
        capacity: 4,
        availability: 10,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
      armanteDress: {
        article: "Armante Dress",
        armorRating: 8,
        capacity: 4,
        availability: 10,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonBerwickSuit: {
        article: "Mortimer of London, Berwick Suit",
        armorRating: 9,
        capacity: 5,
        availability: 9,
        cost: "2,600¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonBerwickDress: {
        article: "Mortimer of London, Berwick Dress",
        armorRating: 8,
        capacity: 4,
        availability: 8,
        cost: "2,300¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonCrimsonSkySuit: {
        article: "Mortimer of London, Crimson Sky Suit",
        armorRating: 8,
        capacity: 5,
        availability: 6,
        cost: "2,400¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonSummitSuit: {
        article: "Mortimer of London, Summit Suit",
        armorRating: 8,
        capacity: 6,
        availability: 7,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonSummitDress: {
        article: "Mortimer of London, Summit Dress",
        armorRating: 7,
        capacity: 5,
        availability: 7,
        cost: "2,200¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonGreatcoatCoat: {
        article: "Mortimer of London, Greatcoat Coat",
        armorRating: "10/+3",
        capacity: 10,
        availability: 8,
        cost: "3,000¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonUlyssesCoat: {
        article: "Mortimer of London, Ulysses Coat",
        armorRating: "10/+3",
        capacity: 12,
        availability: 8,
        cost: "3,100¥",
        source: "SR5:R&G",
      },
      mortimerOfLondonArgentumCoat: {
        article: "Mortimer of London, Argentum Coat",
        armorRating: "12/+4",
        capacity: 14,
        availability: 10,
        cost: "3,600¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfCups: {
        article: "Vashon Island, Ace of Cups",
        armorRating: 9,
        capacity: 8,
        availability: 6,
        cost: "1,600¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfSwords: {
        article: "Vashon Island, Ace of Swords",
        armorRating: 7,
        capacity: 8,
        availability: 6,
        cost: "1,300¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfWands: {
        article: "Vashon Island, Ace of Wands",
        armorRating: 6,
        capacity: 8,
        availability: 6,
        cost: "1,200¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfCoins: {
        article: "Vashon Island, Ace of Coins",
        armorRating: 7,
        capacity: 10,
        availability: 4,
        cost: "2,100¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfSpades: {
        article: "Vashon Island, Ace of Spades",
        armorRating: 7,
        capacity: 6,
        availability: 6,
        cost: "1,000¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfClubs: {
        article: "Vashon Island, Ace of Clubs",
        armorRating: 7,
        capacity: 6,
        availability: 6,
        cost: "1,000¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfHearts: {
        article: "Vashon Island, Ace of Hearts",
        armorRating: 7,
        capacity: 6,
        availability: 6,
        cost: "1,000¥",
        source: "SR5:R&G",
      },
      vashonIslandAceOfDiamonds: {
        article: "Vashon Island, Ace of Diamonds",
        armorRating: 8,
        capacity: 6,
        availability: 8,
        cost: "1,400¥",
        source: "SR5:R&G",
      },
      vashonIslandSteampunk: {
        article: "Vashon Island, Steampunk",
        armorRating: 10,
        capacity: 14,
        availability: 7,
        cost: "2,250¥",
        source: "SR5:R&G",
      },
      vashonIslandSynergistBusinessLine: {
        article: "Vashon Island, Synergist Business Line",
        armorRating: 9,
        capacity: 5,
        availability: 8,
        cost: "1,500¥",
        source: "SR5:R&G",
      },
      vashonIslandSynergistBusinessLineLongcoat: {
        article: "Vashon Island, Synergist Business Line Longcoat",
        armorRating: "10 / +3",
        capacity: 6,
        availability: 8,
        cost: "2,300¥",
        source: "SR5:R&G",
      },
      vashonIslandSleepingTiger: {
        article: "Vashon Island, Sleeping Tiger",
        armorRating: 13,
        capacity: 10,
        availability: 10,
        cost: "13,500¥",
        source: "SR5:R&G",
      },
      executiveSuite: {
        article: "Executive Suite",
        armorRating: 12,
        capacity: 4,
        availability: 12,
        cost: "2,000¥",
        source: "SR5:R&G",
      },
      heritage: {
        article: "Heritage",
        armorRating: "4/6/8/10/12",
        capacity: "Armor ÷ 2",
        availability: 16,
        cost: "2,000¥ + (Armor Rating x 500)",
        source: "SR5:R&G",
      },
      nightshadeMoonsilver: {
        article: "Nightshade/Moonsilver",
        armorRating: 7,
        capacity: 2,
        availability: 10,
        cost: "8,500¥",
        source: "SR5:R&G",
      },
      secondSkin: {
        article: "Second Skin",
        armorRating: "6/+2",
        capacity: 2,
        availability: 14,
        cost: "12,000¥",
        source: "SR5:R&G",
      },
      globetrotterJacket: {
        article: "Globetrotter Jacket",
        armorRating: 12,
        capacity: 10,
        availability: 10,
        cost: "1,300¥",
        source: "SR5:R&G",
      },
      globetrotterVest: {
        article: "Globetrotter Vest",
        armorRating: 9,
        capacity: 10,
        availability: 7,
        cost: "900¥",
        source: "SR5:R&G",
      },
      globetrotterClothing: {
        article: "Globetrotter Clothing",
        armorRating: 7,
        capacity: 10,
        availability: 6,
        cost: "600¥",
        source: "SR5:R&G",
      },
      wildHunt: {
        article: "Wild Hunt",
        armorRating: 12,
        capacity: 10,
        availability: 12,
        cost: "3,000¥",
        source: "SR5:R&G",
      },
      industrious: {
        article: "Industrious",
        armorRating: 9,
        capacity: 6,
        availability: 6,
        cost: "1,100¥",
        source: "SR5:R&G",
      },
      bigGameHunter: {
        article: "Big Game Hunter",
        armorRating: 14,
        capacity: 12,
        availability: 12,
        cost: "5,000¥",
        source: "SR5:R&G",
      },
      rapidTransit: {
        article: "Rapid Transit",
        armorRating: 9,
        capacity: 6,
        availability: 10,
        cost: "400+¥",
        source: "SR5:R&G",
      },
      actioneerBusinessClothes: {
        article: "Actioneer Business Clothes",
        armorRating: 8,
        capacity: 8,
        availability: 8,
        cost: "1,500¥",
        source: "Core",
      },
      armorClothing: {
        article: "Armor Clothing",
        armorRating: 6,
        capacity: 6,
        availability: 2,
        cost: "450¥",
        source: "Core",
      },
      armorJacket: {
        article: "Armor Jacket",
        armorRating: 12,
        capacity: 12,
        availability: 2,
        cost: "1,000¥",
        source: "Core",
      },
      armorVest: {
        article: "Armor Vest",
        armorRating: 9,
        capacity: 9,
        availability: 4,
        cost: "500¥",
        source: "Core",
      },
      chameleonSuit: {
        article: "Chameleon Suit",
        armorRating: 9,
        capacity: 9,
        availability: "10R",
        cost: "1,700¥",
        source: "Core",
      },
      fullBodyArmor: {
        article: "Full Body Armor",
        armorRating: 15,
        capacity: 15,
        availability: "14R",
        cost: "2,000¥",
        source: "Core",
      },
      fullBodyArmorHelmet: {
        article: "Full Body Armor, Helmet",
        armorRating: "+3",
        capacity: "+3",
        availability: "-",
        cost: "+500¥",
        source: "Core",
      },
      fullBodyArmorChemicalSeal: {
        article: "Full Body Armor, Chemical Seal",
        armorRating: "-",
        capacity: "-",
        availability: "+6",
        cost: "+6,000¥",
        source: "Core",
      },
      fullBodyArmorEnvironmentalAdaptation: {
        article: "Full Body Armor, Environmental Adaptation",
        armorRating: "-",
        capacity: "-",
        availability: "+3",
        cost: "+1,000¥",
        source: "Core",
      },
      linedCoat: {
        article: "Lined Coat",
        armorRating: 9,
        capacity: 9,
        availability: 4,
        cost: "900¥",
        source: "Core",
      },
      urbanExplorerJumpsuit: {
        article: "Urban Explorer Jumpsuit",
        armorRating: 9,
        capacity: 9,
        availability: 8,
        cost: "650¥",
        source: "Core",
      },
      urbanExplorerJumpsuitHelmet: {
        article: "Urban Explorer Jumpsuit, Helmet",
        armorRating: "+2",
        capacity: "+2",
        availability: "-",
        cost: "+100¥",
        source: "Core",
      },
      helmet: {
        article: "Helmet",
        armorRating: "+2",
        capacity: "+2",
        availability: 2,
        cost: "100¥",
        source: "Core",
      },
      ballisticShield: {
        article: "Ballistic Shield",
        armorRating: "+6",
        capacity: "+6",
        availability: "12R",
        cost: "1,200¥",
        source: "Core",
      },
      riotShield: {
        article: "Riot Shield",
        armorRating: "+6",
        capacity: "+6",
        availability: "10R",
        cost: "1,000¥",
        source: "Core",
      },
      formFittingBodyArmor: {
        article: "Form-Fitting Body Armor",
        armorRating: 8,
        capacity: 3,
        availability: 8,
        cost: "1,300¥",
        source: "SR5:R&G",
      },
      hardenedMilSpecBattleArmorLight: {
        article: "Hardened Mil-Spec Battle Armor, Light",
        armorRating: 15,
        capacity: 15,
        availability: "16F",
        cost: "15,000¥",
        source: "SR5:R&G",
      },
      hardenedMilSpecBattleArmorMedium: {
        article: "Hardened Mil-Spec Battle Armor, Medium",
        armorRating: 18,
        capacity: 18,
        availability: "18F",
        cost: "20,000¥",
        source: "SR5:R&G",
      },
      hardenedMilSpecBattleArmorHeavy: {
        article: "Hardened Mil-Spec Battle Armor, Heavy",
        armorRating: 20,
        capacity: 20,
        availability: "22F",
        cost: "25,000¥",
        source: "SR5:R&G",
      },
      hardenedMilSpecBattleArmorHelmet: {
        article: "Hardened Mil-Spec Battle Armor, Helmet",
        armorRating: "+3",
        capacity: 8,
        availability: "8F",
        cost: "10,000¥",
        source: "SR5:R&G",
      },
      securityArmorLight: {
        article: "Security Armor, Light",
        armorRating: 15,
        capacity: 12,
        availability: "14R",
        cost: "8,000¥",
        source: "SR5:R&G",
      },
      securityArmorMedium: {
        article: "Security Armor, Medium",
        armorRating: 18,
        capacity: 14,
        availability: "16R",
        cost: "14,000¥",
        source: "SR5:R&G",
      },
      securityArmorHeavy: {
        article: "Security Armor, Heavy",
        armorRating: 20,
        capacity: 16,
        availability: "18R",
        cost: "20,000¥",
        source: "SR5:R&G",
      },
      securityArmorHelmet: {
        article: "Security Armor, Helmet",
        armorRating: "+3",
        capacity: 5,
        availability: "8R",
        cost: "5,000¥",
        source: "SR5:R&G",
      },
      bikeRacingArmor: {
        article: "Bike Racing Armor",
        armorRating: 8,
        capacity: 8,
        availability: 6,
        cost: "500¥",
        source: "SR5:R&G",
      },
      bikeRacingHelmet: {
        article: "Bike Racing Helmet",
        armorRating: "+2",
        capacity: 6,
        availability: 6,
        cost: "200¥",
        source: "SR5:R&G",
      },
      bunkerGear: {
        article: "Bunker Gear",
        armorRating: 6,
        capacity: 6,
        availability: 6,
        cost: "3,000¥",
        source: "SR5:R&G",
      },
      bunkerGearHelmet: {
        article: "Bunker Gear Helmet",
        armorRating: "+2",
        capacity: 3,
        availability: 6,
        cost: "750¥",
        source: "SR5:R&G",
      },
      riotControlArmor: {
        article: "Riot Control Armor",
        armorRating: 14,
        capacity: 8,
        availability: "10R",
        cost: "5,000¥",
        source: "SR5:R&G",
      },
      riotControlHelmet: {
        article: "Riot Control Helmet",
        armorRating: "+2",
        capacity: 6,
        availability: "6R",
        cost: "1,000¥",
        source: "SR5:R&G",
      },
      swatArmor: {
        article: "Swat Armor",
        armorRating: 15,
        capacity: 15,
        availability: "16R",
        cost: "8,000¥",
        source: "SR5:R&G",
      },
      swatHelmet: {
        article: "Swat Helmet",
        armorRating: "+3",
        capacity: 8,
        availability: "10R",
        cost: "1,500¥",
        source: "SR5:R&G",
      },
      securetechPPPArmsKit: {
        article: "Securetech PPP Arms Kit",
        armorRating: "+1",
        capacity: 1,
        availability: 6,
        cost: "250¥",
        source: "SR5:R&G",
      },
      securetechPPPLegsKit: {
        article: "Securetech PPP Legs Kit",
        armorRating: "+1",
        capacity: 1,
        availability: 6,
        cost: "300¥",
        source: "SR5:R&G",
      },
      securetechPPPVitalsKit: {
        article: "Securetech PPP Vitals Kit",
        armorRating: "+1",
        capacity: 1,
        availability: 6,
        cost: "350¥",
        source: "SR5:R&G",
      },
      bodyArmorBag: {
        article: "Body Armor Bag",
        armorRating: 8,
        capacity: 4,
        availability: 8,
        cost: "750¥",
        source: "SR5:R&G",
      },
      chainMail: {
        article: "Chain Mail",
        armorRating: 8,
        capacity: 2,
        availability: 8,
        cost: "900¥",
        source: "SR5:R&G",
      },
      paddedLeather: {
        article: "Padded Leather",
        armorRating: 7,
        capacity: 2,
        availability: 8,
        cost: "600¥",
        source: "SR5:R&G",
      },
      aresFlaShield: {
        article: "Ares FlaShield",
        armorRating: "+6",
        capacity: 4,
        availability: "12R",
        cost: "4,000¥",
        source: "SR5:R&G",
      },
      murderArmor: {
        article: "Murder Armor",
        armorRating: 13,
        capacity: 4,
        availability: "12R",
        cost: "5,000¥",
        source: "SR5:R&G",
      },
      gorepak: {
        article: "Gorepak",
        armorRating: "-",
        capacity: "-",
        availability: "8R",
        cost: "200¥",
        source: "SR5:R&G",
      },
      forearmGuards: {
        article: "Forearm Guards",
        armorRating: "+1",
        capacity: 3,
        availability: 6,
        cost: "300¥",
        source: "SR5:R&G",
      },
      ballisticMask: {
        article: "Ballistic Mask",
        armorRating: "+2",
        capacity: 8,
        availability: 6,
        cost: "150¥",
        source: "SR5:R&G",
      },
      cloak: {
        article: "Cloak",
        armorRating: "-",
        capacity: "(Rating)",
        availability: 1,
        cost: "(Rating) x 100¥",
        source: "SR5:HT",
      },
      rutheniumPolymerCloak: {
        article: "Ruthenium Polymer Cloak",
        armorRating: "-",
        capacity: "-",
        availability: "14F",
        cost: "(Rating) x 4,000¥",
        source: "SR5:HT",
      },
    },
    environmentalArmor: {
      ghillieSuit: {
        article: "Ghillie Suit",
        environment: "Universal",
        armorRating: 4,
        capacity: 4,
        availability: 6,
        cost: "600¥",
        source: "SR5:R&G",
      },
      aresArmoredSurvivalist: {
        article: "Ares Armored Survivalist",
        environment: "Universal",
        armorRating: 8,
        capacity: 6,
        availability: 10,
        cost: "1,500¥",
        source: "SR5:R&G",
      },
      desertSuit: {
        article: "Desert Suit",
        environment: "Heat",
        armorRating: 3,
        capacity: 2,
        availability: 8,
        cost: "1,000¥",
        source: "SR5:R&G",
      },
      snakeMeshSocks: {
        article: "Snake Mesh Socks",
        environment: "Heat",
        armorRating: "+2",
        capacity: "-",
        availability: 6,
        cost: "50¥",
        source: "SR5:R&G",
      },
      coldsuit: {
        article: "Coldsuit",
        environment: "Cold",
        armorRating: "—",
        capacity: 4,
        availability: 4,
        cost: "800¥",
        source: "SR5:R&G",
      },
      polarSurvivalSuit: {
        article: "Polar Survival Suit",
        environment: "Cold",
        armorRating: 6,
        capacity: 6,
        availability: 8,
        cost: "2,000¥",
        source: "SR5:R&G",
      },
      aresArcticForcesSuit: {
        article: "Ares Arctic Forces Suit",
        environment: "Cold",
        armorRating: 15,
        capacity: 14,
        availability: "16R",
        cost: "11,000¥",
        source: "SR5:R&G",
      },
      aresArmoredColdsuit: {
        article: "Ares Armored Coldsuit",
        environment: "Cold",
        armorRating: 9,
        capacity: 6,
        availability: 6,
        cost: "1,200¥",
        source: "SR5:R&G",
      },
      aresPolarSneakSuit: {
        article: "Ares Polar Sneak Suit",
        environment: "Cold",
        armorRating: 6,
        capacity: 4,
        availability: "16F",
        cost: "10,000¥",
        source: "SR5:R&G",
      },
      enclosedBreathingHelmet: {
        article: "Enclosed Breathing Helmet",
        environment: "Aquatic",
        armorRating: "—",
        capacity: 6,
        availability: 8,
        cost: "900¥",
        source: "SR5:R&G",
      },
      fullFaceMask: {
        article: "Full Face Mask",
        environment: "Aquatic",
        armorRating: "—",
        capacity: 4,
        availability: 8,
        cost: "300¥",
        source: "SR5:R&G",
      },
      drysuit: {
        article: "Drysuit",
        environment: "Aquatic",
        armorRating: "—",
        capacity: 4,
        availability: 6,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
      divingArmor: {
        article: "Diving Armor",
        environment: "Aquatic",
        armorRating: 7,
        capacity: 4,
        availability: 6,
        cost: "1,750¥",
        source: "SR5:R&G",
      },
      arcticDivingSuit: {
        article: "Arctic Diving Suit",
        environment: "Aquatic",
        armorRating: 1,
        capacity: 4,
        availability: 8,
        cost: "3,000¥",
        source: "SR5:R&G",
      },
      evoHelSuit: {
        article: "Evo HEL Suit",
        environment: "Space",
        armorRating: 8,
        capacity: 5,
        availability: 10,
        cost: "3,000¥",
        source: "SR5:R&G",
      },
      spacesuit: {
        article: "Spacesuit",
        environment: "Space",
        armorRating: 12,
        capacity: 6,
        availability: 16,
        cost: "12,000¥",
        source: "SR5:R&G",
      },
      securitySpacesuit: {
        article: "Security Spacesuit",
        environment: "Space",
        armorRating: 15,
        capacity: 10,
        availability: 24,
        cost: "25,000¥",
        source: "SR5:R&G",
      },
      evoArmadilloArmoredSpacesuit: {
        article: "Evo Armadillo Armored Spacesuit",
        environment: "Space",
        armorRating: 16,
        capacity: 10,
        availability: "24R",
        cost: "35,000¥",
        source: "SR5:R&G",
      },
      magneticBoots: {
        article: "Magnetic Boots",
        environment: "Space",
        armorRating: "—",
        capacity: 4,
        availability: 12,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
      survivalBubble: {
        article: "Survival Bubble",
        environment: "Space",
        armorRating: 4,
        capacity: 4,
        availability: "Rating x 3",
        cost: "2,000¥",
        source: "SR5:R&G",
      },
      mctEESuit: {
        article: "MCT EE Suit",
        environment: "Space",
        armorRating: 6,
        capacity: 5,
        availability: 10,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
    },
    armorModifications: {
      chemicalProtection: {
        modification: "Chemical Protection",
        capacity: "[Rating]",
        availability: 6,
        cost: "250¥ * Rating",
        source: "Core",
      },
      chemicalSeal: {
        modification: "Chemical Seal",
        capacity: "[6]",
        availability: "12R",
        cost: "3,000¥",
        source: "Core",
      },
      fireResistance: {
        modification: "Fire Resistance",
        capacity: "[Rating]",
        availability: 6,
        cost: "250¥ * Rating",
        source: "Core",
      },
      insulation: {
        modification: "Insulation",
        capacity: "[Rating]",
        availability: 6,
        cost: "250¥ * Rating",
        source: "Core",
      },
      nonconductivity: {
        modification: "Nonconductivity",
        capacity: "[Rating]",
        availability: 6,
        cost: "250¥ * Rating",
        source: "Core",
      },
      shockFrills: {
        modification: "Shock Frills",
        capacity: "[2]",
        availability: "6R",
        cost: "250¥",
        source: "Core",
      },
      thermalDamping: {
        modification: "Thermal Damping",
        capacity: "[Rating]",
        availability: "10R",
        cost: "500¥ * Rating",
        source: "Core",
      },
      autoInjector: {
        modification: "Auto-Injector",
        capacity: "[2]",
        availability: 4,
        cost: "1,500¥ + chemical costs",
        source: "SR5:R&G",
      },
      fresnelFabric: {
        modification: "Fresnel Fabric",
        capacity: "[2]",
        availability: "14R",
        cost: "Rating x 1,000¥",
        source: "SR5:R&G",
      },
      pulseWeave: {
        modification: "Pulse Weave",
        capacity: "[3]",
        availability: "+8R",
        cost: "Rating x 3,000¥",
        source: "SR5:R&G",
      },
      shockWeave: {
        modification: "Shock Weave",
        capacity: "[3]",
        availability: 8,
        cost: "1,000¥",
        source: "SR5:R&G",
      },
      universalMirrorMaterial: {
        modification: "Universal Mirror Material (per square meter)",
        capacity: "[3]",
        availability: "8F",
        cost: "Rating x 250¥",
        source: "SR5:R&G",
      },
      yntSoftweaveArmor: {
        modification: "YNT Softweave Armor",
        capacity: "—",
        availability: "+4",
        cost: "x2¥",
        source: "SR5:R&G",
      },
      rutheniumPolymerCoating: {
        modification: "Ruthenium Polymer Coating (Rating 1-4)",
        capacity: "[4]",
        availability: "16F",
        cost: "Rating x 5,000¥",
        source: "SR5:R&G",
      },
      radiationShielding: {
        modification: "Radiation Shielding",
        capacity: "[Rating]",
        availability: "Rating x 2",
        cost: "Rating x 200¥",
        source: "SR5:R&G",
      },
      gelPacks: {
        modification: "Gel Packs",
        capacity: "—",
        availability: 6,
        cost: "1,500¥",
        source: "SR5:R&G",
      },
      responseInterfaceGear: {
        modification: "Response Interface Gear (RIG)",
        capacity: "[4] + [2]",
        availability: 8,
        cost: "2,500¥",
        source: "SR5:R&G",
      },
      biofiberPocket: {
        modification: "Biofiber Pocket",
        capacity: "[2]",
        availability: "10F",
        cost: "700¥",
        source: "SR5:HT",
      },
      concealedPockets: {
        modification: "Concealed Pockets",
        capacity: "[1]",
        availability: 4,
        cost: "40¥",
        source: "SR5:HT",
      },
      faradayPocket: {
        modification: "Faraday Pocket",
        capacity: "[1]",
        availability: "7R",
        cost: "50¥",
        source: "SR5:HT",
      },
      gearAccess: {
        modification: "Gear Access",
        capacity: "[4]",
        availability: 4,
        cost: "150¥",
        source: "SR5:HT",
      },
    },
  };
  return armors;
}
