export default function returnAmmo() {
  const ammo = {
    ammunition: {
      APDS: {
        DV: "–",
        AP: "-4",
        Modifiers: "–",
        Avail: "12F",
        Cost: "120¥",
        Source: "Core",
      },
      AssaultCannon: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "12F",
        Cost: "400¥",
        Source: "Core",
      },
      AVRounds: {
        DV: "–",
        AP: "-1 / -5",
        Modifiers: "–",
        Avail: "14R",
        Cost: "175¥",
        Source: "SR5:R&G",
      },
      CapsuleRounds: {
        DV: "–",
        AP: "+4",
        Modifiers: "-4",
        Avail: "2",
        Cost: "5¥",
        Source: "SR5:R&G",
      },
      ExplosiveRounds: {
        DV: "–",
        AP: "-1",
        Modifiers: "+1",
        Avail: "9F",
        Cost: "80¥",
        Source: "Core",
      },
      EXExplosiveRounds: {
        DV: "–",
        AP: "-1",
        Modifiers: "+2",
        Avail: "14F",
        Cost: "120¥",
        Source: "SR5:R&G",
      },
      FlareRounds: {
        DV: "–",
        AP: "+2 / -3",
        Modifiers: "-1 / +2",
        Avail: "6R",
        Cost: "20¥",
        Source: "SR5:R&G",
      },
      FlechetteRounds: {
        DV: "–",
        AP: "+5",
        Modifiers: "+2",
        Avail: "6R",
        Cost: "65¥",
        Source: "Core",
      },
      FrangibleRounds: {
        DV: "–",
        AP: "+4",
        Modifiers: "-1",
        Avail: "2R",
        Cost: "10¥",
        Source: "SR5:R&G",
      },
      FuelCanister: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "16F",
        Cost: "40¥",
        Source: "SR5:R&G",
      },
      Gauss: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "18F",
        Cost: "400¥",
        Source: "SR5:R&G",
      },
      GelRounds: {
        DV: "+0S",
        AP: "+1",
        Modifiers: "–",
        Avail: "2R",
        Cost: "25¥",
        Source: "Core",
      },
      GyrojetAmmo: {
        DV: "-2S(e)",
        AP: "-5",
        Modifiers: "–",
        Avail: "14R",
        Cost: "160¥",
        Source: "SR5:R&G",
      },
      HollowPoints: {
        DV: "+1",
        AP: "+2",
        Modifiers: "–",
        Avail: "4F",
        Cost: "70¥",
        Source: "Core",
      },
      InjectionDarts: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "4R",
        Cost: "75¥",
        Source: "Core",
      },
      NetGun: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "9",
        Cost: "350¥",
        Source: "SR5:R&G",
      },
      NetGunXL: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "9",
        Cost: "400¥",
        Source: "SR5:R&G",
      },
      RegularAmmo: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "2R",
        Cost: "20¥",
        Source: "Core",
      },
      Shocknet: {
        DV: "8S(e)",
        AP: "-5",
        Modifiers: "–",
        Avail: "10R",
        Cost: "+250¥",
        Source: "SR5:R&G",
      },
      SticknShock: {
        DV: "-2S(e)",
        AP: "-5",
        Modifiers: "–",
        Avail: "6R",
        Cost: "80¥",
        Source: "Core",
      },
      TaserDart: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "3",
        Cost: "50¥",
        Source: "Core",
      },
      Tracer1: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "6R",
        Cost: "60¥",
        Source: "Core",
      },
      Tracer2: {
        DV: "–",
        AP: "-2",
        Modifiers: "-2",
        Avail: "8R",
        Cost: "150¥",
        Source: "SR5:R&G",
      },
    },
    ballisticProjectileConsumables: {
      Arrow: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "Rating",
        Cost: "Rating×2¥",
        Source: "Core",
      },
      BarbedHead: {
        DV: "–",
        AP: "–",
        Modifiers: "+1",
        Avail: "5R",
        Cost: "10¥",
        Source: "SR5:R&G",
      },
      Bolt: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "2",
        Cost: "5¥",
        Source: "Core",
      },
      ExplosiveHead: {
        DV: "–",
        AP: "-1",
        Modifiers: "+2",
        Avail: "9F",
        Cost: "15¥",
        Source: "SR5:R&G",
      },
      Hammerhead: {
        DV: "–",
        AP: "-1",
        Modifiers: "+1S",
        Avail: "5",
        Cost: "5¥",
        Source: "SR5:R&G",
      },
      IncendiaryHead: {
        DV: "8P",
        AP: "-6",
        Modifiers: "-1",
        Avail: "12F",
        Cost: "100¥",
        Source: "SR5:R&G",
      },
      InjectionArrow: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "(Rating+2)R",
        Cost: "Rating×20¥",
        Source: "Core",
      },
      InjectionBolt: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "8R",
        Cost: "50¥",
        Source: "Core",
      },
      MonoTip: {
        DV: "–",
        AP: "-2",
        Modifiers: "–",
        Avail: "8R",
        Cost: "Rating×30¥",
        Source: "SR5:HT",
      },
      ScreamerHead: {
        DV: "–",
        AP: "-2",
        Modifiers: "+2S",
        Avail: "2",
        Cost: "5¥",
        Source: "SR5:R&G",
      },
      SeekerShafts: {
        DV: "–",
        AP: "–",
        Modifiers: "–",
        Avail: "12F",
        Cost: "45¥",
        Source: "SR5:HT",
      },
      StaticShaft: {
        DV: "–",
        AP: "–",
        Modifiers: "+4S(e)",
        Avail: "6R",
        Cost: "Rating×25¥",
        Source: "SR5:R&G",
      },
      StickNShock: {
        DV: "8S(e)",
        AP: "-5",
        Modifiers: "-1",
        Avail: "6R",
        Cost: "25¥",
        Source: "SR5:R&G",
      },
    },
    grenades: {
      FlashBang: {
        DV: "10S",
        AP: "-4",
        Blast: "10 m radius",
        Avail: "6R",
        Cost: "100¥",
        Source: "Core",
      },
      FlashPak: {
        DV: "Spec.",
        AP: "–",
        Blast: "Spec.",
        Avail: "4",
        Cost: "125¥",
        Source: "Core",
      },
      Fragmentation: {
        DV: "18P(f)",
        AP: "+5",
        Blast: "-1/m",
        Avail: "11F",
        Cost: "100¥",
        Source: "Core",
      },
      Gas: {
        DV: "Chemical",
        AP: "10 m radius",
        Blast: "Chemical+2",
        Avail: "Chemical+40¥",
        Cost: "Core",
      },
      HighExplosive: {
        DV: "16P",
        AP: "-2",
        Blast: "-2/m",
        Avail: "11F",
        Cost: "100¥",
        Source: "Core",
      },
      PaintGrenade: {
        DV: "–",
        AP: "–",
        Blast: "-2/m",
        Avail: "8R",
        Cost: "100¥",
        Source: "SR5:R&G",
      },
      Smoke: {
        DV: "–",
        AP: "–",
        Blast: "10 m radius",
        Avail: "4R",
        Cost: "40¥",
        Source: "Core",
      },
      ThermalSmoke: {
        DV: "–",
        AP: "–",
        Blast: "10 m radius",
        Avail: "6R",
        Cost: "40¥",
        Source: "Core",
      },
    },
    rocketsMissiles: {
      AntiVehicleRocket: {
        DV: "24P",
        AP: "-4 / -10",
        Blast: "-4/m",
        Avail: "18F",
        Cost: "2,800¥",
        Source: "Core",
      },
      FragmentationRocket: {
        DV: "23P(f)",
        AP: "+5",
        Blast: "-1/m",
        Avail: "12F",
        Cost: "2,000¥",
        Source: "Core",
      },
      HighExplosiveRocket: {
        DV: "21P",
        AP: "-2",
        Blast: "-2/m",
        Avail: "18F",
        Cost: "2,100¥",
        Source: "Core",
      },
      Missile: {
        DV: "Rocket",
        AP: "+4",
        Blast: "+Sensor rating",
        Avail: "×500¥",
        Cost: "Core",
      },
    },
  };
  return ammo;
}
