export default function returnTraditions() {
  const traditions = {
    traditions: {
      theHermeticMage: {
        name: "The Hermetic Mage",
        combat: "Fire",
        detection: "Air",
        health: "Man",
        illusion: "Water",
        manipulation: "Earth",
        drain: "Logic + Willpower",
        source: "Core",
      },
      theShaman: {
        name: "The Shaman",
        combat: "Beasts",
        detection: "Water",
        health: "Earth",
        illusion: "Air",
        manipulation: "Man",
        drain: "Charisma + Willpower",
        source: "Core",
      },
      aztecGuardian: {
        name: "Aztec Guardian",
        combat: "Fire",
        detection: "Plant",
        health: "Water",
        illusion: "Beasts",
        manipulation: "Charisma + Willpower",
        drain: "SR5:SG",
      },
      blackMagic: {
        name: "Black Magic",
        combat: "Fire",
        detection: "Water",
        health: "Earth",
        illusion: "Air",
        manipulation: "Man",
        drain: "Charisma + Willpower",
        source: "SR5:SG",
      },
      buddhism: {
        name: "Buddhism",
        combat: "Air",
        detection: "Guidance",
        health: "Earth",
        illusion: "Fire",
        manipulation: "Water",
        drain: "Intuition + Willpower",
        source: "SR5:SG",
      },
      chaosMagic: {
        name: "Chaos Magic",
        combat: "Fire",
        detection: "Air",
        health: "Earth",
        illusion: "Man",
        manipulation: "Water",
        drain: "Intuition + Willpower",
        source: "SR5:SG",
      },
      christianTheurgy: {
        name: "Christian Theurgy",
        combat: "Fire",
        detection: "Water",
        health: "Air",
        illusion: "Earth",
        manipulation: "Guidance",
        drain: "Charisma + Willpower",
        source: "SR5:SG",
      },
      druid: {
        name: "Druid",
        combat: "Beasts",
        detection: "Water",
        health: "Plant",
        illusion: "Air",
        manipulation: "Earth",
        drain: "Intuition + Willpower",
        source: "SR5:SG",
      },
      egyptian: {
        name: "Egyptian",
        combat: "Fire",
        detection: "Earth",
        health: "Air",
        illusion: "Guidance",
        manipulation: "Water",
        drain: "Intuition + Willpower",
        source: "SR5:SSP",
      },
      hinduism: {
        name: "Hinduism",
        combat: "Beasts",
        detection: "Water",
        health: "Plant",
        illusion: "Air",
        manipulation: "Earth",
        drain: "Logic + Willpower",
        source: "SR5:SG",
      },
      islam: {
        name: "Islam",
        combat: "Guardian",
        detection: "Earth",
        health: "Plant",
        illusion: "Air",
        manipulation: "Fire",
        drain: "Logic + Willpower",
        source: "SR5:SG",
      },
      pathOfTheWheel: {
        name: "Path Of The Wheel",
        combat: "Earth",
        detection: "Guidance",
        health: "Air",
        illusion: "Water",
        manipulation: "Fire",
        drain: "Charisma + Willpower",
        source: "SR5:SG",
      },
      //Qabbalism is a possession tradition
      qabbalism: {
        name: "Qabbalism",
        combat: "Air",
        detection: "Earth",
        health: "Fire",
        illusion: "Water",
        manipulation: "Task",
        drain: "Logic + Willpower",
        source: "SR5:SG",
      },
      shinto: {
        name: "Shinto",
        combat: "Air",
        detection: "Water",
        health: "Plant",
        illusion: "Beasts",
        manipulation: "Man",
        drain: "Charisma + Willpower",
        source: "SR5:SG",
      },
      sioux: {
        name: "Sioux",
        combat: "Beasts",
        detection: "Plant",
        health: "Fire",
        illusion: "Air",
        manipulation: "Guardian",
        drain: "Intuition + Willpower",
        source: "SR5:SG",
      },
      vodou: {
        name: "Vodou",
        combat: "Guardian",
        detection: "Water",
        health: "Man",
        illusion: "Guidance",
        manipulation: "Task",
        drain: "Charisma + Willpower",
        source: "SR5:SG",
      },
      wicca: {
        name: "Wicca",
        combat: "Fire",
        detection: "Water",
        health: "Plant",
        illusion: "Air",
        manipulation: "Earth",
        drain: "Intuition(Goddess Wicca)/Logic(Gardnerian Wicca) + Willpower",
        source: "SR5:SG",
      },
      wuxing: {
        name: "Wuxing",
        combat: "Fire",
        detection: "Earth",
        health: "Plant",
        illusion: "Water",
        manipulation: "Guidance",
        drain: "Logic + Willpower",
        source: "SR5:SG",
      },
      zoroastrianism: {
        name: "Zoroastrianism",
        combat: "Man",
        detection: "Water",
        health: "Fire",
        illusion: "Air",
        manipulation: "Plant",
        drain: "Logic + Willpower",
        source: "SR5:SG",
      },
      insectSpirits: {
        name: "Insect Spirits",
        combat: "Soldier",
        detection: "Scout",
        health: "Caretaker",
        illusion: "Nymph",
        manipulation: "Worker",
        drain: "Intuition + Willpower",
        source: "SR5:SG",
      },
    },
  };

  return traditions;
}
