export default function returnCyberware() {
  const cyberware = {
    wareGrades: {
      standard: {
        grade: "Standard",
        essCostMultiplier: "*1.0",
        availMod: "-",
        costMultiplier: "*1",
      },
      alphaware: {
        grade: "Alphaware",
        essCostMultiplier: "*0.8",
        availMod: "+2",
        costMultiplier: "*1.2",
      },
      betaware: {
        grade: "Betaware",
        essCostMultiplier: "*0.7",
        availMod: "+4",
        costMultiplier: "*1.5",
      },
      deltaware: {
        grade: "Deltaware",
        essCostMultiplier: "*0.5",
        availMod: "+8",
        costMultiplier: "*2.5",
      },
      used: {
        grade: "Used",
        essCostMultiplier: "*1.25",
        availMod: "-4",
        costMultiplier: "*0.75",
      },
    },
    riggers: {
      controlRigR1: {
        device: "Control Rig R1",
        part: "Head",
        essence: 1,
        capacity: "-",
        avail: "5R",
        cost: "43,000¥",
        source: "Core",
      },
      controlRigR2: {
        device: "Control Rig R2",
        part: "Head",
        essence: 2,
        capacity: "-",
        avail: "10R",
        cost: "97,000¥",
        source: "Core",
      },
      controlRigR3: {
        device: "Control Rig R3",
        part: "Head",
        essence: 3,
        capacity: "-",
        avail: "15R",
        cost: "208,000¥",
        source: "Core",
      },
    },
    deckers: {
      cyberdeck: {
        device: "Cyberdeck",
        part: "Head",
        essence: 0.4,
        capacity: "[4]",
        avail: "5R",
        cost: "Deck Cost + 5,000¥",
        source: "Core",
      },
    },
    headDevices: {
      commlink: {
        device: "Commlink",
        part: "Head",
        essence: 0.2,
        capacity: "[2]",
        avail: "-",
        cost: "Commlink + 2,000¥",
        source: "Core",
      },
      cortexBombKink: {
        device: "Cortex Bomb (Kink)",
        part: "Head",
        essence: 0,
        capacity: "[1]",
        avail: "12F",
        cost: "10,000¥",
        source: "Core",
      },
      cortexBombMicrobomb: {
        device: "Cortex Bomb (Microbomb)",
        part: "Head",
        essence: 0,
        capacity: "[2]",
        avail: "16F",
        cost: "25,000¥",
        source: "Core",
      },
      cortexBombAreaBomb: {
        device: "Cortex Bomb (Area Bomb)",
        part: "Head",
        essence: 0,
        capacity: "[3]",
        avail: "20F",
        cost: "40,000¥",
        source: "Core",
      },

      datajack: {
        device: "Datajack",
        part: "Head",
        essence: 0.1,
        capacity: "-",
        avail: "2",
        cost: "1,000¥",
        source: "Core",
      },
      dataLockR112: {
        device: "Data Lock (R 1-12)",
        part: "Head",
        essence: 0.1,
        capacity: "-",
        avail: "Rating * 2",
        cost: "Rating * 1,000¥",
        source: "Core",
      },
      olfactoryBoosterR16: {
        device: "Olfactory Booster (R 1-6)",
        part: "Head",
        essence: 0.2,
        capacity: "-",
        avail: "Rating * 3",
        cost: "Rating * 4,000¥",
        source: "Core",
      },
      simrig: {
        device: "Simrig",
        part: "Head",
        essence: 0.2,
        capacity: "-",
        avail: "12R",
        cost: "4,000¥",
        source: "Core",
      },
      skilljackR16: {
        device: "Skilljack (R 1-6)",
        part: "Head",
        essence: 0.6,
        capacity: "-",
        avail: "Rating * 2",
        cost: "Rating * 20,000¥",
        source: "Core",
      },
      tasteBooster: {
        device: "Taste Booster",
        part: "Head",
        essence: 0.2,
        capacity: "-",
        avail: "Rating * 3",
        cost: "Rating * 3,000¥",
        source: "Core",
      },
      toothCompartment: {
        device: "Tooth Compartment",
        part: "Head",
        essence: 0,
        capacity: "-",
        avail: "8",
        cost: "800¥",
        source: "Core",
      },
      ultrasoundSensorR16: {
        device: "Ultrasound Sensor (R 1-6)",
        part: "Head",
        essence: 0.25,
        capacity: "[2]",
        avail: "10",
        cost: "Rating * 12,000¥",
        source: "Core",
      },
      voiceModulatorR16: {
        device: "Voice Modulator (R 1-6)",
        part: "Head",
        essence: 0.2,
        capacity: "-",
        avail: "Rating * 3F",
        cost: "Rating * 5,000¥",
        source: "Core",
      },
      attentionCoprocessor: {
        device: "Attention Coprocessor",
        part: "Head",
        essence: 0.2,
        capacity: "[1]",
        avail: "8",
        cost: "3,000¥",
        source: "SR5:CF",
      },
      chipjack16: {
        device: "Chipjack (1-6)",
        part: "Head",
        essence: 0.3,
        capacity: "-",
        avail: "(Rating) x 2",
        cost: "(Rating) x1,000¥",
        source: "SR5:CF",
      },
      dreamLink: {
        device: "Dream Link",
        part: "Head",
        essence: 0.1,
        capacity: "-",
        avail: "8",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      falseFace: {
        device: "False Face",
        part: "Head",
        essence: 0.5,
        capacity: "[8]",
        avail: "12R",
        cost: "20,000¥",
        source: "SR5:CF",
      },
      radarSensor14: {
        device: "Radar Sensor (1-4)",
        part: "Head",
        essence: 2,
        capacity: "[Rating]",
        avail: "Rating * 3",
        cost: "Rating * 4,000¥",
        source: "SR5:CF",
      },
      synthlink: {
        device: "Synthlink",
        part: "Head",
        essence: 0.1,
        capacity: "[1]",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      visualizer: {
        device: "Visualizer",
        part: "Head",
        essence: 0.1,
        capacity: "-",
        avail: "8",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      voiceMask: {
        device: "Voice Mask",
        part: "Head",
        essence: 0.1,
        capacity: "-",
        avail: "8F",
        cost: "2,000¥",
        source: "SR5:CF",
      },
    },
    eyeDevices: {
      cybereyesR1: {
        device: "Cybereyes R1",
        part: "Eye",
        essence: 0.2,
        capacity: "4",
        avail: "3",
        cost: "4,000¥",
        source: "Core",
      },
      cybereyesR2: {
        device: "Cybereyes R2",
        part: "Eye",
        essence: 0.3,
        capacity: "8",
        avail: "6",
        cost: "6,000¥",
        source: "Core",
      },
      cybereyesR3: {
        device: "Cybereyes R3",
        part: "Eye",
        essence: 0.4,
        capacity: "12",
        avail: "9",
        cost: "10,000¥",
        source: "Core",
      },
      cybereyesR4: {
        device: "Cybereyes R4",
        part: "Eye",
        essence: 0.5,
        capacity: "16",
        avail: "12",
        cost: "14,000¥",
        source: "Core",
      },
      flareCompensation: {
        device: "Flare Compensation",
        part: "Eye",
        essence: 0.1,
        capacity: "[1]",
        avail: "4",
        cost: "1,000¥",
        source: "Core",
      },
      imageLink: {
        device: "Image Link",
        part: "Eye",
        essence: 0.1,
        capacity: "*",
        avail: "4",
        cost: "1,000¥",
        source: "Core",
      },
      lowLightVision: {
        device: "Low-Light Vision",
        part: "Eye",
        essence: 0.1,
        capacity: "[2]",
        avail: "4",
        cost: "1,500¥",
        source: "Core",
      },
      ocularDrone: {
        device: "Ocular Drone",
        part: "Eye",
        essence: 0,
        capacity: "[6]",
        avail: "6",
        cost: "6,000¥",
        source: "Core",
      },
      retinalDuplicationR16: {
        device: "Retinal Duplication (R 1-6)",
        part: "Eye",
        essence: 0.6,
        capacity: "[1]",
        avail: "16F",
        cost: "Rating * 20,000¥",
        source: "Core",
      },
      smartlink: {
        device: "Smartlink",
        part: "Eye",
        essence: 0.2,
        capacity: "[3]",
        avail: "8R",
        cost: "4,000¥",
        source: "Core",
      },
      thermographicVision: {
        device: "Thermographic Vision",
        part: "Eye",
        essence: 0.1,
        capacity: "[2]",
        avail: "4",
        cost: "1,500¥",
        source: "Core",
      },
      visionEnhancementR13: {
        device: "Vision Enhancement (R 1-3)",
        part: "Eye",
        essence: 0.1,
        capacity: "[Rating]",
        avail: "Rating * 3",
        cost: "Rating * 4,000¥",
        source: "Core",
      },
      visionMagnification: {
        device: "Vision Magnification",
        part: "Eye",
        essence: 0.1,
        capacity: "[2]",
        avail: "4",
        cost: "2,000¥",
        source: "Core",
      },
      additionalEyeMount: {
        device: "Additional Eye Mount",
        part: "Eye",
        essence: 0.2,
        capacity: "[2]",
        avail: "8",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      eyeLightSystem: {
        device: "Eye-light System",
        part: "Eye",
        essence: 0.1,
        capacity: "[2]",
        avail: "2",
        cost: "500¥",
        source: "SR5:CF",
      },
      eyeProtectors: {
        device: "Eye Protectors",
        part: "Eye",
        essence: 0.1,
        capacity: "[2]",
        avail: "-",
        cost: "100¥",
        source: "SR5:CF",
      },
      microscopicLenses: {
        device: "Microscopic Lenses",
        part: "Eye",
        essence: 0.2,
        capacity: "[3]",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      spiderEyes: {
        addedStats: ["skills", "Perception", 1, "physical"],
        device: "Spider Eyes",
        part: "Eye",
        essence: 0.2,
        capacity: "2",
        avail: "8",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      targetingLaser: {
        device: "Targeting Laser",
        part: "Eye",
        essence: 0.2,
        capacity: "[4]",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      targetingLaserInfrared: {
        device: "Targeting Laser (Infrared)",
        part: "Eye",
        essence: 0.2,
        capacity: "[4]",
        avail: "6",
        cost: "1,250¥",
        source: "SR5:CF",
      },
    },
    earDevices: {
      cyberearsR1: {
        device: "Cyberears R1",
        part: "Ear",
        essence: 0.2,
        capacity: "4",
        avail: "3",
        cost: "3,000¥",
        source: "Core",
      },
      cyberearsR2: {
        device: "Cyberears R2",
        part: "Ear",
        essence: 0.3,
        capacity: "8",
        avail: "6",
        cost: "4,500¥",
        source: "Core",
      },
      cyberearsR3: {
        device: "Cyberears R3",
        part: "Ear",
        essence: 0.4,
        capacity: "12",
        avail: "9",
        cost: "7,500¥",
        source: "Core",
      },
      cyberearsR4: {
        device: "Cyberears R4",
        part: "Ear",
        essence: 0.5,
        capacity: "16",
        avail: "12",
        cost: "11,000¥",
        source: "Core",
      },

      balanceAugmenter: {
        device: "Balance Augmenter",
        part: "Ear",
        essence: 0.1,
        capacity: "[4]",
        avail: "8",
        cost: "8,000¥",
        source: "Core",
      },
      damper: {
        device: "Damper",
        part: "Ear",
        essence: 0.1,
        capacity: "[1]",
        avail: "6",
        cost: "2,250¥",
        source: "Core",
      },
      selectSoundFilterR16: {
        device: "Select Sound Filter (R 1-6)",
        part: "Ear",
        essence: 0.1,
        capacity: "[Rating]",
        avail: "Rating * 3",
        cost: "Rating * 3,500¥",
        source: "Core",
      },
      soundLink: {
        device: "Sound Link",
        part: "Ear",
        essence: 0.1,
        capacity: "*",
        avail: "4",
        cost: "1,000¥",
        source: "Core",
      },
      spatialRecognizer: {
        device: "Spatial Recognizer",
        part: "Ear",
        essence: 0.1,
        capacity: "[2]",
        avail: "8",
        cost: "4,000¥",
        source: "Core",
      },
      antennae: {
        device: "Antennae",
        part: "Ear",
        essence: 0.1,
        capacity: "[1]",
        avail: "2",
        cost: "500¥",
        source: "SR5:CF",
      },
      audioAnalyzer: {
        device: "Audio Analyzer",
        part: "Ear",
        essence: 0.1,
        capacity: "[1]",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      earProtectors: {
        device: "Ear Protectors",
        part: "Ear",
        essence: 0.05,
        capacity: "[1]",
        avail: "-",
        cost: "250¥",
        source: "SR5:CF",
      },
      increasedSpectrum: {
        device: "Increased Spectrum",
        part: "Ear",
        essence: 0.1,
        capacity: "[1]",
        avail: "6",
        cost: "500¥",
        source: "SR5:CF",
      },
      modularMount: {
        device: "Modular Mount",
        part: "Ear",
        essence: 0.1,
        capacity: "[1]",
        avail: "4",
        cost: "250¥",
        source: "SR5:CF",
      },
      translatEar: {
        device: "Translat-Ear",
        part: "Ear",
        essence: 0.1,
        capacity: "[Rating]",
        avail: "8",
        cost: "Rating x 2,000¥",
        source: "SR5:CF",
      },
    },
    bodyDevices: {
      boneLacingPlastic: {
        addedStats: ["stats", "body", 1],
        addedStatsTwo: ["armor", "armor", 1],
        device: "Bone Lacing (Plastic)",
        part: "Body",
        essence: 0.5,
        capacity: "-",
        avail: "8R",
        cost: "8,000¥",
        source: "Core",
      },
      boneLacingAluminum: {
        addedStats: ["stats", "body", 2],
        addedStatsTwo: ["armor", "armor", 2],
        device: "Bone Lacing (Aluminum)",
        part: "Body",
        essence: 1,
        capacity: "-",
        avail: "12R",
        cost: "18,000¥",
        source: "Core",
      },
      bondLacingTitanium: {
        addedStats: ["stats", "body", 3],
        addedStatsTwo: ["armor", "armor", 3],
        device: "Bond Lacing (Titanium)",
        part: "Body",
        essence: 1.5,
        capacity: "-",
        avail: "16R",
        cost: "30,000¥",
        source: "Core",
      },
      dermalPlatingR16: {
        addedStats: ["armor", "armor", 6],
        device: "Dermal Plating (R 1-6)",
        part: "Body",
        essence: 3,
        capacity: "-",
        avail: "(Rating * 4)R",
        cost: "Rating * 3,000¥",
        source: "Core",
      },
      fingertipCompartment: {
        device: "Fingertip Compartment",
        part: "Body",
        essence: 0.1,
        capacity: "[1]",
        avail: "4",
        cost: "3,000¥",
        source: "Core",
      },
      grappleGun: {
        device: "Grapple Gun",
        part: "Body",
        essence: 0.5,
        capacity: "[4]",
        avail: "8",
        cost: "5,000¥",
        source: "Core",
      },
      internalAirTankR13: {
        device: "Internal Air Tank (R 1-3)",
        part: "Body",
        essence: 0.25,
        capacity: "[3]",
        avail: "Rating",
        cost: "Rating * 4,500¥",
        source: "Core",
      },
      muscleReplacementR14: {
        addedStats: ["stats", "body", 4],
        addedStatsTwo: ["stats", "agility", 4],
        device: "Muscle Replacement (R 1-4)",
        part: "Body",
        essence: 4,
        capacity: "-",
        avail: "(Rating * 5)R",
        cost: "Rating * 25,000¥",
        source: "Core",
      },
      reactionEnhancersR13: {
        addedStats: ["stats", "reaction", 3],
        device: "Reaction Enhancers (R 1-3)",
        part: "Body",
        essence: 0.9,
        capacity: "-",
        avail: "(Rating * 5)R",
        cost: "Rating * 13,000¥",
        source: "Core",
      },
      skillwiresR16: {
        device: "Skillwires (R 1-6)",
        part: "Body",
        essence: 0.6,
        capacity: "-",
        avail: "Rating * 4",
        cost: "Rating * 20,000¥",
        source: "Core",
      },
      smugglingCompartment: {
        device: "Smuggling Compartment",
        part: "Body",
        essence: 0.2,
        capacity: "[2]",
        avail: "6",
        cost: "7,500¥",
        source: "Core",
      },
      wiredReflexesR1: {
        addedStats: ["stats", "reaction", 1],
        addedStatsTwo: ["initiative", "dice", 1],
        device: "Wired Reflexes R1",
        part: "Body",
        essence: 2,
        capacity: "-",
        avail: "8R",
        cost: "39,000¥",
        source: "Core",
      },
      wiredReflexesR2: {
        addedStats: ["stats", "reaction", 2],
        addedStatsTwo: ["initiative", "dice", 2],
        device: "Wired Reflexes R2",
        part: "Body",
        essence: 3,
        capacity: "-",
        avail: "12R",
        cost: "149,000¥",
        source: "Core",
      },
      wiredReflexesR3: {
        addedStats: ["stats", "reaction", 3],
        addedStatsTwo: ["initiative", "dice", 3],
        device: "Wired Reflexes R3",
        part: "Body",
        essence: 5,
        capacity: "-",
        avail: "20R",
        cost: "217,000¥",
        source: "Core",
      },
      activeHardwires: {
        device: "Active Hardwires(6)",
        part: "Body",
        essence: 0.6,
        capacity: "-",
        avail: "Rating x 2",
        cost: "Rating x 4,000¥",
        source: "SR5:CF",
      },
      autoInjector: {
        device: "Auto-injector",
        part: "Body",
        essence: 0.05,
        capacity: "-",
        avail: "2",
        cost: "(Rating) x 1,000¥",
        source: "SR5:CF",
      },
      killswitch: {
        device: "Killswitch",
        part: "Body",
        essence: 0.05,
        capacity: "-",
        avail: "8F",
        cost: "750¥+ contents",
        source: "SR5:CF",
      },

      biomonitor: {
        device: "Biomonitor",
        part: "Body",
        essence: 0.1,
        capacity: "[1]",
        avail: "2",
        cost: "500¥",
        source: "SR5:CF",
      },
      biowasteStorage: {
        device: "Biowaste Storage(3)",
        part: "Body",
        essence: 0.3,
        capacity: "[Rating]",
        avail: "8",
        cost: "Rating x 500¥",
        source: "SR5:CF",
      },
      breastImplant2_0: {
        device: "Breast Implant 2.0",
        part: "Body",
        essence: 0.1,
        capacity: "[1]",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:CF",
      },
      casemod: {
        device: "Casemod",
        part: "Body",
        essence: 0,
        capacity: "-",
        avail: "4",
        cost: "50-10,000¥",
        source: "SR5:CF",
      },
      cosmeticSurgery: {
        device: "Cosmetic Surgery",
        part: "Body",
        essence: 0.1,
        capacity: "-",
        avail: "2",
        cost: "100-20,000¥",
        source: "SR5:CF",
      },
      cyberfins: {
        device: "Cyberfins",
        part: "Body",
        essence: 0.05,
        capacity: "[1]",
        avail: "8",
        cost: "500¥",
        source: "SR5:CF",
      },
      cyberGenitalia: {
        device: "Cyber Genitalia",
        part: "Body",
        essence: 0.25,
        capacity: "[1]",
        avail: "6",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      cybersafety: {
        device: "Cybersafety",
        part: "Body",
        essence: 0,
        capacity: "[1]",
        avail: "4",
        cost: "100¥",
        source: "SR5:CF",
      },
      fiberopticHair: {
        addedStats: ["skills", "Escape Artist", 3, "physical"],
        device: "Fiberoptic Hair",
        part: "Body",
        essence: 0.1,
        capacity: "[1]",
        avail: "-",
        cost: "100¥+",
        source: "SR5:CF",
      },
      flexHand: {
        addedStats: ["skills", "Escape Artist", 3, "physical"],
        device: "Flex Hand",
        part: "Body",
        essence: 0.15,
        capacity: "-",
        avail: "8",
        cost: "1,500¥",
        source: "SR5:CF",
      },
      footAnchor: {
        device: "Foot Anchor",
        part: "Body",
        essence: 0.25,
        capacity: "[3]",
        avail: "10",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      internalRouter: {
        device: "Internal Router",
        part: "Body",
        essence: 0.7,
        capacity: "-",
        avail: "4",
        cost: "15,000¥",
        source: "SR5:CF",
      },
      ledTattooSmall: {
        device: "LED Tattoo (Small)",
        part: "Body",
        essence: 0.05,
        capacity: "[1]",
        avail: "-",
        cost: "100¥+",
        source: "SR5:CF",
      },
      ledTattooMedium: {
        device: "LED Tattoo (Medium)",
        part: "Body",
        essence: 0.1,
        capacity: "[2]",
        avail: "4",
        cost: "500¥+",
        source: "SR5:CF",
      },
      ledTattooLarge: {
        device: "LED Tattoo (Large)",
        part: "Body",
        essence: 0.2,
        capacity: "[4]",
        avail: "8",
        cost: "1,000¥+",
        source: "SR5:CF",
      },
      magneticSystem: {
        device: "Magnetic System",
        part: "Body",
        essence: 0.25,
        capacity: "[2]",
        avail: "8",
        cost: "1,000¥+contents",
        source: "SR5:CF",
      },
      metatypeReduction: {
        device: "Metatype Reduction",
        part: "Body",
        essence: 0.3,
        capacity: "-",
        avail: "4",
        cost: "6,000¥",
        source: "SR5:CF",
      },
      moveByWireR1: {
        addedStats: ["stats", "reaction", 1],
        addedStatsTwo: ["initiative", "bonus", 3],
        device: "Move-by-Wire (R1)",
        part: "Body",
        essence: 3.0,
        capacity: "-",
        avail: "12F",
        cost: "40,000¥",
        source: "SR5:CF",
      },
      moveByWireR2: {
        addedStats: ["stats", "reaction", 1],
        addedStatsTwo: ["initiative", "bonus", 6],
        addedStatsThree: ["initiative", "dice", 1],
        device: "Move-by-Wire (R2)",
        part: "Body",
        essence: 4.0,
        capacity: "-",
        avail: "18F",
        cost: "125,000¥",
        source: "SR5:CF",
      },
      moveByWireR3: {
        addedStats: ["stats", "reaction", 1],
        addedStatsTwo: ["initiative", "bonus", 9],
        addedStatsThree: ["initiative", "dice", 1],
        device: "Move-by-Wire (R3)",
        part: "Body",
        essence: 5.0,
        capacity: "-",
        avail: "24F",
        cost: "205,000¥",
        source: "SR5:CF",
      },
      nutritionStorageSystem: {
        device: "Nutrition Storage System(3)",
        part: "Body",
        essence: 0.3,
        capacity: "[Rating]",
        avail: "4",
        cost: "Rating x 500¥",
        source: "SR5:CF",
      },
      oxsysCybergill: {
        device: "Oxsys Cybergill",
        part: "Body",
        essence: 0.25,
        capacity: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      retractableClimbingClaws: {
        addedStats: ["skills", "climbing", 2, "physical"],
        device: "Retractable Climbing Claws",
        part: "Body",
        essence: 0.2,
        capacity: "[2]",
        avail: "8",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      skinToner: {
        device: "Skin Toner",
        part: "Body",
        essence: 0.5,
        capacity: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      touchLink: {
        device: "Touch Link",
        part: "Body",
        essence: 0.1,
        capacity: "-",
        avail: "8",
        cost: "1,000¥",
        source: "SR5:CF",
      },
    },
    // limbDevices: {
    //   obviousFullArm: {
    //     device: "Obvious Full Arm",
    //     part: "Limb",
    //     essence: 1,
    //     capacity: 15,
    //     avail: 4,
    //     cost: "15,000¥",
    //     source: "Core",
    //   },
    //   obviousFullLeg: {
    //     device: "Obvious Full Leg",
    //     part: "Limb",
    //     essence: 1,
    //     capacity: 20,
    //     avail: 4,
    //     cost: "15,000¥",
    //     source: "Core",
    //   },
    //   obviousHandFoot: {
    //     device: "Obvious Hand/Foot",
    //     part: "Limb",
    //     essence: 0.25,
    //     capacity: 4,
    //     avail: 2,
    //     cost: "5,000¥",
    //     source: "Core",
    //   },
    //   obviousLowerArm: {
    //     device: "Obvious Lower Arm",
    //     part: "Limb",
    //     essence: 0.45,
    //     capacity: 10,
    //     avail: 4,
    //     cost: "10,000¥",
    //     source: "Core",
    //   },
    //   obviousLowerLeg: {
    //     device: "Obvious Lower Leg",
    //     part: "Limb",
    //     essence: 0.45,
    //     capacity: 12,
    //     avail: 4,
    //     cost: "10,000¥",
    //     source: "Core",
    //   },
    //   obviousTorso: {
    //     device: "Obvious Torso",
    //     part: "Limb",
    //     essence: 1.5,
    //     capacity: 10,
    //     avail: 12,
    //     cost: "20,000¥",
    //     source: "Core",
    //   },
    //   obviousSkull: {
    //     device: "Obvious Skull",
    //     part: "Limb",
    //     essence: 0.75,
    //     capacity: 4,
    //     avail: 16,
    //     cost: "10,000¥",
    //     source: "Core",
    //   },
    //   syntheticFullArm: {
    //     device: "Synthetic Full Arm",
    //     part: "Limb",
    //     essence: 1,
    //     capacity: 8,
    //     avail: 4,
    //     cost: "20,000¥",
    //     source: "Core",
    //   },
    //   syntheticFullLeg: {
    //     device: "Synthetic Full Leg",
    //     part: "Limb",
    //     essence: 1,
    //     capacity: 10,
    //     avail: 4,
    //     cost: "20,000¥",
    //     source: "Core",
    //   },
    //   syntheticHandFoot: {
    //     device: "Synthetic Hand/Foot",
    //     part: "Limb",
    //     essence: 0.25,
    //     capacity: 2,
    //     avail: 2,
    //     cost: "6,000¥",
    //     source: "Core",
    //   },
    //   syntheticLowerArm: {
    //     device: "Synthetic Lower Arm",
    //     part: "Limb",
    //     essence: 0.45,
    //     capacity: 5,
    //     avail: 4,
    //     cost: "12,000¥",
    //     source: "Core",
    //   },
    //   syntheticLowerLeg: {
    //     device: "Synthetic Lower Leg",
    //     part: "Limb",
    //     essence: 0.45,
    //     capacity: 6,
    //     avail: 4,
    //     cost: "12,000¥",
    //     source: "Core",
    //   },
    //   syntheticTorso: {
    //     device: "Synthetic Torso",
    //     part: "Limb",
    //     essence: 1.5,
    //     capacity: 5,
    //     avail: 12,
    //     cost: "25,000¥",
    //     source: "Core",
    //   },
    //   syntheticSkull: {
    //     device: "Synthetic Skull",
    //     part: "Limb",
    //     essence: 0.75,
    //     capacity: 2,
    //     avail: 16,
    //     cost: "15,000¥",
    //     source: "Core",
    //   },

    //   primitiveHandFoot: {
    //     device: "Primitive Hand/Foot",
    //     part: "Limb",
    //     essence: 0,
    //     capacity: "-",
    //     avail: "-",
    //     cost: "20¥",
    //     source: "SR5:CF",
    //   },
    //   primitivePartialArmLeg: {
    //     device: "Primitive Partial Arm/Leg",
    //     part: "Limb",
    //     essence: 0,
    //     capacity: "-",
    //     avail: "-",
    //     cost: "100¥",
    //     source: "SR5:CF",
    //   },
    //   primitiveFullArmLeg: {
    //     device: "Primitive Full Arm/Leg",
    //     part: "Limb",
    //     essence: 0,
    //     capacity: "-",
    //     avail: "-",
    //     cost: "250¥",
    //     source: "SR5:CF",
    //   },
    // },
    // limbAccessories: {
    //   cyberarmGyromount: {
    //     device: "Cyberarm Gyromount",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[8]",
    //     avail: "12F",
    //     cost: "6,000¥",
    //     source: "Core",
    //   },
    //   cyberarmSlide: {
    //     device: "Cyberarm Slide",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[3]",
    //     avail: "12R",
    //     cost: "3,000¥",
    //     source: "Core",
    //   },
    //   cyberHolster: {
    //     device: "Cyber Holster",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[5]",
    //     avail: "8R",
    //     cost: "2,000¥",
    //     source: "Core",
    //   },

    //   largeSmugglingCompartment: {
    //     device: "Large Smuggling Compartment",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[5]",
    //     avail: "6",
    //     cost: "8,000¥",
    //     source: "Core",
    //   },
    //   builtInMedkit: {
    //     device: "Built-In Medkit",
    //     part: "Limb Accessories",
    //     essence: 0.45,
    //     capacity: "[10]",
    //     avail: "8",
    //     cost: "1,000¥(+ medkit)",
    //     source: "SR5:CF",
    //   },
    //   builtInToolkit: {
    //     device: "Built-In Toolkit",
    //     part: "Limb Accessories",
    //     essence: 0.45,
    //     capacity: "[10]",
    //     avail: "4",
    //     cost: "2,000¥",
    //     source: "SR5:CF",
    //   },
    //   bulkModification: {
    //     device: "Bulk Modification (1-6)",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "+ (Rating)",
    //     avail: "+(Rating)",
    //     cost: "(Rating) x 500¥",
    //     source: "SR5:CF",
    //   },
    //   cyberfingers: {
    //     device: "Cyberfingers",
    //     part: "Limb Accessories",
    //     essence: 0.05,
    //     capacity: "[1]",
    //     avail: "2",
    //     cost: "500¥",
    //     source: "SR5:CF",
    //   },
    //   cyberlight: {
    //     device: "Cyberlight",
    //     part: "Limb Accessories",
    //     essence: 0.05,
    //     capacity: "[1]",
    //     avail: "4",
    //     cost: "550¥",
    //     source: "SR5:CF",
    //   },
    //   cyberlighter: {
    //     device: "Cyberlighter",
    //     part: "Limb Accessories",
    //     essence: 0.05,
    //     capacity: "[1]",
    //     avail: "4",
    //     cost: "550¥",
    //     source: "SR5:CF",
    //   },
    //   fingerGrenade: {
    //     device: "Finger Grenade",
    //     part: "Limb Accessories",
    //     essence: 0.05,
    //     capacity: "[1]",
    //     avail: "(Grenade) +4",
    //     cost: "(Grenade) + 500¥",
    //     source: "SR5:CF",
    //   },
    //   fingerPistol: {
    //     device: "Finger Pistol",
    //     part: "Limb Accessories",
    //     essence: 0.05,
    //     capacity: "[1]",
    //     avail: "8R",
    //     cost: "1,000¥",
    //     source: "SR5:CF",
    //   },

    //   digigradeLegs: {
    //     addedStats: ["skills", "sneaking", 2, "physical"],
    //     device: "Digigrade Legs",
    //     part: "Limb Accessories",
    //     essence: 0.5,
    //     capacity: "[4]",
    //     avail: "(Leg) +4",
    //     cost: "(Leg) + 5,000¥",
    //     source: "SR5:CF",
    //   },
    //   grappleHand: {
    //     device: "Grapple Hand",
    //     part: "Limb Accessories",
    //     essence: 0.45,
    //     capacity: "[10]",
    //     avail: "12R",
    //     cost: "2,000¥",
    //     source: "SR5:CF",
    //   },
    //   improvedSynthskin: {
    //     device: "Improved Synthskin (1-4)",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[(Rating) X 2]",
    //     avail: "(Rating) X 4",
    //     cost: "(Rating) x 5,000¥",
    //     source: "SR5:CF",
    //   },
    //   liminalBodyCentaur: {
    //     device: "Liminal Body (Centaur)",
    //     part: "Limb Accessories",
    //     essence: 3.0,
    //     capacity: "80",
    //     avail: "12",
    //     cost: "80,000¥",
    //     source: "SR5:CF",
    //   },
    //   partialCyberskull: {
    //     device: "Partial Cyberskull",
    //     part: "Limb Accessories",
    //     essence: 0.4,
    //     capacity: "4",
    //     avail: "12",
    //     cost: "8,000¥",
    //     source: "SR5:CF",
    //   },
    //   raptorFoot: {
    //     device: "Raptor Foot",
    //     part: "Limb Accessories",
    //     essence: 0.5,
    //     capacity: "[4]",
    //     avail: "8R",
    //     cost: "8,000¥",
    //     source: "SR5:CF",
    //   },
    //   snakeFingers: {
    //     addedStats: ["skills", "Palming", 1, "physical"],
    //     device: "Snake Fingers",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[2]",
    //     avail: "6",
    //     cost: "1,000¥",
    //     source: "SR5:CF",
    //   },
    //   telescopicLimbs: {
    //     device: "Telescopic Limbs (1-2)",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[Rating] x 3",
    //     avail: "(Rating) x 4",
    //     cost: "(Rating) x 1,000¥",
    //     source: "SR5:CF",
    //   },
    //   waterJet: {
    //     device: "Water Jet",
    //     part: "Limb Accessories",
    //     essence: 0,
    //     capacity: "[4]",
    //     avail: "8",
    //     cost: "1,000¥",
    //     source: "SR5:CF",
    //   },
    //   remoteCyberhand: {
    //     device: "Remote Cyberhand",
    //     part: "Limb Accessories",
    //     essence: 0.25,
    //     capacity: "[5]",
    //     avail: "8",
    //     cost: "8,000¥",
    //     source: "SR5:R5.0",
    //   },
    // },
    weapons: {
      holdOutPistol: {
        device: "Hold-Out Pistol",
        part: "Weapon",
        essence: 0.1,
        capacity: "[2]",
        avail: "8R",
        cost: "2,000¥",
        source: "Core",
      },
      lightPistol: {
        device: "Light Pistol",
        part: "Weapon",
        essence: 0.25,
        capacity: "[4]",
        avail: "10R",
        cost: "3,900¥",
        source: "Core",
      },
      machinePistol: {
        device: "Machine Pistol",
        part: "Weapon",
        essence: 0.5,
        capacity: "[6]",
        avail: "12R",
        cost: "3,500¥",
        source: "Core",
      },
      heavyPistol: {
        device: "Heavy Pistol",
        part: "Weapon",
        essence: 0.5,
        capacity: "[6]",
        avail: "12R",
        cost: "4,300¥",
        source: "Core",
      },
      submachineGun: {
        device: "Submachine Gun",
        part: "Weapon",
        essence: 1,
        capacity: "[8]",
        avail: "12R",
        cost: "4,800¥",
        source: "Core",
      },
      shotgun: {
        device: "Shotgun",
        part: "Weapon",
        essence: 1.25,
        capacity: "[10]",
        avail: "12R",
        cost: "8,500¥",
        source: "Core",
      },
      grenadeLauncher: {
        device: "Grenade Launcher",
        part: "Weapon",
        essence: 1.5,
        capacity: "[15]",
        avail: "20F",
        cost: "30,000¥",
        source: "Core",
      },
      externalClipPort: {
        device: "External Clip Port",
        part: "Weapon",
        essence: 0.1,
        capacity: "[1]",
        avail: "-",
        cost: "+1,000¥",
        source: "Core",
      },
      laserSight: {
        device: "Laser Sight",
        part: "Weapon",
        essence: 0,
        capacity: "[1]",
        avail: "-",
        cost: "+1,000¥",
        source: "Core",
      },

      extremeCyberImplant: {
        device: "Extreme Cyber-Implant",
        part: "Weapon",
        essence: 0.5,
        capacity: "[5]",
        avail: "8F",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      fangsPair: {
        device: "Fangs (Pair)",
        part: "Weapon",
        essence: 0.1,
        capacity: "[1]",
        avail: "6",
        cost: "200¥",
        source: "SR5:CF",
      },

      flametosser: {
        device: "Flametosser",
        part: "Weapon",
        essence: 1.0,
        capacity: "[8]",
        avail: "12F",
        cost: "4,000¥",
        source: "SR5:CF",
      },

      junkyardJaw: {
        device: "Junkyard Jaw",
        part: "Weapon",
        essence: 0.75,
        capacity: "[6]",
        avail: "8F",
        cost: "2,000¥",
        source: "SR5:CF",
      },
      oralSlasher: {
        device: "Oral Slasher",
        part: "Weapon",
        essence: 0.25,
        capacity: "[3]",
        avail: "12R",
        cost: "750¥",
        source: "SR5:CF",
      },
      weaponLauncher: {
        device: "Weapon Launcher",
        part: "Weapon",
        essence: 0.2,
        capacity: "[2]",
        avail: "12F",
        cost: "500¥(added to weapon cost)",
        source: "SR5:CF",
      },
      handBladeRetractable: {
        device: "Hand Blade (Retractable)",
        part: "Weapon",
        essence: 0.25,
        capacity: "[2]",
        avail: "10F",
        cost: "2,500¥",
        source: "Core",
      },
      handRazorsRetractable: {
        device: "Hand Razors (Retractable)",
        part: "Weapon",
        essence: 0.2,
        capacity: "[2]",
        avail: "8F",
        cost: "1,250¥",
        source: "Core",
      },
      shockHand: {
        device: "Shock Hand",
        part: "Weapon",
        essence: 0.25,
        capacity: "[4]",
        avail: "8R",
        cost: "5,000¥",
        source: "Core",
      },
    },
    nanoware: {
      antiTox: {
        device: "Anti-Tox",
        rating: "1-9",
        availability: "16F",
        cost: "Rating x 5,000¥",
        source: "SR5:CF",
      },
      carcerandPlus: {
        device: "Carcerand Plus",
        rating: "1-6",
        availability: "10F",
        cost: "Rating x 3,000¥(+ drug)",
        source: "SR5:CF",
      },
      nanosymbiotes: {
        device: "Nanosymbiotes",
        rating: "1-3",
        availability: "16F",
        cost: "Rating x 6,000¥",
        source: "SR5:CF",
      },
      nantidotes: {
        device: "Nantidotes",
        rating: "1-6",
        availability: "8F",
        cost: "Rating x 1,500¥",
        source: "SR5:CF",
      },
      nanotattoos: {
        device: "Nanotattoos",
        rating: "1-3",
        availability: "12F",
        cost: "Rating x 500¥",
        source: "SR5:CF",
      },
      learningStimulus: {
        device: "Learning Stimulus",
        rating: "1-3",
        availability: "14F",
        cost: "Rating x 5,000¥",
        source: "SR5:CF",
      },
      limbic: {
        device: "Limbic",
        rating: "1-3",
        availability: "16F",
        cost: "Rating x 7,500¥",
        source: "SR5:CF",
      },
      neocortical: {
        device: "Neocortical",
        rating: "1-3",
        availability: "16F",
        cost: "Rating x 7,500¥",
        source: "SR5:CF",
      },
      recall: {
        device: "Recall",
        rating: "1-3",
        availability: "12F",
        cost: "Rating x 3,500¥",
        source: "SR5:CF",
      },
      oCells: {
        device: "O-Cells",
        rating: "1-9",
        availability: "12F",
        cost: "Rating x 5,000¥",
        source: "SR5:CF",
      },
      oxyrush: {
        device: "Oxyrush",
        rating: "1-5",
        availability: "12F",
        cost: "Rating x 1,500¥",
        source: "SR5:CF",
      },
      antiRad: {
        device: "Anti-Rad",
        rating: "1–6",
        availability: "14F",
        cost: "Rating x 6,000¥",
        source: "SR5:CF",
      },
      controlRigBooster: {
        device: "Control Rig Booster",
        rating: "1–3",
        availability: "12F",
        cost: "Rating x 6,000¥",
        source: "SR5:CF",
      },
      implantMedic: {
        device: "Implant Medic",
        rating: "1–6",
        availability: "12F",
        cost: "10% of implant cost¥",
        source: "SR5:CF",
      },
      naniteHunters: {
        device: "Nanite Hunters",
        rating: "1–6",
        availability: "16R",
        cost: "Rating x 5,000¥",
        source: "SR5:CF",
      },
      markers: {
        device: "Markers",
        rating: "1–3",
        availability: "12",
        cost: "Rating x 2,000¥",
        source: "SR5:CF",
      },
      nanotattoos2: {
        device: "Nanotattoos",
        rating: "1–3",
        availability: "12F",
        cost: "Rating x 1,000¥",
        source: "SR5:CF",
      },
      taggants: {
        device: "Taggants",
        rating: "1–3",
        availability: "12",
        cost: "Rating x 600¥",
        source: "SR5:CF",
      },
      traumaControlSystem: {
        device: "Trauma Control System",
        rating: "1–6",
        availability: "12F",
        cost: "Rating x 4,000¥",
        source: "SR5:CF",
      },
    },
    nanoCybernetic: {
      dynamicHandprints: {
        device: "Dynamic Handprints",
        rating: "-",
        essence: 0.2,
        availability: "12F",
        cost: "Rating x 21,00¥",
        source: "SR5:CF",
      },
      flashbackSystem: {
        device: "Flashback System",
        rating: "-",
        essence: 0.3,
        availability: "8R",
        cost: "6,000¥",
        source: "SR5:CF",
      },
      nanohiveHard: {
        device: "Nanohive (Hard)(4)",
        rating: "1–6",
        essence: 1,
        availability: "(Rating x 5)R",
        cost: "Rating x 12,000¥",
        source: "SR5:CF",
      },
      nanohiveSoft: {
        device: "Nanohive (Soft)(4)",
        rating: "1–6",
        essence: 0.8,
        availability: "(Rating x 5)R",
        cost: "Rating x 10,000¥",
        source: "SR5:CF",
      },
      retinalAdjusters: {
        device: "Retinal Adjusters",
        rating: "-",
        essence: 0.2,
        availability: "16F",
        cost: "Rating x 19,000¥",
        source: "SR5:CF",
      },
      smartskin: {
        device: "Smartskin(3)",
        rating: "1–6",
        essence: 1.5,
        availability: "(Rating x 5)F",
        cost: "Rating x 5,000¥",
        source: "SR5:CF",
      },
      voiceMimic: {
        device: "Voice Mimic",
        rating: "1–6",
        essence: 0.2,
        availability: "16F",
        cost: "Rating x 20,000¥",
        source: "SR5:CF",
      },
    },
    basicBioware: {
      adrenalinePump: {
        type: "Basic",

        device: "Adrenaline Pump (R 1-3)",
        essence: 2.25,
        avail: "(Rating * 6)F",
        cost: "Rating * 55,000¥",
        source: "Core",
      },
      boneDensityAugmentation: {
        type: "Basic",

        device: "Bone Density Augmentation (R 1-4)",
        essence: 1.2,
        avail: "Rating * 4",
        cost: "Rating * 5,000¥",
        source: "Core",
      },
      catsEye: {
        type: "Basic",

        device: "Cat's Eye",
        essence: 0.1,
        avail: 4,
        cost: "4,000¥",
        source: "Core",
      },
      enhancedArticulation: {
        type: "Basic",

        device: "Enhanced Articulation",
        essence: 0.3,
        avail: 12,
        cost: "24,000¥",
        source: "Core",
      },
      muscleAugmentation: {
        type: "Basic",
        addedStats: ["stats", "strength", 4],
        device: "Muscle Augmentation (R 1-4)",
        essence: 0.8,
        avail: "(Rating * 5)R",
        cost: "Rating * 31,000¥",
        source: "Core",
      },
      muscleToner: {
        type: "Basic",
        addedStats: ["stats", "agility", 4],
        device: "Muscle Toner (R 1-4)",
        essence: 0.8,
        avail: "(Rating * 5)R",
        cost: "Rating * 32,000¥",
        source: "Core",
      },
      orthoskin: {
        type: "Basic",
        addedStats: ["armor", "armor", 4],
        device: "Orthoskin (R 1-4)",
        essence: 1,
        avail: "(Rating * 4)R",
        cost: "Rating * 6,000¥",
        source: "Core",
      },
      plateletFactories: {
        type: "Basic",

        device: "Platelet Factories",
        essence: 0.2,
        avail: 12,
        cost: "17,000¥",
        source: "Core",
      },
      skinPocket: {
        type: "Basic",

        device: "Skin Pocket",
        essence: 0.1,
        avail: 4,
        cost: "12,000¥",
        source: "Core",
      },
      suprathyroidGland: {
        type: "Basic",
        addedStats: ["stats", "agility", 1],
        addedStatsTwo: ["stats", "reaction", 1],
        addedStatsThree: ["stats", "body", 1],
        addedStatsFour: ["stats", "strength", 1],
        device: "Suprathyroid Gland",
        essence: 0.7,
        avail: "20R",
        cost: "140,000¥",
        source: "Core",
      },

      chemicalGland: {
        type: "Basic",

        device: "Chemical Gland",
        essence: 0.1,
        avail: "12R (or chemical)",
        cost: "20,000¥",
        source: "SR5:CF",
      },
      exhalationSpray: {
        type: "Basic",

        device: "Exhalation Spray",
        essence: 0.1,
        avail: "12R",
        cost: "6,000¥",
        source: "SR5:CF",
      },
      spit: {
        type: "Basic",

        device: "Spit",
        essence: 0.1,
        avail: "12R",
        cost: "6,000¥",
        source: "SR5:CF",
      },
      weaponReservoir: {
        type: "Basic",

        device: "Weapon Reservoir",
        essence: 0.1,
        avail: "12F",
        cost: "4,000¥",
        source: "SR5:CF",
      },
      expandedReservoir: {
        type: "Basic",

        device: "Expanded Reservoir",
        essence: 0.1,
        avail: 12,
        cost: "2,000¥",
        source: "SR5:CF",
      },

      gills: {
        type: "Basic",

        device: "Gills",
        essence: 0.2,
        avail: 8,
        cost: "8,000¥",
        source: "SR5:CF",
      },

      hearingEnhancement: {
        type: "Basic",

        device: "Hearing Enhancement",
        essence: 0.1,
        avail: 4,
        cost: "4,000¥",
        source: "SR5:CF",
      },
      hearingExpansion: {
        type: "Basic",

        device: "Hearing Expansion",
        essence: 0.1,
        avail: 8,
        cost: "4,000¥",
        source: "SR5:CF",
      },
      nictitatingMembrane: {
        type: "Basic",

        device: "Nictitating Membrane",
        essence: 0.05,
        avail: 6,
        cost: "1,000¥",
        source: "SR5:CF",
      },
      replacementFingerToe: {
        type: "Basic",

        device: "Replacement Finger/Toe",
        essence: 0,
        avail: 2,
        cost: "1,000¥",
        source: "SR5:CF",
      },

      spidersilkGland: {
        type: "Basic",

        device: "Spidersilk Gland",
        essence: 0.3,
        avail: 10,
        cost: "35,000¥",
        source: "SR5:CF",
      },

      tail: {
        type: "Basic",

        device: "Tail",
        essence: 0.25,
        avail: 4,
        cost: "2,000¥",
        source: "SR5:CF",
      },
      prehensileTail: {
        type: "Basic",

        device: "Tail (prehensile)",
        essence: 0.5,
        avail: 8,
        cost: "8,000¥",
        source: "SR5:CF",
      },
      tailoredCritterPheromones: {
        type: "Basic",

        device: "Tailored Critter Pheromones (1-3)",
        essence: 0.3,
        avail: "(Rating) X 4",
        cost: "(Rating) x 2,000¥",
        source: "SR5:CF",
      },

      vocalRangeEnhancer: {
        type: "Basic",

        device: "Vocal Range Enhancer",
        essence: 0.1,
        avail: 8,
        cost: "10,000¥",
        source: "SR5:CF",
      },
      vocalRangeExpander: {
        type: "Basic",

        device: "Vocal Range Expander",
        essence: 0.2,
        avail: "12R",
        cost: "30,000¥",
        source: "SR5:CF",
      },
    },
    culturedBioware: {
      cerebralBooster: {
        type: "Cultured",
        addedStats: ["stats", "intuition", 3],
        device: "Cerebral Booster (R 1-3)",
        essence: 0.6,
        avail: "Rating * 6",
        cost: "Rating * 31,500¥",
        source: "Core",
      },

      mnemonicEnhancer: {
        type: "Cultured",

        device: "Mnemonic Enhancer (R 1-3)",
        essence: 0.3,
        avail: "Rating * 5",
        cost: "Rating * 9,000¥",
        source: "Core",
      },
      painEditor: {
        type: "Cultured",
        addedStats: ["stats", "willpower", 3],
        // addedStatsTwo: ["stats", "intuition", -3],

        device: "Pain Editor",
        essence: 0.3,
        avail: "18F",
        cost: "48,000¥",
        source: "Core",
      },

      sleepRegulator: {
        type: "Cultured",

        device: "Sleep Regulator",
        essence: 0.1,
        avail: 6,
        cost: "12,000¥",
        source: "Core",
      },
      synapticBooster: {
        type: "Cultured",
        addedStats: ["stats", "reaction", 3],
        addedStats: ["initiative", "dice", 3],
        device: "Synaptic Booster (R 1-3)",
        essence: 1.5,
        avail: "(Rating * 6)R",
        cost: "Rating * 95,000¥",
        source: "Core",
      },
      boostedReflexes: {
        type: "Cultured",
        addedStats: ["initiative", "dice", 1],
        device: "Boosted Reflexes",
        essence: 1.0,
        avail: "8R",
        cost: "10,000¥",
        source: "SR5:CF",
      },
    },
  };

  return cyberware;
}
