export default function returnElectronics() {
  const electronics = {
    comlinks: {
      metaLink: {
        name: "Meta Link",
        type: "Commlink",
        rating: 1,
        avail: 2,
        cost: "100¥",
        source: "Core",
      },
      sonyEmperor: {
        name: "Sony Emperor",
        type: "Commlink",
        rating: 2,
        avail: 4,
        cost: "700¥",
        source: "Core",
      },
      renrakuSensei: {
        name: "Renraku Sensei",
        type: "Commlink",
        rating: 3,
        avail: 6,
        cost: "1,000¥",
        source: "Core",
      },
      erikaElite: {
        name: "Erika Elite",
        type: "Commlink",
        rating: 4,
        avail: 8,
        cost: "2,500¥",
        source: "Core",
      },
      hermesIkon: {
        name: "Hermes Ikon",
        type: "Commlink",
        rating: 5,
        avail: 10,
        cost: "3,000¥",
        source: "Core",
      },
      transysAvalon: {
        name: "Transys Avalon",
        type: "Commlink",
        rating: 6,
        avail: 12,
        cost: "5,000¥",
        source: "Core",
      },
      fairlightCaliban: {
        name: "Fairlight Caliban",
        type: "Commlink",
        rating: 7,
        avail: 14,
        cost: "8,000¥",
        source: "Core",
      },
      evoTechHimitsu: {
        name: "EvoTech Himitsu",
        type: "Commlink",
        rating: 2,
        avail: "8R",
        cost: "11,000¥",
        source: "SR5:DT",
      },
      mctBlueDefender: {
        name: "MCT Blue Defender",
        type: "Commlink",
        rating: 3,
        avail: 7,
        cost: "2,000¥",
        source: "SR5:DT",
      },
      nixdorfSekretar: {
        name: "Nixdorf Sekretär",
        type: "Commlink",
        rating: 4,
        avail: 5,
        cost: "4,000¥",
        source: "SR5:DT",
      },
    },
    software: {
      agentR1_3: {
        name: "Agent (R 1–3)",
        type: "Program",
        avail: "Rating x 3",
        cost: "Rating x 1,000¥",
        source: "Core",
      },
      agentR4_6: {
        name: "Agent (R 4–6)",
        type: "Program",
        avail: "Rating x 3",
        cost: "Rating x 2,000¥",
        source: "Core",
      },
      autosoft: {
        name: "Autosoft",
        type: "Program",
        avail: "Rating x 2",
        cost: "Rating x 500¥",
        source: "Core",
      },
      cyberprogramCommonUse: {
        name: "Cyberprogram, common use",
        type: "Program",
        avail: "-",
        cost: "80¥",
        source: "Core",
      },
      cyberprogramHacking: {
        name: "Cyberprogram, hacking",
        type: "Program",
        avail: "6R",
        cost: "250¥",
        source: "Core",
      },
      datasoft: {
        name: "Datasoft",
        type: "Program",
        avail: 4,
        cost: "120¥",
        source: "Core",
      },
      mapsoft: {
        name: "Mapsoft",
        type: "Program",
        avail: 4,
        cost: "100¥",
        source: "Core",
      },
      shopsoft: {
        name: "Shopsoft",
        type: "Program",
        avail: 4,
        cost: "150¥",
        source: "Core",
      },
      tutorsoftR1_6: {
        name: "Tutorsoft (R 1–6)",
        type: "Program",
        avail: "Rating",
        cost: "Rating x 400¥",
        source: "Core",
      },
      activesoftsR1_6: {
        name: "Activesofts (R 1–6)",
        type: "SkillSoft",
        avail: 8,
        cost: "Rating x 5,000¥",
        source: "Core",
      },
      knowsoftsR1_6: {
        name: "Knowsofts (R 1–6)",
        type: "SkillSoft",
        avail: 4,
        cost: "Rating x 2,000¥",
        source: "Core",
      },
      linguasoftsR1_6: {
        name: "Linguasofts (R 1–6)",
        type: "SkillSoft",
        avail: 2,
        cost: "Rating x 1,000¥",
        source: "Core",
      },
    },
    cyberdecks: {
      erikaMcd1: {
        name: "Erika MCD-1",
        deviceRating: 1,
        attributeArray: [4, 3, 2, 1],
        programs: 1,
        avail: "3R",
        cost: "49,500¥",
        source: "Core",
      },
      microdeckSummit: {
        name: "Microdeck Summit",
        deviceRating: 1,
        attributeArray: [4, 3, 3, 1],
        programs: 1,
        avail: "3R",
        cost: "58,000¥",
        source: "Core",
      },
      microtronicaAzteca200: {
        name: "Microtrónica Azteca 200",
        deviceRating: 2,
        attributeArray: [5, 4, 3, 2],
        programs: 2,
        avail: "6R",
        cost: "110,250¥",
        source: "Core",
      },
      hermesChariot: {
        name: "Hermes Chariot",
        deviceRating: 2,
        attributeArray: [5, 4, 4, 2],
        programs: 2,
        avail: "6R",
        cost: "123,000¥",
        source: "Core",
      },
      novatechNavigator: {
        name: "Novatech Navigator",
        deviceRating: 3,
        attributeArray: [6, 5, 4, 3],
        programs: 3,
        avail: "9R",
        cost: "205,750¥",
        source: "Core",
      },
      renrakuTsurugi: {
        name: "Renraku Tsurugi",
        deviceRating: 3,
        attributeArray: [6, 5, 5, 3],
        programs: 3,
        avail: "9R",
        cost: "214,125¥",
        source: "Core",
      },
      sonyCiy720: {
        name: "Sony CIY-720",
        deviceRating: 4,
        attributeArray: [7, 6, 5, 4],
        programs: 4,
        avail: "12R",
        cost: "345,000¥",
        source: "Core",
      },
      shiawaseCyber5: {
        name: "Shiawase Cyber-5",
        deviceRating: 5,
        attributeArray: [8, 7, 6, 5],
        programs: 5,
        avail: "15R",
        cost: "549,375¥",
        source: "Core",
      },
      fairlightExcalibur: {
        name: "Fairlight Excalibur",
        deviceRating: 6,
        attributeArray: [9, 8, 7, 6],
        programs: 6,
        avail: "18R",
        cost: "823,250¥",
        source: "Core",
      },
      radioShackPcd500: {
        name: "Radio Shack PCD-500",
        deviceRating: 1,
        attributeArray: [2, 2, 1, 1],
        programs: 1,
        avail: "2",
        cost: "21,000¥",
        source: "SR5:DT",
      },
      littleHornet: {
        name: "Little Hornet",
        deviceRating: 2,
        attributeArray: [5, 4, 1, 1],
        programs: 2,
        avail: "5R",
        cost: "89,700¥",
        source: "SR5:DT",
      },
      microtronicaAzteca300: {
        name: "Microtrónica Azteca 300",
        deviceRating: 3,
        attributeArray: [7, 5, 3, 1],
        programs: 3,
        avail: "9R",
        cost: "200,000¥",
        source: "SR5:DT",
      },
      xiaoMpg1: {
        name: "Xiao MPG-1",
        deviceRating: 4,
        attributeArray: [8, 5, 4, 3],
        programs: 3,
        avail: "13R",
        cost: "302,000¥",
        source: "SR5:DT",
      },
      shiawaseCyber4: {
        name: "Shiawase Cyber-4",
        deviceRating: 4,
        attributeArray: [8, 6, 4, 2],
        programs: 3,
        avail: "12R",
        cost: "331,000¥",
        source: "SR5:DT",
      },
      fairlightPaladin: {
        name: "Fairlight Paladin",
        deviceRating: 6,
        attributeArray: [9, 9, 8, 8],
        programs: 6,
        avail: "20R",
        cost: "1,050,000¥",
        source: "SR5:DT",
      },
      mctTrainee: {
        name: "MCT Trainee",
        deviceRating: 1,
        attributeArray: [2, 1, 1, 2],
        programs: 1,
        avail: "3R",
        cost: "17,250¥",
        source: "SR5:DT",
      },
      cKAnalyst: {
        name: "C-K Analyst",
        deviceRating: 2,
        attributeArray: [1, 5, 4, 3],
        programs: 1,
        avail: "5R",
        cost: "83,800¥",
        source: "SR5:DT",
      },
      aztechnologyEmissary: {
        name: "Aztechnology Emissary",
        deviceRating: 3,
        attributeArray: [2, 3, 3, 8],
        programs: 1,
        avail: "8R",
        cost: "168,000¥",
        source: "SR5:DT",
      },
    },
    cyberdeckModules: {
      hardening: {
        name: "Hardening",
        availability: "3R",
        cost: "1,500¥",
        source: "SR5:DT",
      },
      inductionReceiver: {
        name: "Induction Receiver",
        availability: "10R",
        cost: "1,200¥",
        source: "SR5:DT",
      },
      multidimensionalCoprocessor: {
        name: "Multidimensional Coprocessor",
        availability: "7R",
        cost: "1,400¥",
        source: "SR5:DT",
      },
      overwatchMask: {
        name: "Overwatch Mask",
        availability: "9F",
        cost: "4,200¥",
        source: "SR5:DT",
      },
      programCarrier: {
        name: "Program Carrier",
        availability: "2",
        cost: "900¥",
        source: "SR5:DT",
      },
      selfDestruct: {
        name: "Self-Destruct",
        availability: "12F",
        cost: "200¥",
        source: "SR5:DT",
      },
      vectoredSignalFilter: {
        name: "Vectored Signal Filter",
        availability: "3",
        cost: "800¥",
        source: "SR5:DT",
      },
    },
    rcc: {
      scratchBuiltJunk: {
        type: "RCC",
        name: "Scratch-Built Junk",
        deviceRating: 1,
        availability: "2R",
        cost: "1,400¥",
        dataProcessing: 3,
        firewall: 2,
        source: "Core",
      },
      radioShackRemoteController: {
        type: "RCC",
        name: "Radio Shack Remote Controller",
        deviceRating: 2,
        availability: "6R",
        cost: "8,000¥",
        dataProcessing: 3,
        firewall: 3,
        source: "Core",
      },
      essyMotorsDroneMaster: {
        type: "RCC",
        name: "Essy Motors DroneMaster",
        deviceRating: 3,
        availability: "6R",
        cost: "16,000¥",
        dataProcessing: 4,
        firewall: 4,
        source: "Core",
      },
      compuForceTaskMaster: {
        type: "RCC",
        name: "CompuForce TaskMaster",
        deviceRating: 4,
        availability: "8R",
        cost: "3,200¥",
        dataProcessing: 5,
        firewall: 4,
        source: "Core",
      },
      maerskSpider: {
        type: "RCC",
        name: "Maersk Spider",
        deviceRating: 4,
        availability: "8R",
        cost: "34,000¥",
        dataProcessing: 4,
        firewall: 5,
        source: "Core",
      },
      maserIndustrialElectronics: {
        type: "RCC",
        name: "Maser Industrial Electronics",
        deviceRating: 5,
        availability: "8R",
        cost: "64,000¥",
        dataProcessing: 3,
        firewall: 4,
        source: "Core",
      },
      vulcanLiegelord: {
        type: "RCC",
        name: "Vulcan Liegelord",
        deviceRating: 5,
        availability: "10R",
        cost: "66,000¥",
        dataProcessing: 5,
        firewall: 6,
        source: "Core",
      },
      proteusPoseidon: {
        type: "RCC",
        name: "Proteus Poseidon",
        deviceRating: 5,
        availability: "12R",
        cost: "68,000¥",
        dataProcessing: 5,
        firewall: 6,
        source: "Core",
      },
      loneStarRemoteCommander: {
        type: "RCC",
        name: "Lone Star Remote Commander",
        deviceRating: 6,
        availability: "14R",
        cost: "75,000¥",
        dataProcessing: 6,
        firewall: 5,
        source: "Core",
      },
      mctDroneWeb: {
        type: "RCC",
        name: "MCT Drone Web",
        deviceRating: 6,
        availability: "16R",
        cost: "95,000¥",
        dataProcessing: 7,
        firewall: 6,
        source: "Core",
      },
    },
  };

  return electronics;
}
