export default function returnDrones() {
  const drones = {
    microDrones: {
      shiawaseKanmushi: {
        size: "Micro",
        drone: "Shiawase Kanmushi",
        handl: "4",
        speed: "2",
        accel: "1",
        body: "0",
        armor: "0",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "8",
        cost: "1,000¥",
        source: "Core",
      },
      silkorskyBellMicroskimmer: {
        size: "Micro",
        drone: "Silkorsky-Bell Microskimmer",
        handl: "3",
        speed: "3",
        accel: "1",
        body: "0",
        armor: "0",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "6",
        cost: "1,000¥",
        source: "Core",
      },
      goldfish: {
        size: "Micro",
        drone: "Goldfish",
        handl: "2/4",
        speed: "1W",
        accel: "1",
        body: "0",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "6",
        cost: "500¥",
        source: "SR5:R5",
      },
      noizQuito: {
        size: "Micro",
        drone: "NoizQuito",
        handl: "4",
        speed: "3R",
        accel: "2",
        body: "1",
        armor: "0",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "10R",
        cost: "2,000¥",
        source: "SR5:R5",
      },
    },
    miniDrones: {
      mctFlySpy: {
        size: "Mini",
        drone: "MCT Fly-Spy",
        handl: "4",
        speed: "3",
        accel: "2",
        body: "1",
        armor: "0",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "8",
        cost: "2,000¥",
        source: "Core",
      },
      horizonFlyingEye: {
        size: "Mini",
        drone: "Horizon Flying Eye",
        handl: "4",
        speed: "3",
        accel: "2",
        body: "1",
        armor: "0",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "8",
        cost: "2,000¥",
        source: "Core",
      },
      condor: {
        size: "Mini",
        drone: "Condor",
        handl: "2",
        speed: "0R",
        accel: "0",
        body: "1(1)",
        armor: "0",
        pilot: "2",
        sensor: "4",
        seats: "-",
        avail: "6R",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      dragonfly: {
        size: "Mini",
        drone: "Dragonfly",
        handl: "4",
        speed: "2P",
        accel: "1",
        body: "1(0)",
        armor: "3",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "12R",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      gerbil: {
        size: "Mini",
        drone: "Gerbil",
        handl: "4/2",
        speed: "2G",
        accel: "1",
        body: "1(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      hedgehog: {
        size: "Mini",
        drone: "Hedgehog",
        handl: "3",
        speed: "1G",
        accel: "1",
        body: "1(0)",
        armor: "0",
        pilot: "4",
        sensor: "3",
        seats: "-",
        avail: "8F",
        cost: "8,000¥",
        source: "SR5:R5",
      },
      horizonCU3: {
        size: "Mini",
        drone: "Horizon CU^3",
        handl: "4",
        speed: "1P",
        accel: "1",
        body: "1(1)",
        armor: "0",
        pilot: "2",
        sensor: "3",
        seats: "-",
        avail: "4",
        cost: "3,000¥",
        source: "SR5:R5",
      },
      pigeon20: {
        size: "Mini",
        drone: "Pigeon 2.0",
        handl: "4",
        speed: "2P",
        accel: "1",
        body: "1(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8",
        cost: "3,000¥",
        source: "SR5:R5",
      },
      remoteCyberhand: {
        size: "Mini",
        drone: "Remote Cyberhand",
        handl: "n/a",
        speed: "n/a",
        accel: "n/a",
        body: "n/a",
        armor: "n/a",
        pilot: "0",
        sensor: "-",
        seats: "8",
        avail: "8",
        cost: "8,000¥",
        source: "SR5:R5",
      },
    },
    smallDrones: {
      aztechnologyCrawler: {
        size: "Small",
        drone: "Aztechnology Crawler",
        handl: "4",
        speed: "3",
        accel: "1",
        body: "3",
        armor: "3",
        pilot: "4",
        sensor: "3",
        seats: "-",
        avail: "4",
        cost: "4,000¥",
        source: "Core",
      },
      lockheedOpticX2: {
        size: "Small",
        drone: "Lockheed Optic-X2",
        handl: "4",
        speed: "4",
        accel: "3",
        body: "2",
        armor: "2",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "10",
        cost: "21,000¥",
        source: "Core",
      },
      bloodhound: {
        size: "Small",
        drone: "Bloodhound",
        handl: "3",
        speed: "1G",
        accel: "1",
        body: "2(0)",
        armor: "0",
        pilot: "2",
        sensor: "4",
        seats: "-",
        avail: "8",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      castleGuard: {
        size: "Small",
        drone: "Castle Guard",
        handl: "4/2",
        speed: "1G",
        accel: "1",
        body: "2(0)",
        armor: "6",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "8R",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      ferretRPD5X: {
        size: "Small",
        drone: "Ferret RPD-5X",
        handl: "4/2",
        speed: "1G",
        accel: "1",
        body: "2(1)",
        armor: "3",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "8R",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      gunTurret: {
        size: "Small",
        drone: "Gun Turret",
        handl: "0",
        speed: "0",
        accel: "0",
        body: "2(0)",
        armor: "6",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "4R",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      jardinero: {
        size: "Small",
        drone: "Jardinero",
        handl: "2/4",
        speed: "1G",
        accel: "1",
        body: "2(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      jobAMat: {
        size: "Small",
        drone: "Job-a-Mat",
        handl: "0",
        speed: "0",
        accel: "0",
        body: "2(2)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "3,000¥",
        source: "SR5:R5",
      },
      knightErrantP5: {
        size: "Small",
        drone: "Knight Errant P5",
        handl: "4/2",
        speed: "6G",
        accel: "2",
        body: "2(1)",
        armor: "0",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "10R",
        cost: "8,000¥",
        source: "SR5:R5",
      },
      krake: {
        size: "Small",
        drone: "Krake",
        handl: "5",
        speed: "3W",
        accel: "4",
        body: "2(0)",
        armor: "2",
        pilot: "4",
        sensor: "3",
        seats: "-",
        avail: "18F",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      miniZep: {
        size: "Small",
        drone: "Mini-Zep",
        handl: "2",
        speed: "0P",
        accel: "0",
        body: "2(4)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      pelican: {
        size: "Small",
        drone: "Pelican",
        handl: "4",
        speed: "2P",
        accel: "1",
        body: "2(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "2",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      prairieDog: {
        size: "Small",
        drone: "Prairie Dog",
        handl: "2/4",
        speed: "2G",
        accel: "1",
        body: "2(0)",
        armor: "3",
        pilot: "3",
        sensor: "4",
        seats: "-",
        avail: "12F",
        cost: "8,000¥",
        source: "SR5:R5",
      },
      proletarian: {
        size: "Small",
        drone: "Proletarian",
        handl: "4/2",
        speed: "2G",
        accel: "1",
        body: "2(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "6",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      renrakuDove: {
        size: "Small",
        drone: "Renraku Dove",
        handl: "4",
        speed: "2P",
        accel: "1",
        body: "2(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "5,000¥",
        source: "SR5:R5",
      },
      sentryV: {
        size: "Small",
        drone: "Sentry V",
        handl: "4/—",
        speed: "1G",
        accel: "1",
        body: "2(0)",
        armor: "6",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "4R",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      sevenWheelie: {
        size: "Small",
        drone: "Seven (Wheelie)",
        handl: "4/2",
        speed: "2G",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "-",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      sevenTreads: {
        size: "Small",
        drone: "Seven (Treads)",
        handl: "3",
        speed: "2G",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "2",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      sevenDirty: {
        size: "Small",
        drone: "Seven (Dirty)",
        handl: "2/4",
        speed: "2G",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "2",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      sevenQuad: {
        size: "Small",
        drone: "Seven (Quad)",
        handl: "4",
        speed: "1G",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      sevenSwims: {
        size: "Small",
        drone: "Seven (Swims)",
        handl: "3",
        speed: "2W",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:R5",
      },
      sevenHovers: {
        size: "Small",
        drone: "Seven (Hovers)",
        handl: "4",
        speed: "1P",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "6",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      sevenSoars: {
        size: "Small",
        drone: "Seven (Soars)",
        handl: "3",
        speed: "2J",
        accel: "1",
        body: "1(3)",
        armor: "0",
        pilot: "1",
        sensor: "1",
        seats: "-",
        avail: "8",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      sewerSnake: {
        size: "Small",
        drone: "Sewer Snake",
        handl: "3",
        speed: "1G/1W",
        accel: "1/1",
        body: "2(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "10",
        cost: "6,000¥",
        source: "SR5:R5",
      },
      shamus: {
        size: "Small",
        drone: "Shamus",
        handl: "3",
        speed: "3G",
        accel: "1",
        body: "4(0)",
        armor: "4",
        pilot: "3",
        sensor: "8",
        seats: "-",
        avail: "10",
        cost: "30,000¥",
        source: "SR5:R5",
      },
      smokeGenerator: {
        size: "Small",
        drone: "Smoke Generator",
        handl: "3",
        speed: "1G",
        accel: "1",
        body: "2(0)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      sundowner: {
        size: "Small",
        drone: "Sundowner",
        handl: "3",
        speed: "4P",
        accel: "1",
        body: "2(0)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      wolfhound: {
        size: "Small",
        drone: "Wolfhound",
        handl: "3",
        speed: "2J",
        accel: "1",
        body: "2(1)",
        armor: "0",
        pilot: "2",
        sensor: "4",
        seats: "-",
        avail: "12",
        cost: "30,000¥",
        source: "SR5:R5",
      },
    },
    mediumDrones: {
      aresDuelist: {
        size: "Medium",
        drone: "Ares Duelist",
        handl: "3",
        speed: "3",
        accel: "1",
        body: "4",
        armor: "4",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "5R",
        cost: "4,500¥",
        source: "Core",
      },
      gmNissanDoberman: {
        size: "Medium",
        drone: "GM-Nissan Doberman",
        handl: "5",
        speed: "3",
        accel: "1",
        body: "4",
        armor: "4",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "4R",
        cost: "5,000¥",
        source: "Core",
      },
      mctNissanRotoDrone: {
        size: "Medium",
        drone: "MCT-Nissan Roto-Drone",
        handl: "4",
        speed: "4",
        accel: "2",
        body: "4",
        armor: "4",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "6",
        cost: "5,000¥",
        source: "Core",
      },
      cheetah: {
        size: "Medium",
        drone: "Cheetah",
        handl: "4",
        speed: "6G",
        accel: "2",
        body: "2(0)",
        armor: "6",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "12R",
        cost: "14,000¥",
        source: "SR5:R5",
      },
      evoKrokodil: {
        size: "Medium",
        drone: "Evo Krokodil",
        handl: "3",
        speed: "2G/3W",
        accel: "1",
        body: "3(1)",
        armor: "6",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8R",
        cost: "12,000¥",
        source: "SR5:R5",
      },
      fBKull: {
        size: "Medium",
        drone: "F-B Kull",
        handl: "3",
        speed: "4P",
        accel: "2",
        body: "3(3)",
        armor: "0",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      lebd2: {
        size: "Medium",
        drone: "LEBD-2",
        handl: "4",
        speed: "2P",
        accel: "1",
        body: "3(0)",
        armor: "9",
        pilot: "4",
        sensor: "4",
        seats: "-",
        avail: "12R",
        cost: "20,000¥",
        source: "SR5:R5",
      },
      steed: {
        size: "Medium",
        drone: "Steed",
        handl: "4/2",
        speed: "1G",
        accel: "1",
        body: "3(1)",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "2",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      tunneler: {
        size: "Medium",
        drone: "Tunneler",
        handl: "3",
        speed: "0P",
        accel: "0",
        body: "3(2)",
        armor: "6",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8R",
        cost: "10,000¥",
        source: "SR5:R5",
      },
    },
    largeDrones: {
      cyberspaceDesignsDalmation: {
        size: "Large",
        drone: "Cyberspace Designs Dalmation",
        handl: "5",
        speed: "5",
        accel: "3",
        body: "5",
        armor: "5",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "6R",
        cost: "10,000¥",
        source: "Core",
      },
      steelLynxCombatDrone: {
        size: "Large",
        drone: "Steel Lynx Combat Drone",
        handl: "5",
        speed: "4",
        accel: "2",
        body: "6",
        armor: "12",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "10R",
        cost: "25,000¥",
        source: "Core",
      },
      malakim: {
        size: "Large",
        drone: "Malakim",
        handl: "3",
        speed: "6P",
        accel: "2",
        body: "4(0)",
        armor: "9",
        pilot: "4",
        sensor: "4",
        seats: "-",
        avail: "20F",
        cost: "40,000¥",
        source: "SR5:R5",
      },
      matilda: {
        size: "Large",
        drone: "Matilda",
        handl: "1",
        speed: "2G",
        accel: "1",
        body: "8",
        armor: "8",
        pilot: "2",
        sensor: "1",
        seats: "-",
        avail: "12R",
        cost: "18,000¥",
        source: "SR5:R5",
      },
      mediCart: {
        size: "Large",
        drone: "MediCart",
        handl: "5",
        speed: "5G",
        accel: "1",
        body: "6(2)",
        armor: "5",
        pilot: "4",
        sensor: "4",
        seats: "-",
        avail: "6",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      mule: {
        size: "Large",
        drone: "Mule",
        handl: "4",
        speed: "1G",
        accel: "1",
        body: "4(3)",
        armor: "6",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "8,000¥",
        source: "SR5:R5",
      },
      neptune: {
        size: "Large",
        drone: "Neptune",
        handl: "2",
        speed: "3W",
        accel: "1",
        body: "5(0)",
        armor: "3",
        pilot: "4",
        sensor: "3",
        seats: "-",
        avail: "10R",
        cost: "17,500¥",
        source: "SR5:R5",
      },
      paladin: {
        size: "Large",
        drone: "Paladin",
        handl: "5",
        speed: "4G",
        accel: "1",
        body: "5(0)",
        armor: "18",
        pilot: "3",
        sensor: "2",
        seats: "-",
        avail: "8R",
        cost: "5,000¥",
        source: "SR5:R5",
      },
      tower: {
        size: "Large",
        drone: "Tower",
        handl: "2",
        speed: "1P",
        accel: "1",
        body: "4(0)",
        armor: "6",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8",
        cost: "10,000¥",
        source: "SR5:R5",
      },
    },
    hugeDrones: {
      aresKNY0Deimos: {
        size: "Huge",
        drone: "Ares KN-Y0 (Deimos)",
        handl: "3",
        speed: "2G",
        accel: "1",
        body: "6(0)",
        armor: "18",
        pilot: "5",
        sensor: "3",
        seats: "-",
        avail: "20F",
        cost: "220,000¥",
        source: "SR5:R5",
      },
      aresKNY0Eris: {
        size: "Huge",
        drone: "Ares KN-Y0 (Eris)",
        handl: "3",
        speed: "2G",
        accel: "1",
        body: "6(0)",
        armor: "18",
        pilot: "5",
        sensor: "3",
        seats: "-",
        avail: "24F",
        cost: "270,000¥",
        source: "SR5:R5",
      },
      aresKNY0Phobos: {
        size: "Huge",
        drone: "Ares KN-Y0 (Phobos)",
        handl: "3",
        speed: "2G",
        accel: "1",
        body: "6(0)",
        armor: "18",
        pilot: "5",
        sensor: "3",
        seats: "-",
        avail: "16F",
        cost: "250,000¥",
        source: "SR5:R5",
      },
      avengingAngel: {
        size: "Huge",
        drone: "Avenging Angel",
        handl: "3",
        speed: "6J",
        accel: "2",
        body: "6(0)",
        armor: "12",
        pilot: "6",
        sensor: "6",
        seats: "-",
        avail: "40F",
        cost: "1,000,000¥",
        source: "SR5:R5",
      },
      kodiak: {
        size: "Huge",
        drone: "Kodiak",
        handl: "2/4",
        speed: "2G",
        accel: "1",
        body: "6(2)",
        armor: "12",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "12R",
        cost: "40,000¥",
        source: "SR5:R5",
      },
    },
    anthroDrones: {
      criadoJuan: {
        size: "Anthro",
        drone: "Criado Juan",
        handl: "2",
        speed: "2G",
        accel: "1",
        body: "2",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "2",
        cost: "8,000¥",
        source: "SR5:R5",
      },
      direktionssekretar: {
        size: "Anthro",
        drone: "Direktionssekretar",
        handl: "4",
        speed: "4G",
        accel: "2",
        body: "4",
        armor: "3",
        pilot: "4",
        sensor: "4",
        seats: "-",
        avail: "12R",
        cost: "40,000¥",
        source: "SR5:R5",
      },
      juggernaught: {
        size: "Anthro",
        drone: "Juggernaught",
        handl: "3",
        speed: "4G",
        accel: "1",
        body: "6",
        armor: "12",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "14R",
        cost: "100,000¥",
        source: "SR5:R5",
      },
      kenchikuKikai: {
        size: "Anthro",
        drone: "Kenchiku-Kikai",
        handl: "2",
        speed: "2G",
        accel: "1",
        body: "5",
        armor: "3",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "8R",
        cost: "20,000¥",
        source: "SR5:R5",
      },
      littleBuddy: {
        size: "Anthro",
        drone: "Little Buddy",
        handl: "2",
        speed: "1G",
        accel: "1",
        body: "1",
        armor: "0",
        pilot: "2",
        sensor: "2",
        seats: "-",
        avail: "4",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      shiawaseIDoll: {
        size: "Anthro",
        drone: "Shiawase i-Doll",
        handl: "3",
        speed: "3G",
        accel: "1",
        body: "3",
        armor: "0",
        pilot: "3",
        sensor: "3",
        seats: "-",
        avail: "4",
        cost: "20,000¥",
        source: "SR5:R5",
      },
    },
  };
  return drones;
}
