export default function returnSkills() {
  const skills = {
    physical: {
      diving: ["Diving", "body", "physical"],
      escapeArtist: ["Escape Artist", "agility", "physical"],
      freeFall: ["Free-Fall", "body", "physical"],
      gymnastics: ["Gymnastics", "agility", "physical"],
      palming: ["Palming", "agility", "physical"],
      running: ["Running", "strength", "physical"],
      sneaking: ["Sneaking", "agility", "physical"],
      survival: [["Survival"], "willpower", "mental"],
      swimming: ["Swimming", "strength", "physical"],
      tracking: ["Tracking", "intuition", "mental"],
      perception: ["Perception", "intuition", "mental"],
      lockpicking: ["Lockpicking", "agility", "mephysicalntal"],
    },
    social: {
      animalHandling: ["Animal Handling", "charisma", "social"],
      con: ["Con", "charisma", "social"],
      disguise: ["Disguise", "intuition", "mental"],
      etiquette: ["Etiquette", "charisma", "social"],
      instruction: ["Instruction", "charisma", "social"],
      intimidation: ["Intimidation", "charisma", "social"],
      impersonation: ["Impersonation", "charisma", "social"],
      leadership: ["Leadership", "charisma", "social"],
      negotiation: ["Negotiation", "charisma", "social"],
      performance: ["Performance", "charisma", "social"],
    },
    engineering: {
      aeronauticsMechanics: ["Aeronautics Mechanics", "logic", "mental"],
      armorer: ["Armorer", "logic", "mental"],
      industrialMechanics: ["Industrial Mechanics", "logic", "mental"],
      nauticalMechanics: ["Nautical Mechanics", "logic", "mental"],
      automotiveMechanic: ["Automotive Mechanic", "logic", "mental"],
      Hardware: ["Hardware", "logic", "mental"],
      artisan: ["Artisan", "intuition", "mental"],
    },
    scientific: {
      arcana: ["Arcana", "logic", "mental"],
      biotechnology: ["Biotechnology", "logic", "mental"],
      computer: ["Computer", "logic", "mental"],
      cybertechnology: ["Cybertechnology", "logic", "mental"],
      software: ["Software", "logic", "mental"],
      demolitions: ["Demolitions", "logic", "mental"],
      firstAid: ["First Aid", "logic", "mental"],
      forgery: ["Forgery", "agility", "mental"],
      hacking: ["Hacking", "logic", "mental"],
      medicine: ["Medicine", "logic", "mental"],
      chemistry: ["Chemistry", "logic", "mental"],
    },
    combat: {
      automatics: ["Automatics", "agility", "physical"],
      blades: ["Blades", "agility", "physical"],
      clubs: ["Clubs", "agility", "physical"],
      cybercombat: ["Cybercombat", "logic", "mental"],
      electronicWarfare: ["Electronic Warfare", "logic", "mental"],
      heavyWeapons: ["Heavy Weapons", "agility", "physical"],
      unarmedCombat: ["Unarmed Combat", "agility", "physical"],
      longarms: ["Longarms", "agility", "physical"],
      pistols: ["Pistols", "agility", "physical"],
    },
    vehicle: {
      gunnery: ["Gunnery", "agility", "physical"],
      pilotAerospace: ["Pilot Aerospace", "reaction", "physical"],
      pilotAircraft: ["Pilot Aircraft", "reaction", "physical"],
      pilotGroundCraft: ["Pilot Ground Craft", "reaction", "physical"],
      pilotWatercraft: ["Pilot Watercraft", "reaction", "physical"],
      pilotWalker: ["Pilot Walker", "reaction", "physical"],
      navigation: ["Navigation", "intuition", "mental"],
    },
    magical: {
      artificing: ["Artificing", "logic", "astral"],
      assensing: ["Assensing", "intuition", "mental"],
      astralCombat: ["Astral Combat", "willpower", "astral"],
      counterspelling: ["Counterspelling", "magic", "astral"],
      alchemy: ["Alchemy", "magic", "astral"],
      arcana: ["Arcana", "logic", "astral"],
      banishing: ["Banishing", "magic", "astral"],
      binding: ["Binding", "magic", "astral"],
      disenchanting: ["Disenchanting", "magic", "astral"],
      ritualSpellcasting: ["Ritual Spellcasting", "magic", "astral"],
      summoning: ["Summoning", "magic", "astral"],
      spellcasting: ["Spellcasting", "magic", "astral"],
    },
    resonance: {
      compiling: ["Compiling", "resonance", "mental"],
      decompiling: ["Decompiling", "resonance", "mental"],
      registering: ["Registering", "resonance", "mental"],
    },
  };
  return skills;
}
