export default function returnMagicalEquipment() {
  const magicalEquipment = {
    foci: {
      enchantingFocus: {
        type: "Foci",
        name: "Enchanting Focus",
        karmaCost: "Force x 3",
        avail: (force) => `${force * 3}R`,
        cost: (force) => `¥${5000 * force} * Force`,
        source: "Core",
      },
      metamagicFocus: {
        type: "Foci",
        name: "Metamagic Focus",
        karmaCost: "Force x 3",
        avail: (force) => `${force * 3}R`,
        cost: (force) => `¥${9000 * force} * Force`,
        source: "Core",
      },
      powerFocus: {
        type: "Foci",
        name: "Power Focus",
        karmaCost: "Force x 6",
        avail: (force) => `${force * 4}R`,
        cost: (force) => `¥${18000 * force} * Force`,
        source: "Core",
      },
      qiFocus: {
        type: "Foci",
        name: "Qi Focus",
        karmaCost: "Force x 2",
        avail: (force) => `${force * 3}R`,
        cost: (force) => `¥${3000 * force} * Force`,
        source: "Core",
      },
      spellFocus: {
        type: "Foci",
        name: "Spell Focus",
        karmaCost: "Force x 2",
        avail: (force) => `${force * 3}R`,
        cost: (force) => `¥${4000 * force} * Force`,
        source: "Core",
      },
      spiritFocus: {
        type: "Foci",
        name: "Spirit Focus",
        karmaCost: "Force x 2",
        avail: (force) => `${force * 3}R`,
        cost: (force) => `¥${4000 * force} * Force`,
        source: "Core",
      },
      weaponFocus: {
        type: "Foci",
        name: "Weapon Focus",
        karmaCost: "Force x 3",
        avail: (force) => `${force * 4}R`,
        cost: (force) => `¥${7000 * force} * Force`,
        source: "Core",
      },
    },
    euipment: {
      agHexHex: {
        item: "AgHexHex",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥8",
        avail: "8",
        cost: (force) => `¥${500 * force} * Force`,
        source: "SR5:SG",
      },
      aquaFictus: {
        item: "Aqua Fictus",
        skill: "Alchemy",
        threshold: "3",
        baseTime: "10 Hours",
        materialCost: "¥850",
        avail: "8",
        cost: "¥1,000",
        source: "SR5:SG",
      },
      aquaFortis: {
        item: "Aqua Fortis",
        skill: "Alchemy",
        threshold: "3",
        baseTime: "10 Hours",
        materialCost: "¥43",
        avail: "4",
        cost: "¥50",
        source: "SR5:SG",
      },
      aquaRegia: {
        item: "Aqua Regia",
        skill: "Alchemy",
        threshold: "3",
        baseTime: "10 Hours",
        materialCost: "¥85",
        avail: "5",
        cost: "¥100",
        source: "SR5:SG",
      },
      aquaVitae: {
        item: "Aqua Vitae",
        skill: "Alchemy",
        threshold: "3",
        baseTime: "4 Hours",
        materialCost: "¥13",
        avail: "1",
        cost: "¥15",
        source: "SR5:SG",
      },
      astralPowder: {
        item: "Astral Powder",
        skill: "Alchemy",
        threshold: "4",
        baseTime: "2 Days",
        materialCost: "¥70",
        avail: "4",
        cost: "¥120",
        source: "SR5:SG",
      },
      bdnb: {
        item: "BDNB",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥8",
        avail: "8",
        cost: (force) => `¥${500 * force} * Force`,
        source: "SR5:SG",
      },
      fabI: {
        item: "FAB I",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥10",
        avail: "10",
        cost: (force) => `¥50 * cubic meter`,
        source: "SR5:SG",
      },
      fabII: {
        item: "FAB II",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥16R",
        avail: "16R",
        cost: (force) => `¥${50 * force} * cubic meter`,
        source: "SR5:SG",
      },
      fabIII: {
        item: "FAB III",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥20F",
        avail: "20F",
        cost: (force) => `¥${25000 * force} * cubic meter`,
        source: "SR5:SG",
      },
      fetish: {
        item: "Fetish",
        skill: "Artificing",
        threshold: "2",
        baseTime: "1 Day",
        materialCost: "¥1,700",
        avail: "4",
        cost: "¥2,000",
        source: "SR5:SG",
      },
      govi: {
        item: "Govi",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥Force",
        avail: "Force",
        cost: (force) => `¥50 * Force`,
        source: "SR5:SG",
      },
      handOfGlory: {
        item: "Hand of Glory",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force^2)R",
        avail: "(Force^2)R",
        cost: (force) => `¥1,500 * Force`,
        source: "SR5:SG",
      },
      lotsCurse: {
        item: "Lot's Curse",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥14F",
        avail: "14F",
        cost: (force) => `¥1,000 * Force`,
        source: "SR5:SG",
      },
      magecuff: {
        item: "Magecuff",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥5",
        avail: "5",
        cost: "¥1,000",
        source: "SR5:SG",
      },
      magemask: {
        item: "Magemask",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥2R",
        avail: "2R",
        cost: "¥200",
        source: "SR5:SG",
      },
      manaSensitiveFilmPlate: {
        item: "Mana-Sensitive Film Plate",
        skill: "Alchemy",
        threshold: "4",
        baseTime: "3 Days",
        materialCost: "¥21",
        avail: "4",
        cost: "¥25",
        source: "SR5:SG",
      },
      mortisOptigram: {
        item: "Mortis Optigram",
        skill: "Artificing",
        threshold: "4",
        baseTime: "1 Week",
        materialCost: "¥2,550",
        avail: "6",
        cost: "¥3,000",
        source: "SR5:SG",
      },
      mysticCuff: {
        item: "Mystic Cuff",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force)R",
        avail: "(Force)R",
        cost: (force) => `¥200 * Force`,
        source: "SR5:SG",
      },
      mysticJacket: {
        item: "Mystic Jacket",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force)R",
        avail: "(Force)R",
        cost: (force) => `¥500 * Force`,
        source: "SR5:SG",
      },
      mysticMask: {
        item: "Mystic Mask",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force)R",
        avail: "(Force)R",
        cost: (force) => `¥400 * Force`,
        source: "SR5:SG",
      },
      quicksilverCamera: {
        item: "Quicksilver Camera",
        skill: "Artificing",
        threshold: "4",
        baseTime: "1 Week",
        materialCost: "¥2,125",
        avail: "4",
        cost: "¥2,500",
        source: "SR5:SG",
      },
      sage: {
        item: "Sage",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force * 6)R",
        avail: "800¥ * Force",
        cost: (force) => `¥800 * Force`,
        source: "SR5:SG",
      },
      shofar: {
        item: "Shofar",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥Force",
        avail: "800¥ * Force",
        cost: (force) => `¥800 * Force`,
        source: "SR5:SG",
      },
      spiritStrength: {
        item: "Spirit Strength",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force * 6)R",
        avail: "3,000¥ * Force",
        cost: (force) => `¥3,000 * Force`,
        source: "SR5:SG",
      },
      symbolicLink: {
        item: "Symbolic Link",
        skill: "Artificing",
        threshold: "-",
        baseTime: "1 Day",
        materialCost: "¥-",
        avail: "¥-",
        cost: "¥-",
        source: "SR5:SG",
      },
      witchsMoss: {
        item: "Witch's Moss",
        skill: "-",
        threshold: "-",
        baseTime: "-",
        materialCost: "¥(Force * 6)R",
        avail: "1,600¥ * Force",
        cost: (force) => `¥1,600 * Force`,
        source: "SR5:SG",
      },
    },
  };
}
