export default function returnWeapons() {
  const weapons = {
    clubs: {
      club: {
        Name: "Club",
        Accuracy: 4,
        Reach: 1,
        DV: "3P",
        "Armor Penetration": "-",
        Avail: "-",
        Cost: "30¥",
        Source: "Core",
      },
      ExtendableBaton: {
        Name: "Extendable Baton",
        Accuracy: 5,
        Reach: 1,
        DV: "2P",
        "Armor Penetration": "-",
        Avail: 4,
        Cost: "100¥",
        Source: "Core",
      },
      NemesisArmsMaulStunStaff: {
        Name: "Nemesis Arms Maul Stun Staff",
        Accuracy: 6,
        Reach: 2,
        DV: "9S(e)",
        "Armor Penetration": -5,
        Avail: "8R",
        Cost: "1,000¥",
        Source: "SR5:R&G",
      },
      Sap: {
        Name: "Sap",
        Accuracy: 5,
        Reach: "-",
        DV: "2P",
        "Armor Penetration": "-",
        Avail: 2,
        Cost: "30¥",
        Source: "Core",
      },
      Staff: {
        Name: "Staff",
        Accuracy: 6,
        Reach: 2,
        DV: "3P",
        "Armor Penetration": "-",
        Avail: 3,
        Cost: "100¥",
        Source: "Core",
      },
      StunBaton: {
        Name: "Stun Baton",
        Accuracy: 4,
        Reach: 1,
        DV: "9S(e)",
        "Armor Penetration": -5,
        Avail: "6R",
        Cost: "750¥",
        Source: "Core",
      },
      TelescopingStaff: {
        Name: "Telescoping Staff",
        Accuracy: 4,
        Reach: 2,
        DV: "2P",
        "Armor Penetration": "-",
        Avail: 4,
        Cost: "350¥",
        Source: "Core",
      },
    },
    blades: {
      AresOneMonosword: {
        Name: "Ares One Monosword",
        Accuracy: 5,
        Reach: 1,
        DV: "3P",
        AP: -3,
        Avail: "8R",
        Cost: "900¥",
        Source: "SR5:R&G",
      },
      CeramicKnife: {
        Name: "Ceramic Knife",
        Accuracy: 5,
        Reach: "-",
        DV: "2P",
        AP: -1,
        Avail: 4,
        Cost: "75¥",
        Source: "SR5:HT",
      },
      CombatAxe: {
        Name: "Combat Axe",
        Accuracy: 4,
        Reach: 2,
        DV: "5P",
        AP: -4,
        Avail: "12R",
        Cost: "4,000¥",
        Source: "Core",
      },
      CombatKnife: {
        Name: "Combat Knife",
        Accuracy: 6,
        Reach: "-",
        DV: "2P",
        AP: -3,
        Avail: 4,
        Cost: "300¥",
        Source: "Core",
      },
      CougarCollapsibleSpear: {
        Name: "Cougar Collapsible Spear",
        Accuracy: 5,
        Reach: "- / 3",
        DV: "1/ 3)P",
        AP: "-1 / -2",
        Avail: "14R",
        Cost: "1,250¥",
        Source: "SR5:HT",
      },
      CougarFineShortblade: {
        Name: "Cougar Fine Shortblade",
        Accuracy: 7,
        Reach: "-",
        DV: "2P",
        AP: -1,
        Avail: "5R",
        Cost: "350¥",
        Source: "SR5:R&G",
      },
      CougarFineLongblade: {
        Name: "Cougar Fine Longblade",
        Accuracy: 7,
        Reach: "-",
        DV: "3P",
        AP: -1,
        Avail: "7R",
        Cost: "600¥",
        Source: "SR5:R&G",
      },
      ForearmSnapBlades: {
        Name: "Forearm Snap-Blades",
        Accuracy: 4,
        Reach: "-",
        DV: "2P",
        AP: -2,
        Avail: "7R",
        Cost: "200¥",
        Source: "Core",
      },
      HighlandForgeClaymore: {
        Name: "Highland Forge Claymore",
        Accuracy: 5,
        Reach: 2,
        DV: "5P",
        AP: -5,
        Avail: "14R",
        Cost: "4,500¥",
        Source: "SR5:R&G",
      },
      HorizonFlynnRapier: {
        Name: "Horizon-Flynn Rapier",
        Accuracy: 7,
        Reach: 1,
        DV: "2P",
        AP: -3,
        Avail: "9R",
        Cost: "500¥",
        Source: "SR5:R&G",
      },
      Katana: {
        Name: "Katana",
        Accuracy: 7,
        Reach: 1,
        DV: "3P",
        AP: -3,
        Avail: "9R",
        Cost: "1,000¥",
        Source: "Core",
      },
      Knife: {
        Name: "Knife",
        Accuracy: 5,
        Reach: "-",
        DV: "1P",
        AP: -1,
        Avail: "-",
        Cost: "10¥",
        Source: "Core",
      },
      LapelDagger: {
        Name: "Lapel Dagger",
        Accuracy: 4,
        Reach: "-",
        DV: "1P",
        AP: -1,
        Avail: 5,
        Cost: "100¥",
        Source: "SR5:CA",
      },
      MortimerOfLondonBelgraveSwordCane: {
        Name: "Mortimer of London Belgrave Sword Cane",
        Accuracy: 5,
        Reach: 1,
        DV: "3P",
        AP: -2,
        Avail: "8",
        Cost: "450¥",
        Source: "SR5:CA",
      },
      PlasteelKnife: {
        Name: "Plasteel Knife",
        Accuracy: 5,
        Reach: "-",
        DV: "2P",
        AP: -1,
        Avail: 4,
        Cost: "75¥",
        Source: "SR5:HT",
      },
      PoleArm: {
        Name: "Pole Arm",
        Accuracy: 5,
        Reach: 3,
        DV: "3P",
        AP: -2,
        Avail: "6R",
        Cost: "1,000¥",
        Source: "Core",
      },
      SapphireKnife: {
        Name: "Sapphire Knife",
        Accuracy: 5,
        Reach: "-",
        DV: "2P",
        AP: -3,
        Avail: "6R",
        Cost: "900¥",
        Source: "SR5:HT",
      },
      SurvivalKnife: {
        Name: "Survival Knife",
        Accuracy: 5,
        Reach: "-",
        DV: "2P",
        AP: -1,
        Avail: "-",
        Cost: "100¥",
        Source: "Core",
      },
      Sword: {
        Name: "Sword",
        Accuracy: 6,
        Reach: 1,
        DV: "3P",
        AP: -2,
        Avail: "5R",
        Cost: "500¥",
        Source: "Core",
      },
      VibroKnife: {
        Name: "Vibro Knife",
        Accuracy: 5,
        Reach: "-",
        DV: "2P",
        AP: -2,
        Avail: "6R",
        Cost: "1,000¥",
        Source: "SR5:SASS",
      },
      VibroSword: {
        Name: "Vibro Sword",
        Accuracy: 6,
        Reach: 1,
        DV: "4P",
        AP: -2,
        Avail: "8F",
        Cost: "2,000¥",
        Source: "SR5:S",
      },
    },
    exoticMeleeWeapons: {
      aresQueenOfHeartsMonofilamentGarrote: {
        Name: "Ares Queen of Hearts Monofilament Garrote",
        Accuracy: 5,
        Reach: "-",
        DV: "6P",
        AP: -8,
        Avail: "18F",
        Cost: "2,000¥",
        Source: "SR5:R&G",
      },
      ashArmsCombatChainsaw: {
        Name: "Ash Arms Combat Chainsaw",
        Accuracy: 5,
        Reach: 1,
        DV: "8P",
        AP: -4,
        Avail: "6R",
        Cost: "2,000¥",
        Source: "SR5:R&G",
      },
      ashArmsMonofilamentChainsaw: {
        Name: "Ash Arms Monofilament Chainsaw",
        Accuracy: 5,
        Reach: 1,
        DV: "12P",
        AP: -8,
        Avail: "8R",
        Cost: "7,500¥",
        Source: "SR5:R&G",
      },
      bullwhip: {
        Name: "Bullwhip",
        Accuracy: 6,
        Reach: 2,
        DV: "1P",
        AP: "+3",
        Avail: 6,
        Cost: "100¥",
        Source: "SR5:R&G",
      },
      collapsibleScythe: {
        Name: "Collapsible Scythe",
        Accuracy: 5,
        Reach: 2,
        DV: "2P",
        AP: -2,
        Avail: "16R",
        Cost: "2,350¥",
        Source: "SR5:HT",
      },
      garrote: {
        Name: "Garrote",
        Accuracy: 5,
        Reach: "-",
        DV: "4S",
        AP: -6,
        Avail: "-",
        Cost: "50¥",
        Source: "SR5:R&G",
      },
      monofilamentChainsaw: {
        Name: "Monofilament Chainsaw",
        Accuracy: 3,
        Reach: 1,
        DV: "8P",
        AP: -6,
        Avail: 8,
        Cost: "500¥",
        Source: "Core",
      },
      monofilamentWhip: {
        Name: "Monofilament Whip",
        Accuracy: "5 (7)",
        Reach: 2,
        DV: "12P",
        AP: -8,
        Avail: "12R",
        Cost: "10,000¥",
        Source: "Core",
      },
    },
    throwingWeapons: {
      boomerang: {
        Name: "Boomerang",
        Accuracy: "Physical-1",
        DV: "2P",
        AP: "-",
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: 4,
        Cost: "50¥",
        Source: "SR5:R&G",
      },
      cavalierArmsUrbanTribeTomahawk: {
        Name: "Cavalier Arms Urban Tribe Tomahawk",
        Accuracy: "Physical+1",
        DV: "2P",
        AP: -1,
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: 4,
        Cost: "200¥",
        Source: "SR5:R&G",
      },
      harpoon: {
        Name: "Harpoon",
        Accuracy: "Physical",
        DV: "3P",
        AP: -1,
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: 6,
        Cost: "125¥",
        Source: "SR5:R&G",
      },
      javelin: {
        Name: "Javelin",
        Accuracy: "Physical",
        DV: "3P",
        AP: -1,
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: 6,
        Cost: "125¥",
        Source: "SR5:R&G",
      },
      shuriken: {
        Name: "Shuriken",
        Accuracy: "Physical",
        DV: "1P",
        AP: -1,
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: "4R",
        Cost: "25¥",
        Source: "Core",
      },
      throwingKnife: {
        Name: "Throwing Knife",
        Accuracy: "Physical",
        DV: "1P",
        AP: -1,
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: "4R",
        Cost: "25¥",
        Source: "Core",
      },
    },
    ballisticProjectiles: {
      aquadyneSharkXSHarpoonGun: {
        Name: "Aquadyne Shark-XS Harpoon Gun",
        Accuracy: 5,
        DV: "9P",
        AP: -2,
        Modes: "SS",
        RC: "-",
        Ammo: "5 (m)",
        Avail: "8R",
        Cost: "800¥",
        Source: "SR5:R&G",
      },
      aresGiantslayerSlingshot: {
        Name: "Ares Giantslayer Slingshot",
        Accuracy: 7,
        DV: "2P",
        AP: "-",
        Modes: "SS",
        RC: "-",
        Ammo: "-",
        Avail: "-",
        Cost: "50¥",
        Source: "SR5:R&G",
      },
      bow: {
        Name: "Bow",
        Accuracy: 6,
        DV: "(Rating+2)P",
        AP: "-(Rating/4)",
        Modes: "-",
        RC: "-",
        Ammo: "Rating",
        Avail: "Rating",
        Cost: "Rating×100¥",
        Source: "Core",
      },
      lightCrossbow: {
        Name: "Light Crossbow",
        Accuracy: 7,
        DV: "5P",
        AP: -1,
        Modes: "-",
        RC: "-",
        Ammo: "4 (m)",
        Avail: 2,
        Cost: "300¥",
        Source: "Core",
      },
      mediumCrossbow: {
        Name: "Medium Crossbow",
        Accuracy: 6,
        DV: "7P",
        AP: -2,
        Modes: "-",
        RC: "-",
        Ammo: "4 (m)",
        Avail: "4R",
        Cost: "500¥",
        Source: "Core",
      },
      heavyCrossbow: {
        Name: "Heavy Crossbow",
        Accuracy: 5,
        DV: "10P",
        AP: -3,
        Modes: "-",
        RC: "-",
        Ammo: "4 (m)",
        Avail: "8R",
        Cost: "1,000¥",
        Source: "Core",
      },
      dynamicTensionBow: {
        Name: "Dynamic Tension Bow",
        Accuracy: 5,
        DV: "(Rating+2)P",
        AP: "-(Rating/4)",
        Modes: "-",
        RC: "-",
        Ammo: "12",
        Avail: "-",
        Cost: "1,200¥",
        Source: "SR5:HT",
      },
      harpoonGun: {
        Name: "Harpoon Gun",
        Accuracy: 5,
        DV: "9P",
        AP: -2,
        Modes: "SS",
        RC: "-",
        Ammo: "1",
        Avail: "6R",
        Cost: "200¥",
        Source: "SR5:R&G",
      },
      rangerSliverPistolCrossbow: {
        Name: "Ranger Sliver Pistol Crossbow",
        Accuracy: 7,
        DV: "4P",
        AP: "-",
        Modes: "SS",
        RC: "-",
        Ammo: "-",
        Avail: "6R",
        Cost: "300¥",
        Source: "SR5:R&G",
      },
    },
    flamethrowers: {
      shiawaseArmsBlazer: {
        Name: "Shiawase Arms Blazer",
        Accuracy: 6,
        DV: "10P",
        AP: -6,
        Modes: "SA/BF/FA",
        RC: "-",
        Ammo: "4 (c)",
        Avail: "16F",
        Cost: "2,200¥",
        Source: "SR5:R&G",
      },
      shiawaseArmsIncinerator: {
        Name: "Shiawase Arms Incinerator",
        Accuracy: 4,
        DV: "12P",
        AP: -6,
        Modes: "SS",
        RC: "-",
        Ammo: "6 (c)",
        Avail: "12F",
        Cost: "10,000¥",
        Source: "SR5:GH3",
      },
    },
    exoticRangedWeapons: {
      blowgun: {
        Name: "Blowgun",
        Accuracy: 8,
        DV: "1P",
        AP: "-",
        Modes: "SS",
        RC: "-",
        Ammo: "1 (ml)",
        Avail: 4,
        Cost: "15¥",
        Source: "SR5:R&G",
      },
      bola: {
        Name: "Bola",
        Accuracy: "Physical",
        DV: "3S",
        AP: "+4",
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: 6,
        Cost: "75¥",
        Source: "SR5:R&G",
      },
      flameBracer: {
        Name: "Flame Bracer",
        Accuracy: 4,
        DV: "6P(fire)",
        AP: -6,
        Modes: "SS",
        RC: "-",
        Ammo: "2 (c)",
        Avail: "8F",
        Cost: "775¥",
        Source: "SR5:HT",
      },
      grappleGun: {
        Name: "Grapple Gun",
        Accuracy: 3,
        DV: "7S",
        AP: -2,
        Modes: "SS",
        RC: "-",
        Ammo: "1 (ml)",
        Avail: "8R",
        Cost: "500¥",
        Source: "Core",
      },
      monofilamentBola: {
        Name: "Monofilament Bola",
        Accuracy: "Physical",
        DV: "3S / 12P",
        AP: "+4 / -8",
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: "18F",
        Cost: "4,000¥",
        Source: "SR5:R&G",
      },
      net: {
        Name: "Net",
        Accuracy: "Physical-2",
        DV: "-",
        AP: "-",
        Modes: "-",
        RC: "-",
        Ammo: "-",
        Avail: 6,
        Cost: "350¥",
        Source: "SR5:R&G",
      },
      netGunBasic: {
        Name: "Net Gun, Basic",
        Accuracy: 5,
        DV: "-",
        AP: "-",
        Modes: "SS",
        RC: "-",
        Ammo: "4 (b)",
        Avail: 9,
        Cost: "750¥",
        Source: "SR5:R&G",
      },
    },
    lightPistols: {
      aresLightFire70: {
        Name: "Ares Light Fire 70",
        Accuracy: 7,
        DV: "8P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "16 (c)",
        Avail: "3R",
        Cost: "200¥",
        Source: "Core",
      },
      aresLightFire75: {
        Name: "Ares Light Fire 75",
        Accuracy: "6 (8)",
        DV: "6P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "16 (c)",
        Avail: "6F",
        Cost: "1,250¥",
        Source: "Core",
      },
      beretta201T: {
        Name: "Beretta 201T",
        Accuracy: 6,
        DV: "6P",
        AP: "-",
        Modes: "SA/BF",
        RC: "- (1)",
        Ammo: "21 (c)",
        Avail: "7R",
        Cost: "210¥",
        Source: "Core",
      },
      cavalierArmsAdderSlivergun: {
        Name: "Cavalier Arms Adder Slivergun",
        Accuracy: 5,
        DV: "8P(f)",
        AP: "+5",
        Modes: "SA",
        RC: "-",
        Ammo: "20 (c)",
        Avail: "7F",
        Cost: "320¥",
        Source: "SR5:HT",
      },
      coltAgentSpecial: {
        Name: "Colt Agent Special",
        Accuracy: 5,
        DV: "8P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "8 (c)",
        Avail: "5R",
        Cost: "250¥",
        Source: "SR5:GH3",
      },
      coltAmericaL36: {
        Name: "Colt America L36",
        Accuracy: 7,
        DV: "7P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "11 (c)",
        Avail: "4R",
        Cost: "320¥",
        Source: "Core",
      },
      fichettiExecutiveAction: {
        Name: "Fichetti Executive Action",
        Accuracy: 6,
        DV: "7P",
        AP: "-",
        Modes: "SA/BF",
        RC: "-",
        Ammo: "18 (c)",
        Avail: "10R",
        Cost: "300¥",
        Source: "SR5:R&G",
      },
      fichettiSecurity600: {
        Name: "Fichetti Security 600",
        Accuracy: "6 (7)",
        DV: "7P",
        AP: "-",
        Modes: "SA",
        RC: "- (1)",
        Ammo: "30 (c)",
        Avail: "6R",
        Cost: "350¥",
        Source: "Core",
      },
      nitamaSporter: {
        Name: "Nitama Sporter",
        Accuracy: "6 (7)",
        DV: "6P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "18 (c)",
        Avail: "10R",
        Cost: "300¥",
        Source: "SR5:R&G",
      },
      shiawaseArmamentsPuzzler: {
        Name: "Shiawase Armaments Puzzler",
        Accuracy: 4,
        DV: "6P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "12 (c)",
        Avail: "14R",
        Cost: "900¥",
        Source: "SR5:R&G",
      },
      taurusOmni6LightPistolRounds: {
        Name: "Taurus Omni-6, light pistol rounds",
        Accuracy: "5 (6)",
        DV: "6P",
        AP: "-",
        Modes: "SA",
        RC: "-",
        Ammo: "6 (cy)",
        Avail: "3R",
        Cost: "300¥",
        Source: "Core",
      },
      taurusOmni6HeavyPistolRounds: {
        Name: "Taurus Omni-6, heavy pistol rounds",
        Accuracy: "5 (6)",
        DV: "7P",
        AP: "-1",
        Modes: "SS",
        RC: "-",
        Ammo: "6 (cy)",
        Avail: "3R",
        Cost: "300¥",
        Source: "Core",
      },
    },
    submachineGuns: {
      aresExecutioner: {
        Name: "Ares Executioner",
        Accuracy: "4 (6)",
        DV: "7P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "- (1)",
        Ammo: "30 (c)",
        Avail: "14F",
        Cost: "1,000¥",
        Source: "SR5:R&G",
      },
      aresSigma3: {
        Name: "Ares Sigma-3",
        Accuracy: "4 (6)",
        DV: "8P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "- (2)",
        Ammo: "50 (d)",
        Avail: "7R",
        Cost: "1,000¥",
        Source: "SR5:GH3",
      },
      cavalierArmsGladius: {
        Name: "Cavalier Arms Gladius",
        Accuracy: "3 (4)",
        DV: "7P",
        AP: "-",
        Modes: "BF/FA",
        RC: "1 (2)",
        Ammo: "32 (c)",
        Avail: "6R",
        Cost: "400¥",
        Source: "SR5:GH3",
      },
      coltCobraTZ120: {
        Name: "Colt Cobra TZ-120",
        Accuracy: "4 (5)",
        DV: "7P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "2 (3)",
        Ammo: "32 (c)",
        Avail: "5R",
        Cost: "660¥",
        Source: "Core",
      },
      fnP93Praetor: {
        Name: "FN P93 Praetor",
        Accuracy: 6,
        DV: "8P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "1 (2)",
        Ammo: "50 (c)",
        Avail: "11F",
        Cost: "900¥",
        Source: "Core",
      },
      hk227: {
        Name: "HK-227",
        Accuracy: "5 (7)",
        DV: "7P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "- (1)",
        Ammo: "28 (c)",
        Avail: "8R",
        Cost: "730¥",
        Source: "Core",
      },
      hkUrbanCombat: {
        Name: "HK Urban Combat",
        Accuracy: "7 (9)",
        DV: "8P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "2",
        Ammo: "36 (c)",
        Avail: "16F",
        Cost: "2,300¥",
        Source: "SR5:R&G",
      },
      hkXM30Carbine: {
        Name: "HK XM30, Carbine",
        Accuracy: "6 (8)",
        DV: "9P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "- (1)",
        Ammo: "30 (c)",
        Avail: "15F",
        Cost: "4,500¥",
        Source: "SR5:R&G",
      },
      ingramSmartgunX: {
        Name: "Ingram Smartgun X",
        Accuracy: "4 (6)",
        DV: "8P",
        AP: "-",
        Modes: "BF/FA",
        RC: "2",
        Ammo: "32 (c)",
        Avail: "6R",
        Cost: "800¥",
        Source: "Core",
      },
      krimeSpree: {
        Name: "Krime Spree",
        Accuracy: 4,
        DV: "7P",
        AP: "-",
        Modes: "FA",
        RC: "1",
        Ammo: "30 (c)",
        Avail: "6R",
        Cost: "425¥",
        Source: "SR5:GH3",
      },
      sckModel100: {
        Name: "SCK Model 100",
        Accuracy: "5 (7)",
        DV: "8P",
        AP: "-",
        Modes: "SA/BF",
        RC: "- (1)",
        Ammo: "30 (c)",
        Avail: "6R",
        Cost: "875¥",
        Source: "Core",
      },
      uziIV: {
        Name: "Uzi IV",
        Accuracy: "4 (5)",
        DV: "7P",
        AP: "-",
        Modes: "BF",
        RC: "- (1)",
        Ammo: "24 (c)",
        Avail: "4R",
        Cost: "450¥",
        Source: "Core",
      },

      ak97: {
        Name: "AK-97",
        Accuracy: 4,
        DV: "10P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "-",
        Ammo: "38 (c)",
        Avail: "4R",
        Cost: "950¥",
        Source: "Core",
      },
      ak98: {
        Name: "AK-98",
        Accuracy: 5,
        DV: "10P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "-",
        Ammo: "38 (c)",
        Avail: "8F",
        Cost: "1,250¥",
        Source: "SR5:R&G",
      },
      aresAlpha: {
        Name: "Ares Alpha",
        Accuracy: "5 (7)",
        DV: "11P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "2",
        Ammo: "42 (c)",
        Avail: "11F",
        Cost: "2,650¥",
        Source: "Core",
      },
      aresHvar: {
        Name: "Ares HVAR",
        Accuracy: "5 (7)",
        DV: "8P",
        AP: "-",
        Modes: "SA/BF/FA",
        RC: "3 (4)",
        Ammo: "50 (c)",
        Avail: "11F",
        Cost: "2,400¥",
        Source: "SR5:R&G",
      },
      coltInception: {
        Name: "Colt Inception",
        Accuracy: "7 (8)",
        DV: "10P",
        AP: "-1",
        Modes: "SA/BF",
        RC: "1 (3)",
        Ammo: "35 (c)",
        Avail: "11R",
        Cost: "2,250¥",
        Source: "SR5:GH3",
      },
      coltM23: {
        Name: "Colt M23",
        Accuracy: 4,
        DV: "9P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "-",
        Ammo: "40 (c)",
        Avail: "4R",
        Cost: "550¥",
        Source: "Core",
      },
      fnHar: {
        Name: "FN HAR",
        Accuracy: "5 (6)",
        DV: "10P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "2",
        Ammo: "35 (c)",
        Avail: "8R",
        Cost: "1,500¥",
        Source: "Core",
      },
      hkXm30AssaultRifle: {
        Name: "HK XM30, Assault Rifle",
        Accuracy: "6 (8)",
        DV: "9P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "- (1)",
        Ammo: "30 (c)",
        Avail: "15F",
        Cost: "4,500¥",
        Source: "SR5:R&G",
      },
      kruppArmsKriegfaust: {
        Name: "Krupp Arms Kriegfaust",
        Accuracy: 8,
        DV: "9P",
        AP: "-1",
        Modes: "SA/BF",
        RC: "1",
        Ammo: "25 (d)",
        Avail: "10R",
        Cost: "1,300¥",
        Source: "SR5:GH3",
      },
      nissanOptimumII: {
        Name: "Nissan Optimum II",
        Accuracy: "5 (7)",
        DV: "9P",
        AP: "-2",
        Modes: "SA/BF/FA",
        RC: "1",
        Ammo: "30 (c)",
        Avail: "10F",
        Cost: "2,300¥",
        Source: "SR5:R&G",
      },
      sbd44: {
        Name: "SBD-44",
        Accuracy: 3,
        DV: "10P",
        AP: "-1",
        Modes: "SA/BF/FA",
        RC: "-",
        Ammo: "32 (c)",
        Avail: "4R",
        Cost: "500¥",
        Source: "SR5:GH3",
      },
      shiawaseArmsMonsoon: {
        Name: "Shiawase Arms Monsoon",
        Accuracy: 5,
        DV: "10P",
        AP: "-1",
        Modes: "SA/BF",
        RC: "1",
        Ammo: "20 (ml)×6",
        Avail: "10F",
        Cost: "1,900¥",
        Source: "SR5:GH3",
      },
      ultimaxRainForestCarbine: {
        Name: "Ultimax Rain Forest Carbine",
        Accuracy: 7,
        DV: "14P",
        AP: "-4",
        Modes: "SA",
        RC: "- (1)",
        Ammo: "18 (c)",
        Avail: "5R",
        Cost: "2,800¥",
        Source: "SR5:GH3",
      },
    },
    sniperRifles: {
      aresDesertStrike: {
        Name: "Ares Desert Strike",
        Accuracy: 7,
        DV: "13P",
        AP: "-4",
        Modes: "SA",
        RC: "- (1)",
        Ammo: "14 (c)",
        Avail: "10F",
        Cost: "17,500¥",
        Source: "Core",
      },
      barretModel122: {
        Name: "Barret Model 122",
        Accuracy: "7 (9)",
        DV: "14P",
        AP: "-6",
        Modes: "SA",
        RC: "- (2)",
        Ammo: "14 (c)",
        Avail: "20F",
        Cost: "38,500¥",
        Source: "SR5:R&G",
      },
      cavalierArmsCrockettEBR: {
        Name: "Cavalier Arms Crockett EBR",
        Accuracy: 6,
        DV: "12P",
        AP: "-3",
        Modes: "SA/BF",
        RC: "- (1)",
        Ammo: "20 (c)",
        Avail: "12F",
        Cost: "10,300¥",
        Source: "Core",
      },
      hkXM30Sniper: {
        Name: "HK XM30, Sniper",
        Accuracy: "7 (9)",
        DV: "9P",
        AP: "-2",
        Modes: "SA",
        RC: "2 (3)",
        Ammo: "10 (c)",
        Avail: "15F",
        Cost: "4,500¥",
        Source: "SR5:R&G",
      },
      onotariJpK50: {
        Name: "Onotari JP-K50",
        Accuracy: 7,
        DV: "12P",
        AP: "-3",
        Modes: "SA/BF",
        RC: "1",
        Ammo: "24 (c)",
        Avail: "13F",
        Cost: "12,500¥",
        Source: "SR5:R&G",
      },
      pioneer60: {
        Name: "Pioneer 60",
        Accuracy: 5,
        DV: "10P",
        AP: "-1",
        Modes: "SA",
        RC: "-",
        Ammo: "5 (m)",
        Avail: "2R",
        Cost: "500¥",
        Source: "SR5:R&G",
      },
      rangerArmsSM5: {
        Name: "Ranger Arms SM-5",
        Accuracy: 8,
        DV: "14P",
        AP: "-5",
        Modes: "SA",
        RC: "- (1)",
        Ammo: "15 (c)",
        Avail: "16F",
        Cost: "28,000¥",
        Source: "Core",
      },
      remington950: {
        Name: "Remington 950",
        Accuracy: 7,
        DV: "12P",
        AP: "-4",
        Modes: "SS",
        RC: "-",
        Ammo: "5 (m)",
        Avail: "4R",
        Cost: "2,100¥",
        Source: "Core",
      },
      ruger100: {
        Name: "Ruger 100",
        Accuracy: 6,
        DV: "11P",
        AP: "-3",
        Modes: "SS",
        RC: "- (1)",
        Ammo: "8 (m)",
        Avail: "4R",
        Cost: "1,300¥",
        Source: "Core",
      },
      terracottaArmsAM47: {
        Name: "Terracotta ARMS AM-47",
        Accuracy: "7 (9)",
        DV: "15P",
        AP: "-4",
        Modes: "SA",
        RC: "1 (3)",
        Ammo: "18 (c)",
        Avail: "14F",
        Cost: "35,000¥",
        Source: "SR5:R&G",
      },
    },
    sportingRifles: {
      m1Garand: {
        Name: "M1 Garand",
        Accuracy: 5,
        DV: "12P",
        AP: "-1",
        Modes: "SA",
        RC: "-",
        Ammo: "8 (c)",
        Avail: "3R",
        Cost: "1,100¥",
        Source: "SR5:GH3",
      },
      marlin79S: {
        Name: "Marlin 79S",
        Accuracy: 4,
        DV: "6P",
        AP: "–",
        Modes: "SA",
        RC: "-",
        Ammo: "10 (c)",
        Avail: "3R",
        Cost: "300¥",
        Source: "SR5:GH3",
      },
      marlin3041BL: {
        Name: "Marlin 3041 BL",
        Accuracy: 5,
        DV: "10P",
        AP: "-3",
        Modes: "SA",
        RC: "-",
        Ammo: "6 (m)",
        Avail: "5R",
        Cost: "1,100¥",
        Source: "SR5:GH3",
      },
      marlin3468SS: {
        Name: "Marlin 3468SS",
        Accuracy: 4,
        DV: "13P",
        AP: "-1",
        Modes: "SS",
        RC: "-",
        Ammo: "4 (m)",
        Avail: "6R",
        Cost: "1,000¥",
        Source: "SR5:GH3",
      },
      marlinX71: {
        Name: "Marlin X71",
        Accuracy: 5,
        DV: "12P",
        AP: "-4",
        Modes: "SS",
        RC: "-",
        Ammo: "5 (m)",
        Avail: "6R",
        Cost: "1,500¥",
        Source: "SR5:GH3",
      },
      springfieldModel1855Reproduction: {
        Name: "Springfield Model 1855 Reproduction",
        Accuracy: 2,
        DV: "10P",
        AP: "–",
        Modes: "SS",
        RC: "-",
        Ammo: "1 (cb)",
        Avail: "4R",
        Cost: "850¥",
        Source: "SR5:GH3",
      },
      springfield2003: {
        Name: "Springfield 2003",
        Accuracy: 9,
        DV: "12P",
        AP: "-2",
        Modes: "SS",
        RC: "-",
        Ammo: "5 (m)",
        Avail: "4R",
        Cost: "3,600¥",
        Source: "SR5:GH3",
      },
      springfieldM1A: {
        Name: "Springfield M1A",
        Accuracy: 6,
        DV: "12P",
        AP: "-1",
        Modes: "SA",
        RC: "-",
        Ammo: "20 (c)",
        Avail: "6R",
        Cost: "1,700¥",
        Source: "SR5:GH3",
      },
      winchesterModel2024: {
        Name: "Winchester Model 2024",
        Accuracy: 6,
        DV: "12P",
        AP: "–",
        Modes: "SA",
        RC: "-",
        Ammo: "7 (m)",
        Avail: "4R",
        Cost: "1,800¥",
        Source: "SR5:GH3",
      },
      winchesterModel2067: {
        Name: "Winchester Model 2067",
        Accuracy: 5,
        DV: "8P",
        AP: "-1",
        Modes: "SA",
        RC: "-",
        Ammo: "15 (m)",
        Avail: "4R",
        Cost: "650¥",
        Source: "SR5:GH3",
      },
    },
    shotguns: {
      autoAssault16: {
        Name: "Auto-Assault 16",
        Accuracy: 4,
        DV: "13P",
        AP: "-1",
        Modes: "SA/BF/FA",
        RC: "2",
        Ammo: "10 (c) or 32 (d)",
        Avail: "18F",
        Cost: "1,800¥",
        Source: "SR5:R&G",
      },
      cavalierFalchion: {
        Name: "Cavalier Falchion",
        Accuracy: "5 (7)",
        DV: "12P",
        AP: "-1",
        Modes: "SS",
        RC: "–",
        Ammo: "8 (m)",
        Avail: "9R",
        Cost: "1,200¥",
        Source: "SR5:GH3",
      },
      defianceT250: {
        Name: "Defiance T-250",
        Accuracy: 4,
        DV: "10P",
        AP: "-1",
        Modes: "SS/SA",
        RC: "–",
        Ammo: "5 (m)",
        Avail: "4R",
        Cost: "450¥",
        Source: "Core",
      },
    },
    lightMachineGuns: {
      geVindicatorMiniGun: {
        Name: "GE Vindicator Mini-Gun",
        Accuracy: "4 (6)",
        DV: "9P",
        AP: "-4",
        Modes: "FA",
        RC: "2",
        Ammo: "200 (belt)",
        Avail: "24F",
        Cost: "6,000¥",
        Source: "SR5:R&G",
      },
      hkXM30LMG: {
        Name: "HK XM30, LMG",
        Accuracy: "6 (8)",
        DV: "9P",
        AP: "-2",
        Modes: "BF/FA",
        RC: "2 (3)",
        Ammo: "100 (belt)",
        Avail: "15F",
        Cost: "4,500¥",
        Source: "SR5:R&G",
      },
      ingramValiant: {
        Name: "Ingram Valiant",
        Accuracy: "5 (6)",
        DV: "9P",
        AP: "-2",
        Modes: "BF/FA",
        RC: "2 (3)",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "12F",
        Cost: "5,800¥",
        Source: "Core",
      },
      krimeWave: {
        Name: "Krime Wave",
        Accuracy: 5,
        DV: "10P",
        AP: "-2",
        Modes: "FA",
        RC: "– (2)",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "11F",
        Cost: "2,000¥",
        Source: "SR5:GH3",
      },
      shiawaseArmsNemesis: {
        Name: "Shiawase Arms Nemesis",
        Accuracy: "5 (7)",
        DV: "9P",
        AP: "-2",
        Modes: "BF/FA",
        RC: "2",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "16F",
        Cost: "6,500¥",
        Source: "SR5:R&G",
      },
    },
    heavyMachineGuns: {
      fnMag5: {
        Name: "FN Mag-5",
        Accuracy: "4 (5)",
        DV: "11P",
        AP: "-3",
        Modes: "FA",
        RC: "2 (8)",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "18F",
        Cost: "8,500¥",
        Source: "SR5:R&G",
      },
      rpkHmg: {
        Name: "RPK HMG",
        Accuracy: "5",
        DV: "12P",
        AP: "-4",
        Modes: "FA",
        RC: "– (6)",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "16F",
        Cost: "16,300¥",
        Source: "Core",
      },
      ruhrmetallSf20: {
        Name: "Ruhrmetall SF-20",
        Accuracy: "5 (6)",
        DV: "12P",
        AP: "-4",
        Modes: "FA",
        RC: "1 (4)",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "18F",
        Cost: "19,600¥",
        Source: "SR5:R&G",
      },
      ultamaxHmg2: {
        Name: "Ultamax HMG-2",
        Accuracy: "4 (5)",
        DV: "11P",
        AP: "-4",
        Modes: "FA",
        RC: "6",
        Ammo: "50 (c) or 100 (belt)",
        Avail: "16F",
        Cost: "16,000¥",
        Source: "SR5:R&G",
      },
    },
    exoticFirearms: {
      aresArmatus: {
        Name: "Ares Armatus",
        Accuracy: "6",
        DV: "6P",
        AP: "-5",
        Modes: "SA",
        RC: "–",
        Ammo: "10 (c)",
        Avail: "20F",
        Cost: "19,000¥",
        Source: "SR5:HT",
      },
      aresSIII: {
        Name: "Ares S-III Super Squirt",
        Accuracy: "3",
        DV: "Chemical",
        AP: "SA",
        Modes: "–",
        RC: "20 (c)",
        Ammo: "7R",
        Avail: "950¥",
        Cost: "Core",
      },
      aresScreech: {
        Name: "Ares Screech Sonic Rifle",
        Accuracy: "6",
        DV: "7S",
        AP: "Spec.",
        Modes: "SS",
        RC: "–",
        Ammo: "10 (c)",
        Avail: "16R",
        Cost: "8,000¥",
        Source: "SR5:R&G",
      },
      fichettiPainInducer: {
        Name: "Fichetti Pain Inducer",
        Accuracy: "3",
        DV: "Spec.",
        AP: "–",
        Modes: "SS",
        RC: "–",
        Ammo: "Spec.",
        Avail: "11R",
        Cost: "5,000¥",
        Source: "Core",
      },
      fnAALGyrojet: {
        Name: "FN-AAL Gyrojet Pistol",
        Accuracy: "5",
        DV: "10P",
        AP: "-2",
        Modes: "SA",
        RC: "–",
        Ammo: "10 (c)",
        Avail: "12F",
        Cost: "2,000¥",
        Source: "SR5:R&G",
      },
      gunCaneKnockoff: {
        Name: "Gun Cane, Knockoff",
        Accuracy: "5",
        DV: "9P",
        AP: "–",
        Modes: "SS",
        RC: "–",
        Ammo: "–",
        Avail: "6R",
        Cost: "150¥",
        Source: "SR5:R&G",
      },
      gunCaneTrafalgar: {
        Name: "Gun Cane, Trafalgar",
        Accuracy: "6",
        DV: "7P",
        AP: "–",
        Modes: "SS",
        RC: "–",
        Ammo: "1 (b)",
        Avail: "9R",
        Cost: "750¥",
        Source: "SR5:R&G",
      },
      parashieldDartPistol: {
        Name: "Parashield Dart Pistol",
        Accuracy: "5",
        DV: "Drug/Toxin",
        AP: "SA",
        Modes: "–",
        RC: "5 (c)",
        Ammo: "4R",
        Avail: "600¥",
        Cost: "Core",
      },
      parashieldDartRifle: {
        Name: "Parashield Dart Rifle",
        Accuracy: "6",
        DV: "Drug/Toxin",
        AP: "SA",
        Modes: "–",
        RC: "6 (m)",
        Ammo: "6R",
        Avail: "1,200¥",
        Cost: "Core",
      },
      shiawaseArmsSimoom: {
        Name: "Shiawase Arms Simoom",
        Accuracy: "5",
        DV: "6P",
        AP: "–",
        Modes: "SA/FA",
        RC: "–",
        Ammo: "6 (ml)",
        Avail: "14R",
        Cost: "1,500¥",
        Source: "SR5:HT",
      },
      tiffaniElegance: {
        Name: "Tiffani Élégance Shooting Bracer",
        Accuracy: "5 (6)",
        DV: "7P",
        AP: "–",
        Modes: "SS",
        RC: "–",
        Ammo: "1 (b)",
        Avail: "10R",
        Cost: "1,250¥",
        Source: "SR5:R&G",
      },
    },
    lasers: {
      aresArchonHeavyMPLaser: {
        Name: "Ares Archon Heavy MP Laser",
        Accuracy: "7",
        DV: "10P",
        AP: "-10",
        Modes: "SA",
        RC: "–",
        Ammo: "External Source",
        Avail: "24F",
        Cost: "35,000¥",
        Source: "SR5:R&G",
      },
      aresLancerMPLaser: {
        Name: "Ares Lancer MP Laser",
        Accuracy: "7",
        DV: "7P",
        AP: "-10",
        Modes: "SA",
        RC: "–",
        Ammo: "2×10 (c) or External Source",
        Avail: "18F",
        Cost: "16,000¥",
        Source: "SR5:R&G",
      },
      aresRedlineLaser: {
        Name: "Ares Redline Laser",
        Accuracy: "9",
        DV: "5P",
        AP: "-10",
        Modes: "SA",
        RC: "–",
        Ammo: "10 (c) or External Source",
        Avail: "14F",
        Cost: "7,500¥",
        Source: "SR5:R&G",
      },
    },
    assaultCannons: {
      aresThunderstruckGaussRifle: {
        Name: "Ares Thunderstruck Gauss Rifle",
        Accuracy: "7 (8)",
        DV: "15P",
        AP: "-8",
        Modes: "SA",
        RC: "– (1)",
        Ammo: "10 (c) + Energy",
        Avail: "12F",
        Cost: "26,000¥",
        Source: "SR5:R&G",
      },
      aresVigorousAssaultCannon: {
        Name: "Ares Vigorous Assault Cannon",
        Accuracy: "4",
        DV: "16P",
        AP: "-6",
        Modes: "SS",
        RC: "–",
        Ammo: "12 (c)",
        Avail: "18F",
        Cost: "24,500¥",
        Source: "SR5:R&G",
      },
      krimeBomb: {
        Name: "Krime Bomb",
        Accuracy: "6 (7)",
        DV: "16P",
        AP: "-6",
        Modes: "SS",
        RC: "–",
        Ammo: "4 (m)",
        Avail: "20F",
        Cost: "23,000¥",
        Source: "SR5:GH3",
      },
      krimeCannon: {
        Name: "Krime Cannon",
        Accuracy: "4",
        DV: "16P",
        AP: "-6",
        Modes: "SA",
        RC: "– (1)",
        Ammo: "6 (m)",
        Avail: "20F",
        Cost: "21,000¥",
        Source: "Core",
      },
      ogreHammerSWSAssaultCannon: {
        Name: "Ogre Hammer SWS Assault Cannon",
        Accuracy: "6",
        DV: "16P",
        AP: "-4",
        Modes: "SA",
        RC: "–",
        Ammo: "6 (c)",
        Avail: "20F",
        Cost: "32,000¥",
        Source: "SR5:R&G",
      },
      pantherXXL: {
        Name: "Panther XXL",
        Accuracy: "5 (7)",
        DV: "17P",
        AP: "-6",
        Modes: "SA",
        RC: "–",
        Ammo: "15 (c)",
        Avail: "20F",
        Cost: "43,000¥",
        Source: "Core",
      },
    },
    missileLaunchers: {
      aztechnologyStriker: {
        Name: "Aztechnology Striker",
        Accuracy: "5",
        DV: "Missile",
        AP: "SS",
        Modes: "–",
        RC: "2 (ml)",
        Ammo: "10F",
        Avail: "1,200¥",
        Cost: "Core",
      },
      mitsubishiYakusokuMRL: {
        Name: "Mitsubishi Yakusoku MRL",
        Accuracy: "Missile",
        DV: "SA/BF",
        AP: "–",
        Modes: "4×2 (m)",
        RC: "–",
        Ammo: "20F",
        Avail: "14,000¥",
        Cost: "SR5:R&G",
      },
      onotariArmsBallistaMML: {
        Name: "Onotari Arms Ballista MML",
        Accuracy: "Missile",
        DV: "SS",
        AP: "–",
        Modes: "4 (m)",
        RC: "–",
        Ammo: "19F",
        Avail: "7,500¥",
        Cost: "SR5:R&G",
      },
      onotariInterceptor: {
        Name: "Onotari Interceptor",
        Accuracy: "4 (6)",
        DV: "Missile",
        AP: "SS",
        Modes: "–",
        RC: "2 (ml)",
        Ammo: "18F",
        Avail: "14,000¥",
        Cost: "Core",
      },
    },
    implantMeleeWeapons: {
      cyberHandBlade: {
        Weapon: "Cyber Hand Blade",
        Accuracy: "Physical",
        Reach: "–",
        DV: "2P",
        AP: "-2",
        Avail: "10F",
        Cost: "2,500¥",
        Source: "Core",
      },
      cyberHandRazors: {
        Weapon: "Cyber Hand Razors",
        Accuracy: "Physical",
        Reach: "–",
        DV: "1P",
        AP: "-3",
        Avail: "8F",
        Cost: "1,250¥",
        Source: "Core",
      },
      cyberShockHand: {
        Weapon: "Cyber Shock Hand",
        Accuracy: "Physical",
        Reach: "–",
        DV: "9S(e)",
        AP: "-5",
        Avail: "8R",
        Cost: "5,000¥",
        Source: "Core",
      },
      cyberSpurs: {
        Weapon: "Cyber Spurs",
        Accuracy: "Physical",
        Reach: "–",
        DV: "3P",
        AP: "-2",
        Avail: "12F",
        Cost: "5,000¥",
        Source: "Core",
      },
      extremeCyberImplant: {
        Weapon: "Extreme Cyber-Implant",
        Accuracy: "Physical",
        Reach: "1",
        DV: "5P",
        AP: "–",
        Avail: "8F",
        Cost: "2,000¥",
        Source: "SR5:CF",
      },
      fangs: {
        Weapon: "Fangs",
        Accuracy: "Physical",
        Reach: "–",
        DV: "(STR)P",
        AP: "–",
        Avail: "6",
        Cost: "200¥",
        Source: "SR5:CF",
      },
      retractableFangs: {
        Weapon: "Fangs, retractable",
        Accuracy: "Physical",
        Reach: "–",
        DV: "(STR)P",
        AP: "–",
        Avail: "8",
        Cost: "500¥",
        Source: "SR5:CF",
      },
      junkyardJaw: {
        Weapon: "Junkyard Jaw",
        Accuracy: "Physical",
        Reach: "–",
        DV: "3P",
        AP: "-6",
        Avail: "8F",
        Cost: "2,000¥",
        Source: "SR5:CF",
      },
      oralSlasher: {
        Weapon: "Oral Slasher",
        Accuracy: "Physical",
        Reach: "1",
        DV: "6P",
        AP: "-3",
        Avail: "12R",
        Cost: "750¥",
        Source: "SR5:CF",
      },
    },
    implantFirearms: {
      cyberHoldOutPistol: {
        Weapon: "Cyber Hold-Out Pistol",
        Accuracy: "4 (6)",
        DV: "6P",
        AP: "–",
        Modes: "SA",
        RC: "–",
        Ammo: "2 (m) / 6 (c)",
        Avail: "8R",
        Cost: "2,000¥",
        Source: "Core",
      },
      cyberMachinePistol: {
        Weapon: "Cyber Machine Pistol",
        Accuracy: "4 (6)",
        DV: "6P",
        AP: "–",
        Modes: "SA/FA",
        RC: "1",
        Ammo: "18 (m) / 32 (c)",
        Avail: "12R",
        Cost: "3,500¥",
        Source: "Core",
      },
      cyberMicrogrenadeLauncher: {
        Weapon: "Cyber Microgrenade Launcher",
        Accuracy: "4 (6)",
        DV: "Grenade",
        AP: "SS",
        Modes: "–",
        RC: "–",
        Ammo: "2 (m) / 6 (c)",
        Avail: "20F",
        Cost: "30,000¥",
        Source: "Core",
      },
      cyberShotgun: {
        Weapon: "Cyber Shotgun",
        Accuracy: "4 (6)",
        DV: "10P",
        AP: "-1",
        Modes: "SS",
        RC: "–",
        Ammo: "4 (m) / 10 (c)",
        Avail: "12R",
        Cost: "8,500¥",
        Source: "Core",
      },
      cyberSubmachinePistol: {
        Weapon: "Cyber Submachine Pistol",
        Accuracy: "4 (6)",
        DV: "7P",
        AP: "–",
        Modes: "SA/FA",
        RC: "2",
        Ammo: "18 (m) / 32 (c)",
        Avail: "12R",
        Cost: "4,800¥",
        Source: "Core",
      },
      flametosser: {
        Weapon: "Flametosser",
        Accuracy: "4",
        DV: "6P(fire)",
        AP: "-6",
        Modes: "SA/BF",
        RC: "–",
        Ammo: "5 (m)",
        Avail: "12F",
        Cost: "4,000¥",
        Source: "SR5:CF",
      },
      heavyCyberPistol: {
        Weapon: "Heavy Cyber Pistol",
        Accuracy: "4 (6)",
        DV: "7P",
        AP: "-1",
        Modes: "SA",
        RC: "–",
        Ammo: "8 (m) / 12 (c)",
        Avail: "12R",
        Cost: "4,300¥",
        Source: "Core",
      },
      lightCyberPistol: {
        Weapon: "Light Cyber Pistol",
        Accuracy: "6 (8)",
        DV: "7P",
        AP: "–",
        Modes: "SA",
        RC: "–",
        Ammo: "10 (m) / 15 (c)",
        Avail: "10R",
        Cost: "3,900¥",
        Source: "Core",
      },
      oneShotDartgun: {
        Weapon: "One-Shot Dartgun",
        Accuracy: "4",
        DV: "4P",
        AP: "–",
        Modes: "SS",
        RC: "–",
        Ammo: "1 (m)",
        Avail: "8R",
        Cost: "2,000¥",
        Source: "SR5:CF",
      },
    },
  };

  return weapons;
}
