export default function SecurityList() {
  const security = {
    devices: {
      keyCombinationLock: {
        type: "Device",
        name: "Key/Combination lock (Rating 1-6)",
        availability: "Rating",
        cost: "Rating x 10¥",
        source: "Core",
      },
      maglock: {
        type: "Device",
        name: "Maglock",
        availability: "Rating",
        cost: "Rating x 100¥",
        source: "Core",
      },
      keypadCardReader: {
        type: "Device",
        name: "Keypad or card reader",
        availability: "-",
        cost: "+50¥",
        source: "Core",
      },
      antiTamperCircuits: {
        type: "Device",
        name: "Anti-tamper circuits (Rating 1-4)",
        availability: "+Rating",
        cost: "+(Rating x 250)¥",
        source: "Core",
      },
      biometricReader: {
        type: "Device",
        name: "Biometric reader",
        availability: "+4",
        cost: "+200¥",
        source: "Core",
      },
    },
    restraints: {
      metal: {
        type: "Restraints",
        name: "Metal",
        availability: "-",
        cost: "20¥",
        source: "Core",
      },
      plasteel: {
        type: "Restraints",
        name: "Plasteel",
        availability: "6R",
        cost: "50¥",
        source: "Core",
      },
      plastic: {
        type: "Restraints",
        name: "Plastic (per 10)",
        availability: "-",
        cost: "5¥",
        source: "Core",
      },
      containmentManacles: {
        type: "Restraints",
        name: "Containment manacles",
        availability: "6R",
        cost: "250¥",
        source: "Core",
      },
    },
    bAndEGear: {
      autopicker: {
        type: "B&E Gear",
        name: "Autopicker (Rating 1-6)",
        availability: "8R",
        cost: "Rating x 500¥",
        source: "Core",
      },
      cellularGloveMolder: {
        type: "B&E Gear",
        name: "Cellular glove molder (Rating 1-4)",
        availability: "12F",
        cost: "Rating x 500¥",
        source: "Core",
      },
      chiselCrowbar: {
        type: "B&E Gear",
        name: "Chisel/crowbar",
        availability: "—",
        cost: "20¥",
        source: "Core",
      },
      keycardCopier: {
        type: "B&E Gear",
        name: "Keycard copier (Rating 1-6)",
        availability: "8F",
        cost: "Rating x 600¥",
        source: "Core",
      },
      lockpickSet: {
        type: "B&E Gear",
        name: "Lockpick set",
        availability: "4R",
        cost: "250¥",
        source: "Core",
      },
      maglockPasskey: {
        type: "B&E Gear",
        name: "Maglock passkey (Rating 1-4)",
        availability: "(Rating x 3)F",
        cost: "Rating x 2,000¥",
        source: "Core",
      },
      miniwelder: {
        type: "B&E Gear",
        name: "Miniwelder",
        availability: "2",
        cost: "250¥",
        source: "Core",
      },
      miniwelderFuelCanister: {
        type: "B&E Gear",
        name: "Miniwelder fuel canister",
        availability: "2",
        cost: "80¥",
        source: "Core",
      },
      monofilamentChainsaw: {
        type: "B&E Gear",
        name: "Monofilament chainsaw",
        availability: "8",
        cost: "500¥",
        source: "Core",
      },
      sequencer: {
        type: "B&E Gear",
        name: "Sequencer (Rating 1-6)",
        availability: "(Rating x 3)F",
        cost: "Rating x 250¥",
        source: "Core",
      },
    },
    grappleGun: {
      grappleGun: {
        type: "Grapple Gun",
        name: "Grapple gun",
        availability: "8R",
        cost: "500¥",
        source: "Core",
      },
      catalystStick: {
        type: "Grapple Gun",
        name: "Catalyst stick",
        availability: "8F",
        cost: "120¥",
        source: "Core",
      },
      microwire: {
        type: "Grapple Gun",
        name: "Microwire",
        availability: "4",
        cost: "50¥ per 100 m",
        source: "Core",
      },
      myomericRope: {
        type: "Grapple Gun",
        name: "Myomeric rope",
        availability: "10",
        cost: "200¥ per 10 m",
        source: "Core",
      },
      standardRope: {
        type: "Grapple Gun",
        name: "Standard rope",
        availability: "-",
        cost: "50¥ per 100 m",
        source: "Core",
      },
      stealthRope: {
        type: "Grapple Gun",
        name: "Stealth rope",
        availability: "8F",
        cost: "85¥ per 100 m",
        source: "Core",
      },
    },
    communications: {
      bugScanner: {
        type: "Communications",
        name: "Bug Scanner (Rating 1-6)",
        availability: "(Rating)R",
        cost: "Rating x 100¥",
        source: "Core",
      },
      dataTap: {
        type: "Communications",
        name: "Data Tap",
        availability: "6R",
        cost: "300¥",
        source: "Core",
      },
      headjammer: {
        type: "Communications",
        name: "Headjammer (Rating 1-6)",
        availability: "(Rating)R",
        cost: "Rating x 150¥",
        source: "Core",
      },
      jammerArea: {
        type: "Communications",
        name: "Jammer, Area (Rating 1-6)",
        availability: "(Rating x 3)F",
        cost: "Rating x 200¥",
        source: "Core",
      },
      jammerDirectional: {
        type: "Communications",
        name: "Jammer, Directional (Rating 1-6)",
        availability: "(Rating x 2)F",
        cost: "Rating x 200¥",
        source: "Core",
      },
      microTransceiver: {
        type: "Communications",
        name: "Micro-Transceiver",
        availability: "2",
        cost: "100¥",
        source: "Core",
      },
      tagEraser: {
        type: "Communications",
        name: "Tag Eraser",
        availability: "6R",
        cost: "450¥",
        source: "Core",
      },
      whiteNoiseGenerator: {
        type: "Communications",
        name: "White Noise Generator (Rating 1-6)",
        availability: "Rating",
        cost: "Rating x 50¥",
        source: "Core",
      },
    },
    batteringRam: {
      standardRam: {
        type: "Battering Ram",
        name: "Standard Ram",
        availability: "10R",
        cost: "2,000¥",
        source: "SR5:R&G",
      },
      fluidMotionRam: {
        type: "Battering Ram",
        name: "Fluid-Motion Ram",
        availability: "10R",
        cost: "3,500¥",
        source: "SR5:R&G",
      },
      pneumaticRam: {
        type: "Battering Ram",
        name: "Pneumatic Ram",
        availability: "18R",
        cost: "10,000¥",
        source: "SR5:R&G",
      },
      shockRam: {
        type: "Battering Ram",
        name: "Shock Ram",
        availability: "10R",
        cost: "15,000¥",
        source: "SR5:R&G",
      },
    },
  };
  return security;
}
