export default function SpellList() {
  const spells = {
    combatSpells: {
      acidStream: {
        name: "Acid Stream",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      toxicWave: {
        name: "Toxic Wave",
        effects: "Indirect, Elemental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "Core",
      },
      punch: {
        name: "Punch",
        effects: "Indirect",
        type: "P",
        range: "T",
        damage: "S",
        duration: "I",
        drain: "F-6",
        source: "Core",
      },
      clout: {
        name: "Clout",
        effects: "Indirect",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      blast: {
        name: "Blast",
        effects: "Indirect",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "I",
        drain: "F",
        source: "Core",
      },
      deathTouch: {
        name: "Death Touch",
        effects: "Direct",
        type: "M",
        range: "T",
        damage: "P",
        duration: "I",
        drain: "F-6",
        source: "Core",
      },
      manabolt: {
        name: "Manabolt",
        effects: "Direct",
        type: "M",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      manaball: {
        name: "Manaball",
        effects: "Direct",
        type: "M",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F",
        source: "Core",
      },
      flamethrower: {
        name: "Flamethrower",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      fireball: {
        name: "Fireball",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "Core",
      },
      lightningBolt: {
        name: "Lightning Bolt",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      ballLightning: {
        name: "Ball Lightning",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "Core",
      },
      shatter: {
        name: "Shatter",
        effects: "Direct",
        type: "P",
        range: "T",
        damage: "P",
        duration: "I",
        drain: "F-6",
        source: "Core",
      },
      powerbolt: {
        name: "Powerbolt",
        effects: "Direct",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      powerball: {
        name: "Powerball",
        effects: "Direct",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F",
        source: "Core",
      },
      knockout: {
        name: "Knockout",
        effects: "Direct",
        type: "M",
        range: "T",
        damage: "P",
        duration: "I",
        drain: "F-6",
        source: "Core",
      },
      stunbolt: {
        name: "Stunbolt",
        effects: "Direct",
        type: "M",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "Core",
      },
      stunball: {
        name: "Stunball",
        effects: "Direct",
        type: "M",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F",
        source: "Core",
      },
      corrodeObject: {
        name: "Corrode [Object]",
        effects: "Indirect, Elemental",
        type: "P",
        range: "T",
        damage: "P",
        duration: "I",
        drain: "F-5",
        source: "SR5:SG",
      },
      meltObject: {
        name: "Melt [Object]",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      sludgeObject: {
        name: "Sludge [Object]",
        effects: "Indirect, Elemental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "SR5:SG",
      },
      disruptFocus: {
        name: "Disrupt [Focus]",
        effects: "Direct",
        type: "M",
        range: "LOS",
        damage: "Special",
        duration: "I",
        drain: "F-2",
        source: "SR5:SG",
      },
      destroyFreeSpirit: {
        name: "Destroy [Free Spirit]",
        effects: "Direct",
        type: "M",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      destroyVehicle: {
        name: "Destroy [Vehicle]",
        effects: "Direct",
        type: "M",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      firewater: {
        name: "Firewater",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-2",
        source: "SR5:SG",
      },
      napalm: {
        name: "Napalm",
        effects: "Indirect, Elemental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F",
        source: "SR5:SG",
      },
      insecticideInsectSpirit: {
        name: "Insecticide [Insect Spirit]",
        effects: "Direct, Area",
        type: "P",
        range: "LOS(A)",
        damage: "M",
        duration: "I",
        drain: "F+1",
        source: "SR5:SG",
      },
      iceSpear: {
        name: "Ice Spear",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      iceStorm: {
        name: "Ice Storm",
        effects: "Indirect, Elemental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F+1",
        source: "SR5:SG",
      },
      oneLessMetatypeSpecies: {
        name: "One Less [Metatype/Species]",
        effects: "Direct",
        type: "M",
        range: "T",
        damage: "P",
        duration: "I",
        drain: "F-6",
        source: "SR5:SG",
      },
      slayMetatypeSpecies: {
        name: "Slay [Metatype/Species]",
        effects: "Direct",
        type: "M",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-4",
        source: "SR5:SG",
      },
      slaughterMetatypeSpecies: {
        name: "Slaughter [Metatype/Species]",
        effects: "Direct",
        type: "M",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-2",
        source: "SR5:SG",
      },
      ramObject: {
        name: "Ram [Object]",
        effects: "Direct",
        type: "P",
        range: "T",
        damage: "P",
        duration: "I",
        drain: "F-5",
        source: "SR5:SG",
      },
      wreckObject: {
        name: "Wreck [Object]",
        effects: "Direct",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      demolishObject: {
        name: "Demolish [Object]",
        effects: "Direct, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "SR5:SG",
      },
      radiationBeam: {
        name: "Radiation Beam",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      radiationBurst: {
        name: "Radiation Burst",
        effects: "Indirect, Elemental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "SR5:SG",
      },
      pollutantStream: {
        name: "Pollutant Stream",
        effects: "Indirect, Elemental",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      pollutantWave: {
        name: "Pollutant Wave",
        effects: "Indirect, Elemental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "SR5:SG",
      },
      shattershield: {
        name: "Shattershield",
        effects: "Direct",
        type: "M",
        range: "LOS(A)",
        damage: "P",
        duration: "I",
        drain: "F-1",
        source: "SR5:SG",
      },
    },
    detectionSpells: {
      analyzeDevice: {
        name: "Analyze Device",
        effects: "Active, Directional",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      analyzeMagic: {
        name: "Analyze Magic",
        effects: "Active, Directional",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      analyzeTruth: {
        name: "Analyze Truth",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-2",
        source: "Core",
      },
      clairaudience: {
        name: "Clairaudience",
        effects: "Passive, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      clairvoyance: {
        name: "Clairvoyance",
        effects: "Passive, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      combatSense: {
        name: "Combat Sense",
        effects: "Passive, Psychic",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F",
        source: "Core",
      },
      detectEnemies: {
        name: "Detect Enemies",
        effects: "Active, Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-2",
        source: "Core",
      },
      detectEnemiesExtended: {
        name: "Detect Enemies, Extended",
        effects: "Active, Extended Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F",
        source: "Core",
      },
      detectIndividual: {
        name: "Detect Individual",
        effects: "Active, Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      detectLife: {
        name: "Detect Life",
        effects: "Active, Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      detectLifeExtended: {
        name: "Detect Life, Extended",
        effects: "Active, Extended Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "Core",
      },
      detectLifeForm: {
        name: "Detect [Life Form]",
        effects: "Active, Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-2",
        source: "Core",
      },
      detectLifeFormExtended: {
        name: "Detect [Life Form], Extended",
        effects: "Active, Extended Area",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F",
        source: "Core",
      },
      detectObject: {
        name: "Detect [Object]",
        effects: "Active, Area",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-2",
        source: "Core",
      },
      mindlink: {
        name: "Mindlink",
        effects: "Active, Psychic",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "Core",
      },
      mindProbe: {
        name: "Mind Probe",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F",
        source: "Core",
      },
      astralMessage: {
        name: "Astral Message",
        effects: "Passive, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      astralClairvoyance: {
        name: "Astral Clairvoyance",
        effects: "Passive, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      borrowSense: {
        name: "Borrow Sense",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      animalSense: {
        name: "Animal Sense",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-5",
        source: "SR5:SG",
      },
      eyesOfThePack: {
        name: "Eyes of the Pack",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "SR5:SG",
      },
      catalog: {
        name: "Catalog",
        effects: "Active, Area",
        type: "P",
        range: "T(A)",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      diagnose: {
        name: "Diagnose",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      dragonAstralSignature: {
        name: "Dragon Astral Signature",
        effects: "Active, Psychic, Area",
        type: "M",
        range: "LOS(A)",
        damage: "",
        duration: "S",
        drain: "F+5",
        source: "SR5:SG",
      },
      enhanceAim: {
        name: "Enhance Aim",
        effects: "Passive, Directional",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "SR5:SG",
      },
      hawkeye: {
        name: "Hawkeye",
        effects: "Passive, Directional",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "SR5:SG",
      },
      manaWindow: {
        name: "Mana Window",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      astralWindow: {
        name: "Astral Window",
        effects: "Active, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      mindnet: {
        name: "Mindnet",
        effects: "Active, Psychic, Area",
        type: "M",
        range: "T(A)",
        damage: "",
        duration: "S",
        drain: "F",
        source: "SR5:SG",
      },
      mindnetExtended: {
        name: "Mindnet Extended",
        effects: "Active, Psychic, Extended Area",
        type: "M",
        range: "T(A)",
        damage: "",
        duration: "S",
        drain: "F+1",
        source: "SR5:SG",
      },
      nightVision: {
        name: "Night Vision",
        effects: "Passive, Directional",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      senseCryptesthesia: {
        name: "[Sense] Cryptesthesia",
        effects: "Passive, Directional",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      spatialSense: {
        name: "Spatial Sense",
        effects: "Passive, Area",
        type: "P",
        range: "T(A)",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      spatialSenseExtended: {
        name: "Spatial Sense Extended",
        effects: "Passive, Extended Area",
        type: "P",
        range: "T(A)",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "SR5:SG",
      },
      thoughtRecognition: {
        name: "Thought Recognition",
        effects: "Active, Psychic, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F",
        source: "SR5:SG",
      },
      areaThoughtRecognition: {
        name: "Area Thought Recognition",
        effects: "Active, Psychic, Area",
        type: "M",
        range: "LOS(A)",
        damage: "",
        duration: "S",
        drain: "F+2",
        source: "SR5:SG",
      },
      translate: {
        name: "Translate",
        effects: "Active, Psychic, Directional",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-4",
        source: "SR5:SG",
      },
    },
    healthSpells: {
      antidote: {
        name: "Antidote",
        effects: "",
        type: "M",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-3",
        source: "Core",
      },
      cureDisease: {
        name: "Cure Disease",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-4",
        source: "Core",
      },
      decreaseAttribute: {
        name: "Decrease [Attribute]",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-2",
        source: "Core",
      },
      detox: {
        name: "Detox",
        effects: "",
        type: "M",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-6",
        source: "Core",
      },
      heal: {
        name: "Heal",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-4",
        source: "Core",
      },
      increaseAttribute: {
        name: "Increase [Attribute]",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      increaseReflexes: {
        name: "Increase Reflexes",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F",
        source: "Core",
      },
      oxygenate: {
        name: "Oxygenate",
        effects: "",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-5",
        source: "Core",
      },
      prophylaxis: {
        name: "Prophylaxis",
        effects: "",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-4",
        source: "Core",
      },
      resistPain: {
        name: "Resist Pain",
        effects: "",
        type: "M",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-4",
        source: "Core",
      },
      stabilize: {
        name: "Stabilize",
        effects: "",
        type: "M",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-4",
        source: "Core",
      },
      ambidexterity: {
        name: "Ambidexterity",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "I",
        drain: "F-3",
        source: "SR5:SG",
      },
      alleviateAddiction: {
        name: "Alleviate Addiction",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-6",
        source: "SR5:SG",
      },
      alleviateAllergy: {
        name: "Alleviate [Allergy]",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-6",
        source: "SR5:SG",
      },
      awaken: {
        name: "Awaken",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      crank: {
        name: "Crank",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      decreaseReflexes: {
        name: "Decrease Reflexes",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "P",
        drain: "F-2",
        source: "SR5:SG",
      },
      enabler: {
        name: "Enabler",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      fast: {
        name: "Fast",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "SR5:SG",
      },
      forcedDefense: {
        name: "Forced Defense",
        effects: "Essence",
        type: "M",
        range: "T",
        damage: "",
        duration: "I",
        drain: "F-1",
        source: "SR5:SG",
      },
      increaseInherentLimits: {
        name: "Increase Inherent Limits",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "SR5:SG",
      },
      decreaseInherentLimits: {
        name: "Decrease Inherent Limits",
        effects: "Essence",
        type: "P",
        range: "T",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "SR5:SG",
      },
    },
    illusionSpells: {
      agony: {
        name: "Agony",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS",
        damage: "",
        duration: "S",
        drain: "F-4",
        source: "Core",
      },
      massAgony: {
        name: "Mass Agony",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS(A)",
        damage: "",
        duration: "S",
        drain: "F-2",
        source: "Core",
      },
      bugs: {
        name: "Bugs",
        effects: "Realistic, Multi-Sense",
        type: "M",
        range: "LOS",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      swarm: {
        name: "Swarm",
        effects: "Realistic, Multi-Sense",
        type: "M",
        range: "LOS(A)",
        damage: "",
        duration: "S",
        drain: "F-1",
        source: "Core",
      },
      confusion: {
        name: "Confusion",
        effects: "Realistic, Multi-Sense",
        type: "M",
        range: "LOS",
        damage: "",
        duration: "S",
        drain: "F-3",
        source: "Core",
      },
      massConfusion: {
        category: "Illusion",
        name: "Mass Confusion",
        effects: "Realistic, Multi-Sense, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      chaos: {
        category: "Illusion",
        name: "Chaos",
        effects: "Realistic, Multi-Sense",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      chaoticWorld: {
        category: "Illusion",
        name: "Chaotic World",
        effects: "Realistic, Multi-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F",
        source: "Core",
      },
      entertainment: {
        category: "Illusion",
        name: "Entertainment",
        effects: "Obvious, Multi-Sense, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-3",
        source: "Core",
      },
      tridEntertainment: {
        category: "Illusion",
        name: "Trid Entertainment",
        effects: "Obvious, Multi-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      invisibility: {
        category: "Illusion",
        name: "Invisibility",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      improvedInvisibility: {
        category: "Illusion",
        name: "Improved Invisibility",
        effects: "Realistic, Single-Sense",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      mask: {
        category: "Illusion",
        name: "Mask",
        effects: "Realistic, Multi-Sense",
        type: "M",
        range: "T",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      physicalMask: {
        category: "Illusion",
        name: "Physical Mask",
        effects: "Realistic, Multi-Sense",
        type: "P",
        range: "T",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      phantasm: {
        category: "Illusion",
        name: "Phantasm",
        effects: "Realistic, Multi-Sense, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      tridPhantasm: {
        category: "Illusion",
        name: "Trid Phantasm",
        effects: "Realistic, Multi-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F",
        source: "Core",
      },
      hush: {
        category: "Illusion",
        name: "Hush",
        effects: "Realistic, Single-Sense, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      silence: {
        category: "Illusion",
        name: "Silence",
        effects: "Realistic, Single-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      stealth: {
        category: "Illusion",
        name: "Stealth",
        effects: "Realistic, Single-Sense",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      camouflageCheck: {
        category: "Illusion",
        name: "Camouflage Check",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "SR5:SG",
      },
      physicalCamouflage: {
        category: "Illusion",
        name: "Physical Camouflage",
        effects: "Realistic, Single-Sense",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F",
        source: "SR5:SG",
      },
      decoy: {
        category: "Illusion",
        name: "Decoy",
        effects: "Realistic, Multi-Sense",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      chaff: {
        category: "Illusion",
        name: "Chaff",
        effects: "Realistic, Multi-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      doubleImage: {
        category: "Illusion",
        name: "Double Image",
        effects: "Realistic, Multi-Sense",
        type: "P",
        range: "T",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      dream: {
        category: "Illusion",
        name: "Dream",
        effects: "Realistic, Multi-Sense",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      euphoria: {
        category: "Illusion",
        name: "Euphoria",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      opiumDen: {
        category: "Illusion",
        name: "Opium Den",
        effects: "Realistic, Single-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      foreboding: {
        category: "Illusion",
        name: "Foreboding",
        effects: "Realistic, Multi-Sense",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      hotPotato: {
        category: "Illusion",
        name: "Hot Potato",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      senseRemoval: {
        category: "Illusion",
        name: "[Sense] Removal",
        effects: "Realistic, Single-Sense",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      massSenseRemoval: {
        category: "Illusion",
        name: "Mass [Sense] Removal",
        effects: "Realistic, Single-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      stink: {
        category: "Illusion",
        name: "Stink",
        effects: "Realistic, Single-Sense",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      stench: {
        category: "Illusion",
        name: "Stench",
        effects: "Realistic, Single-Sense, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      soundBarrier: {
        category: "Illusion",
        name: "Sound Barrier",
        effects: "Realistic, Single-Sense, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      switchVehicleSignature: {
        category: "Illusion",
        name: "Switch Vehicle Signature",
        effects: "Realistic, Multi-Sense",
        type: "P",
        range: "T",
        damage: "Special",
        duration: "F+1",
        source: "SR5:SG",
      },
      vehicleMask: {
        category: "Illusion",
        name: "Vehicle Mask",
        effects: "Realistic, Multi-Sense",
        type: "P",
        range: "T",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
    },
    manipulationSpells: {
      animate: {
        category: "Manipulation",
        name: "Animate",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      massAnimate: {
        category: "Manipulation",
        name: "Mass Animate",
        effects: "Physical, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F+1",
        source: "Core",
      },
      armor: {
        category: "Manipulation",
        name: "Armor",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      controlActions: {
        category: "Manipulation",
        name: "Control Actions",
        effects: "Mental",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      mobControl: {
        category: "Manipulation",
        name: "Mob Control",
        effects: "Mental, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F+1",
        source: "Core",
      },
      controlThoughts: {
        category: "Manipulation",
        name: "Control Thoughts",
        effects: "Mental",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      mobMind: {
        category: "Manipulation",
        name: "Mob Mind",
        effects: "Mental, Area",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F+1",
        source: "Core",
      },
      fling: {
        category: "Manipulation",
        name: "Fling",
        effects: "Physical, Damaging",
        type: "P",
        range: "LOS",
        damage: "I",
        duration: "F-2",
        source: "Core",
      },
      iceSheet: {
        category: "Manipulation",
        name: "Ice Sheet",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "I",
        duration: "F",
        source: "Core",
      },
      ignite: {
        category: "Manipulation",
        name: "Ignite",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "F-1",
        source: "Core",
      },
      influence: {
        category: "Manipulation",
        name: "Influence",
        effects: "Mental",
        type: "M",
        range: "LOS",
        damage: "P",
        duration: "F-1",
        source: "Core",
      },
      levitate: {
        category: "Manipulation",
        name: "Levitate",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      light: {
        category: "Manipulation",
        name: "Light",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-4",
        source: "Core",
      },
      magicFingers: {
        category: "Manipulation",
        name: "Magic Fingers",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      manaBarrier: {
        category: "Manipulation",
        name: "Mana Barrier",
        effects: "Environmental, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      physicalBarrier: {
        category: "Manipulation",
        name: "Physical Barrier",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "Core",
      },
      poltergeist: {
        category: "Manipulation",
        name: "Poltergeist",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-2",
        source: "Core",
      },
      shadow: {
        category: "Manipulation",
        name: "Shadow",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-3",
        source: "Core",
      },
      bind: {
        category: "Manipulation",
        name: "Bind",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "SR5:SG",
      },
      netBind: {
        category: "Manipulation",
        name: "Net Bind",
        effects: "Physical, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      manaBind: {
        category: "Manipulation",
        name: "Mana Bind",
        effects: "Mana",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-2",
        source: "SR5:SG",
      },
      manaNet: {
        category: "Manipulation",
        name: "Mana Net",
        effects: "Mana, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      bugZapper: {
        category: "Manipulation",
        name: "Bug Zapper",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F+1",
        source: "SR5:SG",
      },
      calmAnimal: {
        category: "Manipulation",
        name: "Calm Animal",
        effects: "Mental",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      calmPack: {
        category: "Manipulation",
        name: "Calm Pack",
        effects: "Mental, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      catfall: {
        category: "Manipulation",
        name: "Catfall",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      cleanElement: {
        category: "Manipulation",
        name: "Clean [Element]",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "F-3",
        source: "SR5:SG",
      },
      compelTruth: {
        category: "Manipulation",
        name: "Compel Truth",
        effects: "Mental",
        type: "M",
        range: "LOS",
        damage: "Special",
        duration: "F-1",
        source: "SR5:SG",
      },
      controlAnimal: {
        category: "Manipulation",
        name: "Control Animal",
        effects: "Mental",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      controlPack: {
        category: "Manipulation",
        name: "Control Pack",
        effects: "Mental, Area",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      controlPack: {
        category: "Manipulation",
        name: "Control Pack",
        effects: "Mental, Area",
        type: "M",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      deflection: {
        category: "Manipulation",
        name: "Deflection",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      elementAura: {
        category: "Manipulation",
        name: "[Element] Aura",
        effects: "Environmental",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F+1",
        source: "SR5:SG",
      },
      elementWall: {
        category: "Manipulation",
        name: "[Element] Wall",
        effects: "Environmental",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F+2",
        source: "SR5:SG",
      },
      fashion: {
        category: "Manipulation",
        name: "Fashion",
        effects: "Environmental, Area",
        type: "P",
        range: "T(A)",
        damage: "P",
        duration: "F-1",
        source: "SR5:SG",
      },
      fix: {
        category: "Manipulation",
        name: "Fix",
        effects: "Physical",
        type: "P",
        range: "T",
        damage: "P",
        duration: "F",
        source: "SR5:SG",
      },
      geckoCrawl: {
        category: "Manipulation",
        name: "Gecko Crawl",
        effects: "Physical",
        type: "P",
        range: "T",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      glue: {
        category: "Manipulation",
        name: "Glue",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "P",
        duration: "F-3",
        source: "SR5:SG",
      },
      glueStrip: {
        category: "Manipulation",
        name: "Glue Strip",
        effects: "Physical, Area",
        type: "P",
        range: "LOS(A)",
        damage: "P",
        duration: "F-1",
        source: "SR5:SG",
      },
      increaseNoise: {
        category: "Manipulation",
        name: "Increase Noise",
        effects: "Physical",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      decreaseNoise: {
        category: "Manipulation",
        name: "Decrease Noise",
        effects: "Physical",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      increaseGearLimits: {
        category: "Manipulation",
        name: "Increase Gear Limits",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      decreaseGearLimits: {
        category: "Manipulation",
        name: "Decrease Gear Limits",
        effects: "Physical",
        type: "P",
        range: "T",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      interference: {
        category: "Manipulation",
        name: "Interference",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      lock: {
        category: "Manipulation",
        name: "Lock",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      manaStatic: {
        category: "Manipulation",
        name: "Mana Static",
        effects: "Environmental, Area",
        type: "M",
        range: "LOS(A)",
        damage: "P",
        duration: "F-1",
        source: "SR5:SG",
      },
      makeover: {
        category: "Manipulation",
        name: "Makeover",
        effects: "Physical",
        type: "P",
        range: "T",
        damage: "P",
        duration: "F-3",
        source: "SR5:SG",
      },
      mist: {
        category: "Manipulation",
        name: "Mist",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "I",
        duration: "F-3",
        source: "SR5:SG",
      },
      offensiveManaBarrier: {
        category: "Manipulation",
        name: "Offensive Mana Barrier",
        effects: "Environmental, Area",
        type: "M",
        range: "LOS(A)",
        damage: "S",
        duration: "F+3",
        source: "SR5:SG",
      },
      preserve: {
        category: "Manipulation",
        name: "Preserve",
        effects: "Physical, Area",
        type: "P",
        range: "T",
        damage: "I",
        duration: "F-3",
        source: "SR5:SG",
      },
      protectVehicle: {
        category: "Manipulation",
        name: "Protect Vehicle",
        effects: "Physical, Area",
        type: "P",
        range: "T",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      pulse: {
        category: "Manipulation",
        name: "Pulse",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "I",
        duration: "F+3",
        source: "SR5:SG",
      },
      reinforce: {
        category: "Manipulation",
        name: "Reinforce",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      slowVehicle: {
        category: "Manipulation",
        name: "Slow Vehicle",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F+1",
        source: "SR5:SG",
      },
      shapeMaterial: {
        category: "Manipulation",
        name: "Shape [Material]",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-2",
        source: "SR5:SG",
      },
      shapechange: {
        category: "Manipulation",
        name: "Shapechange",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-3",
        source: "SR5:SG",
      },
      critterForm: {
        category: "Manipulation",
        name: "[Critter] Form",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F-4",
        source: "SR5:SG",
      },
      spiritBarrier: {
        category: "Manipulation",
        name: "Spirit Barrier",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F-1",
        source: "SR5:SG",
      },
      spiritZapper: {
        category: "Manipulation",
        name: "Spirit Zapper",
        effects: "Environmental, Area",
        type: "P",
        range: "LOS(A)",
        damage: "S",
        duration: "F+1",
        source: "SR5:SG",
      },
      sterilize: {
        category: "Manipulation",
        name: "Sterilize",
        effects: "Physical, Area",
        type: "P",
        range: "LOS(A)",
        damage: "I",
        duration: "F-3",
        source: "SR5:SG",
      },
      turnToGoo: {
        category: "Manipulation",
        name: "Turn to Goo",
        effects: "Physical",
        type: "P",
        range: "LOS",
        damage: "S",
        duration: "F+3",
        source: "SR5:SG",
      },
      catch: {
        category: "Manipulation",
        name: "Catch",
        effects: "Manipulation",
        type: "P",
        range: "LOS",
        damage: "I",
        duration: "F-2",
        source: "SR5:HT",
      },
      concealScent: {
        category: "Manipulation",
        name: "Conceal Scent",
        effects: "Object, Manipulation",
        type: "P",
        range: "Touch",
        damage: "S",
        duration: "F-3",
        source: "SR5:HT",
      },
      snakeblood: {
        category: "Manipulation",
        name: "Snakeblood",
        effects: "Manipulation",
        type: "P",
        range: "Touch",
        damage: "S",
        duration: "F-2",
        source: "SR5:HT",
      },
      rechargePotency: {
        category: "Manipulation",
        name: "Recharge Potency",
        effects: "Manipulation",
        type: "M",
        range: "Touch",
        damage: "P",
        duration: "F+1",
        source: "SR5:HT",
      },
      manablade: {
        category: "Manipulation",
        name: "Manablade",
        effects: "Manipulation",
        type: "M",
        range: "Special",
        damage: "S",
        duration: "F-2",
        source: "SR5:HT",
      },
      powerblade: {
        category: "Manipulation",
        name: "Powerblade",
        effects: "Manipulation",
        type: "P",
        range: "Special",
        damage: "S",
        duration: "F-2",
        source: "SR5:HT",
      },
    },
  };
  return spells;
}
