export default function VehiclemodsList() {
  const vehicleMods = {
    powerTrainMods: {
      accelerationEnhancementR1: {
        modification: "Acceleration Enhancement R1",
        slots: "4",
        threshold: "12",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "Accel x 10,000¥",
        source: "SR5:R5",
      },
      accelerationEnhancementR2: {
        modification: "Acceleration Enhancement R2",
        slots: "8",
        threshold: "24",
        tools: "Facility",
        skill: "-",
        avail: "6",
        cost: "Accel x 25,000¥",
        source: "SR5:R5",
      },
      geckoTipsBody1_3: {
        modification: "Gecko Tips (Body 1–3)",
        slots: "1",
        threshold: "8",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "1,000¥",
        source: "SR5:R5",
      },
      geckoTipsBody4_6: {
        modification: "Gecko Tips (Body 4–6)",
        slots: "4",
        threshold: "16",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "5,000¥",
        source: "SR5:R5",
      },
      glidingSystemBody12: {
        modification: "Gliding System (Body <= 12)",
        slots: "5",
        threshold: "16",
        tools: "Facility",
        skill: "-",
        avail: "12R",
        cost: "Body x 3,000¥",
        source: "SR5:R5",
      },
      glidingSystemBodyGT12: {
        modification: "Gliding System (Body > 12)",
        slots: "10",
        threshold: "24",
        tools: "Facility",
        skill: "-",
        avail: "16R",
        cost: "Body x 4,000¥",
        source: "SR5:R5",
      },
      handlingEnhancementR1: {
        modification: "Handling Enhancement (R1)",
        slots: "4",
        threshold: "8",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "Handl x 2,000¥",
        source: "SR5:R5",
      },
      handlingEnhancementR2: {
        modification: "Handling Enhancement (R2)",
        slots: "10",
        threshold: "16",
        tools: "Facility",
        skill: "-",
        avail: "8",
        cost: "Handl x 5,000¥",
        source: "SR5:R5",
      },
      handlingEnhancementR3: {
        modification: "Handling Enhancement (R3)",
        slots: "18",
        threshold: "24",
        tools: "Facility",
        skill: "-",
        avail: "10",
        cost: "Handl x 12,000¥",
        source: "SR5:R5",
      },
      improvedEconomy: {
        modification: "Improved Economy",
        slots: "2",
        threshold: "12",
        tools: "Facility",
        skill: "-",
        avail: "4",
        cost: "7,500¥",
        source: "SR5:R5",
      },
      manualControlOverride: {
        modification: "Manual Control Override",
        slots: "1",
        threshold: "4",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "500¥",
        source: "SR5:R5",
      },
      multifuelEngine: {
        modification: "Multifuel Engine",
        slots: "4",
        threshold: "20",
        tools: "Shop",
        skill: "-",
        avail: "10",
        cost: "Body x 1,000¥",
        source: "SR5:R5",
      },
      offRoadSuspension2: {
        modification: "Off-Road Suspension 2",
        slots: "8",
        threshold: "Shop",
        tools: "-",
        skill: "4",
        avail: "Vehicle cost¥ x 25%",
        cost: "SR5:R5",
      },
      riggerCocoon: {
        modification: "Rigger Cocoon",
        slots: "2",
        threshold: "6",
        tools: "Kit",
        skill: "-",
        avail: "8",
        cost: "1,500¥",
        source: "SR5:R5",
      },
      removedManualControls: {
        modification: "Removed Manual Controls",
        slots: "1",
        threshold: "4",
        tools: "Shop",
        skill: "-",
        avail: "2",
        cost: "200¥",
        source: "SR5:R5",
      },
      rocketBooster: {
        modification: "Rocket Booster",
        slots: "10",
        threshold: "36",
        tools: "Facility",
        skill: "-",
        avail: "16F",
        cost: "Body x 5,000¥",
        source: "SR5:R5",
      },
      secondaryPropulsionAmphibiousSurface: {
        modification: "Secondary Propulsion (Amphibious, Surface)",
        slots: "4",
        threshold: "10",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "Body x 200¥",
        source: "SR5:R5",
      },
      secondaryPropulsionAmphibiousSubmersible: {
        modification: "Secondary Propulsion (Amphibious, Submersible)",
        slots: "8",
        threshold: "20",
        tools: "Shop",
        skill: "-",
        avail: "12R",
        cost: "Body x 2,000¥",
        source: "SR5:R5",
      },
      secondaryPropulsionHovercraft: {
        modification: "Secondary Propulsion (Hovercraft)",
        slots: "8",
        threshold: "16",
        tools: "Shop",
        skill: "-",
        avail: "12",
        cost: "Body x 1,000¥",
        source: "SR5:R5",
      },
      secondaryPropulsionRotor: {
        modification: "Secondary Propulsion (Rotor)",
        slots: "10",
        threshold: "24",
        tools: "Facility",
        skill: "-",
        avail: "12R",
        cost: "Body x 3,000¥",
        source: "SR5:R5",
      },
      secondaryPropulsionTracked: {
        modification: "Secondary Propulsion (Tracked)",
        slots: "6",
        threshold: "14",
        tools: "Shop",
        skill: "-",
        avail: "10",
        cost: "Body x 1,000¥",
        source: "SR5:R5",
      },
      walker: {
        modification: "Walker",
        slots: "8",
        threshold: "16",
        tools: "Shop",
        skill: "-",
        avail: "12",
        cost: "Body x 2,000¥",
        source: "SR5:R5",
      },
      speedEnhancementR1: {
        modification: "Speed Enhancement (R1)",
        slots: "5",
        threshold: "8",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "Speed x 2,000¥",
        source: "SR5:R5",
      },
      speedEnhancementR2: {
        modification: "Speed Enhancement (R2)",
        slots: "14",
        threshold: "16",
        tools: "Facility",
        skill: "-",
        avail: "8",
        cost: "Speed x 5,000¥",
        source: "SR5:R5",
      },
      speedEnhancementR3: {
        modification: "Speed Enhancement (R3)",
        slots: "20",
        threshold: "24",
        tools: "Facility",
        skill: "-",
        avail: "12",
        cost: "Speed x 12,000¥",
        source: "SR5:R5",
      },
    },
    protectionMods: {
      antiTheftSystemR1: {
        modification: "Anti-Theft System (R1)",
        slots: "1",
        threshold: "4",
        tools: "Kit",
        skill: "-",
        avail: "4",
        cost: "500¥",
        source: "SR5:R5",
      },
      antiTheftSystemR2: {
        modification: "Anti-Theft System (R2)",
        slots: "2",
        threshold: "8",
        tools: "Kit",
        skill: "-",
        avail: "6",
        cost: "1,000¥",
        source: "SR5:R5",
      },
      antiTheftSystemR3: {
        modification: "Anti-Theft System (R3)",
        slots: "4",
        threshold: "12",
        tools: "Shop",
        skill: "-",
        avail: "8R",
        cost: "2,500¥",
        source: "SR5:R5",
      },
      antiTheftSystemR4: {
        modification: "Anti-Theft System (R4)",
        slots: "6",
        threshold: "16",
        tools: "Shop",
        skill: "Demolitions",
        avail: "12F",
        cost: "5,000¥",
        source: "SR5:R5",
      },
      armorStandard: {
        modification: "Armor (Standard)",
        slots: "Rating x 2",
        threshold: "Rating x 2",
        tools: "Shop",
        skill: "Armorer",
        avail: "6R",
        cost: "Rating x 500¥",
        source: "SR5:R5",
      },
      armorConcealed: {
        modification: "Armor (Concealed)",
        slots: "Rating x 3",
        threshold: "Rating x 3",
        tools: "Shop",
        skill: "Armorer",
        avail: "12R",
        cost: "Rating x 3,000¥",
        source: "SR5:R5",
      },
      pps: {
        modification: "PPS (Rating 1-6)",
        slots: "2",
        threshold: "Rating x 4",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "Rating x 2,000¥",
        source: "SR5:R5",
      },
      personalArmor: {
        modification: "Personal Armor (Rating 1-10)",
        slots: "2",
        threshold: "Rating x 2",
        tools: "Shop",
        skill: "Armorer",
        avail: "(Rating)R",
        cost: "Rating x 500¥",
        source: "SR5:R5",
      },
      specialArmorModification: {
        modification: "Special Armor Modification",
        slots: "2",
        threshold: "12",
        tools: "Shop",
        skill: "Armorer",
        avail: "(As Mod)",
        cost: "(As Mod) x 2¥",
        source: "SR5:R5",
      },
    },
    weaponMods: {
      ammoBin: {
        modification: "Ammo Bin",
        slots: "1",
        threshold: "4",
        tools: "Shop",
        skill: "Armorer",
        avail: "6R",
        cost: "200¥",
        source: "SR5:R5",
      },
      standardDroneRackMini: {
        modification: "Standard Drone Rack (Mini)",
        slots: "1",
        threshold: "8",
        tools: "Kit",
        skill: "-",
        avail: "4",
        cost: "500¥",
        source: "SR5:R5",
      },
      standardDroneRackSmall: {
        modification: "Standard Drone Rack (Small)",
        slots: "2",
        threshold: "10",
        tools: "Shop",
        skill: "-",
        avail: "4",
        cost: "1,000¥",
        source: "SR5:R5",
      },
      standardDroneRackMedium: {
        modification: "Standard Drone Rack (Medium)",
        slots: "3",
        threshold: "12",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "2,000¥",
        source: "SR5:R5",
      },
      standardDroneRackLarge: {
        modification: "Standard Drone Rack (Large)",
        slots: "4",
        threshold: "16",
        tools: "Shop",
        skill: "-",
        avail: "8",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      landingDroneRackMini: {
        modification: "Landing Drone Rack (Mini)",
        slots: "2",
        threshold: "10",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "1,000¥",
        source: "SR5:R5",
      },
      landingDroneRackSmall: {
        modification: "Landing Drone Rack (Small)",
        slots: "3",
        threshold: "12",
        tools: "Shop",
        skill: "-",
        avail: "6",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      landingDroneRackMedium: {
        modification: "Landing Drone Rack (Medium)",
        slots: "4",
        threshold: "14",
        tools: "Facility",
        skill: "-",
        avail: "8",
        cost: "10,000¥",
        source: "SR5:R5",
      },
      landingDroneRackLarge: {
        modification: "Landing Drone Rack (Large)",
        slots: "5",
        threshold: "20",
        tools: "Facility",
        skill: "-",
        avail: "12",
        cost: "20,000¥",
        source: "SR5:R5",
      },
      gunPort: {
        modification: "Gun Port",
        slots: "1",
        threshold: "4",
        tools: "Kit",
        skill: "-",
        avail: "6R",
        cost: "500¥",
        source: "SR5:R5",
      },
      missileDefenseSystem: {
        modification: "Missile Defense System",
        slots: "3",
        threshold: "16",
        tools: "Facility",
        skill: "Software",
        avail: "12R",
        cost: "15,000¥",
        source: "SR5:R5",
      },
      oilSlickSprayer: {
        modification: "Oil Slick Sprayer",
        slots: "2",
        threshold: "8",
        tools: "Shop",
        skill: "-",
        avail: "8F",
        cost: "500¥",
        source: "SR5:R5",
      },
      smokeProjector: {
        modification: "Smoke Projector",
        slots: "2",
        threshold: "8",
        tools: "Shop",
        skill: "-",
        avail: "6R",
        cost: "750¥",
        source: "SR5:R5",
      },
      thermalSmoke: {
        modification: "Thermal Smoke",
        slots: "-",
        threshold: "-",
        tools: "-",
        skill: "-",
        avail: "-",
        cost: "+100¥",
        source: "SR5:R5",
      },
      roadStripEjector: {
        modification: "Road Strip Ejector",
        slots: "2",
        threshold: "10",
        tools: "Shop",
        skill: "-",
        avail: "10F",
        cost: "800¥ + strips",
        source: "SR5:R5",
      },
      weaponMountLight: {
        modification: "Weapon Mount (Light)",
        slots: "1",
        threshold: "4",
        tools: "Kit",
        skill: "Armorer",
        avail: "6F",
        cost: "750¥",
        source: "SR5:R5",
      },
      weaponMountStandard: {
        modification: "Weapon Mount (Standard)",
        slots: "2",
        threshold: "6",
        tools: "Shop",
        skill: "Armorer",
        avail: "8F",
        cost: "1,500¥",
        source: "SR5:R5",
      },
      weaponMountHeavy: {
        modification: "Weapon Mount (Heavy)",
        slots: "4",
        threshold: "10",
        tools: "Shop",
        skill: "Armorer",
        avail: "12F",
        cost: "4,000¥",
        source: "SR5:R5",
      },
      externalVisibility: {
        modification: "External Visibility",
        slot,
      },

      internalVisibility: {
        modification: "Internal Visibility",
        slots: "+2",
        threshold: "+6",
        tools: "Shop",
        skill: "-",
        avail: "+2",
        cost: "+1,500¥",
        source: "SR5:R5",
      },
      concealedVisibility: {
        modification: "Concealed Visibility",
        slots: "+4",
        threshold: "+10",
        tools: "Shop",
        skill: "-",
        avail: "+4",
        cost: "+4,000¥",
        source: "SR5:R5",
      },
      fixedFlexibility: {
        modification: "Fixed Flexibility",
        slots: "-",
        threshold: "-",
        tools: "-",
        skill: "-",
        avail: "-",
        cost: "0¥",
        source: "SR5:R5",
      },
      flexibleFlexibility: {
        modification: "Flexible Flexibility",
        slots: "+1",
        threshold: "+4",
        tools: "Shop",
        skill: "-",
        avail: "+2",
        cost: "+2,000¥",
        source: "SR5:R5",
      },
      turretFlexibility: {
        modification: "Turret Flexibility",
        slots: "+2",
        threshold: "+12",
        tools: "Facility",
        skill: "-",
        avail: "+6",
        cost: "+5,000¥",
        source: "SR5:R5",
      },
      remoteControl: {
        modification: "Remote Control",
        slots: "-",
        threshold: "-",
        tools: "-",
        skill: "-",
        avail: "-",
        cost: "0¥",
        source: "SR5:R5",
      },
      manualControl: {
        modification: "Manual Control",
        slots: "+1",
        threshold: "+4",
        tools: "Shop",
        skill: "-",
        avail: "+1",
        cost: "+500¥",
        source: "SR5:R5",
      },
      armoredManualControl: {
        modification: "Armored Manual Control",
        slots: "+2",
        threshold: "+6",
        tools: "Shop",
        skill: "-",
        avail: "+4",
        cost: "+1,500¥",
        source: "SR5:R5",
      },
    },
    bodyMods: {
      assemblyDisassembly: {
        modification: "Assembly/Disassembly",
        slots: 2,
        threshold: "Body x 4 (Min. 1)",
        tools: "Facility",
        skill: "-",
        avail: 6,
        cost: "1,000¥",
        source: "SR5:R5",
      },
      chameleonCoating: {
        modification: "Chameleon Coating",
        slots: 2,
        threshold: 10,
        tools: "Facility",
        skill: "-",
        avail: "12F",
        cost: "Body x 1,000¥",
        source: "SR5:R5",
      },
      extraEntryExitPoints: {
        modification: "Extra Entry/Exit Points",
        slots: 1,
        threshold: 8,
        tools: "Shop",
        skill: "-",
        avail: 8,
        cost: "2,500¥",
        source: "SR5:R5",
      },
      extremeEnvironmentModification: {
        modification: "Extreme Environment Modification",
        slots: 2,
        threshold: 12,
        tools: "Shop",
        skill: "-",
        avail: 6,
        cost: "2,000¥",
        source: "SR5:R5",
      },
      increasedSeating: {
        modification: "Increased Seating",
        slots: 2,
        threshold: 6,
        tools: "Shop",
        skill: "-",
        avail: 4,
        cost: "2,000¥",
        source: "SR5:R5",
      },
      lifeSupportL1: {
        modification: "Life Support (L1)",
        slots: 2,
        threshold: 10,
        tools: "Shop",
        skill: "-",
        avail: 8,
        cost: "Body x 500¥",
        source: "SR5:R5",
      },
      lifeSupportL2: {
        modification: "Life Support (L2)",
        slots: 4,
        threshold: 20,
        tools: "Shop",
        skill: "-",
        avail: 12,
        cost: "Body x 2,000¥",
        source: "SR5:R5",
      },
      mechanicalArmBasic: {
        modification: "Mechanical Arm (Basic)",
        slots: 2,
        threshold: 8,
        tools: "Shop",
        skill: "-",
        avail: 4,
        cost: "1,000¥",
        source: "SR5:R5",
      },
      mechanicalArmArticulated: {
        modification: "Mechanical Arm (Articulated)",
        slots: 3,
        threshold: 16,
        tools: "Facility",
        skill: "-",
        avail: 6,
        cost: "5,000¥",
        source: "SR5:R5",
      },
      nanomaintenanceSystem: {
        modification: "Nanomaintenance System (R 1-4)",
        slots: "Rating",
        threshold: "Rating x 4",
        tools: "Shop",
        skill: "-",
        avail: "(R x 5)R",
        cost: "Rating x 5,000¥",
        source: "SR5:R5",
      },
      realisticFeatures: {
        modification: "Realistic Features (R 1-4)",
        slots: "Rating",
        threshold: "Rating x 4",
        tools: "Shop",
        skill: "Medicine",
        avail: "(R x 3)R",
        cost: "Rating x Body x 1,000¥",
        source: "SR5:R5",
      },
      smugglingCompartment: {
        modification: "Smuggling Compartment",
        slots: 3,
        threshold: 16,
        tools: "Facility",
        skill: "-",
        avail: "8F",
        cost: "1,500¥",
        source: "SR5:R5",
      },
      smugglingCompartmentShielding: {
        modification: "Smuggling Compartment (Shielding)",
        slots: "n/a",
        threshold: 12,
        tools: "Facility",
        skill: "-",
        avail: "12F",
        cost: "3,000¥",
        source: "SR5:R5",
      },
      specialEquipment: {
        modification: "Special Equipment",
        slots: "variable",
        threshold: "variable",
        tools: "variable",
        skill: "variable",
        avail: "variable",
        cost: "variable¥",
        source: "SR5:R5",
      },
      valkyrieModule: {
        modification: "Valkyrie Module",
        slots: 4,
        threshold: 6,
        tools: "Shop",
        skill: "Hardware",
        avail: 8,
        cost: "2,000¥",
        source: "SR5:R5",
      },
      winchBasic: {
        modification: "Winch (Basic)",
        slots: 1,
        threshold: 8,
        tools: "Shop",
        skill: "-",
        avail: 4,
        cost: "750¥",
        source: "SR5:R5",
      },
      winchEnhanced: {
        modification: "Winch (Enhanced)",
        slots: 2,
        threshold: 12,
        tools: "Facility",
        skill: "-",
        avail: 8,
        cost: "4,000¥",
        source: "SR5:R5",
      },
      workshop: {
        modification: "Workshop",
        slots: 6,
        threshold: 20,
        tools: "Facility",
        skill: "-",
        avail: "-",
        cost: "0¥",
        source: "SR5:R5",
      },
    },
    electromagneticMods: {
      electromagneticShielding: {
        modification: "Electromagnetic Shielding",
        slots: 2,
        threshold: 20,
        tools: "Facility",
        skill: "-",
        avail: "6R",
        cost: "Body x 500¥",
        source: "SR5:R5",
      },
      ecm: {
        modification: "ECM",
        slots: 2,
        threshold: 20,
        tools: "Shop",
        skill: "Hardware",
        avail: "(R x 3)F",
        cost: "Rating x 500¥",
        source: "SR5:R5",
      },
      gridlink: {
        modification: "Gridlink",
        slots: 2,
        threshold: 4,
        tools: "Shop",
        skill: "Hardware",
        avail: 4,
        cost: "750¥",
        source: "SR5:R5",
      },
      gridlinkOverride: {
        modification: "Gridlink Override",
        slots: 1,
        threshold: 8,
        tools: "Kit",
        skill: "Hardware",
        avail: "8F",
        cost: "1,000¥",
        source: "SR5:R5",
      },
      pilotEnhancementR1R3: {
        modification: "Pilot Enhancement (R1–3)",
        slots: "[Rating]",
        threshold: "Rating x 3",
        tools: "Kit",
        skill: "Hardware",
        avail: "R x 2",
        cost: "Rating x 2,000¥",
        source: "SR5:R5",
      },
      pilotEnhancementR4R6: {
        modification: "Pilot Enhancement (R4–6)",
        slots: "[Rating]",
        threshold: "Rating x 4",
        tools: "Shop",
        skill: "Hardware",
        avail: "R x 3",
        cost: "Rating x 5,000¥",
        source: "SR5:R5",
      },
      retransUnit: {
        modification: "Retrans Unit",
        slots: 2,
        threshold: 4,
        tools: "Kit",
        skill: "Hardware",
        avail: 8,
        cost: "4,000¥",
        source: "SR5:R5",
      },
      satelliteLink: {
        modification: "Satellite Link",
        slots: 1,
        threshold: 6,
        tools: "Kit",
        skill: "Hardware",
        avail: 6,
        cost: "500¥",
        source: "SR5:R5",
      },
      sensorEnhancementR1R3: {
        modification: "Sensor Enhancement (R1–3)",
        slots: "[Rating]",
        threshold: "Rating x 3",
        tools: "Shop",
        skill: "Hardware",
        avail: "R x 2",
        cost: "Rating x 2,000¥",
        source: "SR5:R5",
      },
      sensorEnhancementR4R6: {
        modification: "Sensor Enhancement (R4–6)",
        slots: "[Rating]",
        threshold: "Rating x 4",
        tools: "Shop",
        skill: "Hardware",
        avail: "R x 3",
        cost: "Rating x 5,000¥",
        source: "SR5:R5",
      },
      signatureMaskingR1R6: {
        modification: "Signature Masking (R1–6)",
        slots: "[Rating]",
        threshold: "Rating x 6",
        tools: "Facility",
        skill: "-",
        avail: "14F",
        cost: "Rating x 2,000¥",
        source: "SR5:R5",
      },
      sunCell: {
        modification: "SunCell",
        slots: 2,
        threshold: 16,
        tools: "Shop",
        skill: "Hardware",
        avail: 6,
        cost: "Body x 500¥",
        source: "SR5:R5",
      },
      touchSensors: {
        modification: "Touch Sensors",
        slots: 3,
        threshold: 16,
        tools: "Shop",
        skill: "Hardware",
        avail: 8,
        cost: "Body x 500¥",
        source: "SR5:R5",
      },
    },
    cosmeticMods: {
      amenitiesSquatter: {
        modification: "Amenities (Squatter)",
        slots: "-",
        threshold: 6,
        tools: "Shop",
        skill: "-",
        avail: "-",
        cost: "100¥",
        source: "SR5:R5",
      },
      amenitiesMiddle: {
        modification: "Amenities (Middle)",
        slots: "-",
        threshold: 6,
        tools: "Shop",
        skill: "-",
        avail: 2,
        cost: "500¥",
        source: "SR5:R5",
      },
      amenitiesHigh: {
        modification: "Amenities (High)",
        slots: "-",
        threshold: 10,
        tools: "Shop",
        skill: "-",
        avail: 8,
        cost: "1,000¥",
        source: "SR5:R5",
      },
      luxury: {
        modification: "Luxury",
        slots: "-",
        threshold: 20,
        tools: "Shop",
        skill: "-",
        avail: 16,
        cost: "10,000¥",
        source: "SR5:R5",
      },
      enhancedImageScreens: {
        modification: "Enhanced Image Screens",
        slots: "-",
        threshold: 12,
        tools: "Shop",
        skill: "-",
        avail: 8,
        cost: "5,000¥",
        source: "SR5:R5",
      },
      metahumanAdjustment: {
        modification: "Metahuman Adjustment",
        slots: "-",
        threshold: 4,
        tools: "Kit",
        skill: "-",
        avail: 4,
        cost: "500¥ /seat",
        source: "SR5:R5",
      },
      riggerInterface: {
        modification: "Rigger Interface",
        slots: "-",
        threshold: 8,
        tools: "Kit",
        skill: "-",
        avail: 4,
        cost: "1,000¥",
        source: "SR5:R5",
      },
      interiorCameras: {
        modification: "Interior Cameras",
        slots: "-",
        threshold: 6,
        tools: "Kit",
        skill: "Hardware",
        avail: 6,
        cost: "2,000¥",
        source: "SR5:R5",
      },
      searchlight: {
        modification: "Searchlight",
        slots: "-",
        threshold: 4,
        tools: "Kit",
        skill: "-",
        avail: 4,
        cost: "800¥",
        source: "SR5:R5",
      },
      vehicleTagEraser: {
        modification: "Vehicle Tag Eraser",
        slots: "-",
        threshold: 8,
        tools: "Shop",
        skill: "Hardware",
        avail: "6R",
        cost: "750¥",
        source: "SR5:R5",
      },
      yerzedOutR1R4: {
        modification: "Yerzed Out (R1–4)",
        slots: "-",
        threshold: "Rating x 4",
        tools: "Shop",
        skill: "-",
        avail: "(R x2)",
        cost: "Rating x 1,000¥",
        source: "SR5:R5",
      },
    },
    baseMods: {
      baseMods: {
        riggerInterface: {
          modification: "Rigger Interface",
          availability: 4,
          cost: "1,000¥",
          source: "Core",
        },
        standardWeaponMount: {
          modification: "Standard Weapon Mount",
          availability: "8F",
          cost: "2,500¥",
          source: "Core",
        },
        heavyWeaponMount: {
          modification: "Heavy Weapon Mount",
          availability: "14F",
          cost: "5,000¥",
          source: "Core",
        },
        manualOperation: {
          modification: "Manual Operation",
          availability: "+1",
          cost: "+500¥",
          source: "Core",
        },
        morphingLicensePlate: {
          modification: "Morphing License Plate",
          availability: "8F",
          cost: "1,000¥",
          source: "SR5:R5",
        },
        spoofChip: {
          modification: "Spoof Chip",
          availability: "8F",
          cost: "500¥",
          source: "SR5:R5",
        },
        spikeStrip: {
          modification: "Spike Strip",
          availability: "8R",
          cost: "200¥",
          source: "SR5:R5",
        },
        zapperStrip: {
          modification: "Zapper Strip",
          availability: "12R",
          cost: "2,500¥",
          source: "SR5:R5",
        },
        trackingStrip: {
          modification: "Tracking Strip",
          availability: "8R",
          cost: "600¥",
          source: "SR5:R5",
        },
        offRoadTires: {
          modification: "Off-road Tires",
          availability: 6,
          cost: "400¥ /tire",
          source: "SR5:R5",
        },
        racingTires: {
          modification: "Racing Tires",
          availability: 6,
          cost: "250¥ /tire",
          source: "SR5:R5",
        },
        runFlatTires: {
          modification: "Run Flat Tires",
          availability: 4,
          cost: "250¥ /tire",
          source: "SR5:R5",
        },
      },
    },
  };

  return vehicleMods;
}
